(require :asdf)
(asdf:initialize-source-registry '(:source-registry (:directory #p"/tmp/clamsara-list-baseline-1099d62-xzks71ws/") :ignore-inherited-configuration))
(asdf:initialize-output-translations '(:output-translations (t ("/tmp/clamsara-copy-baseline-v1-tv8tnlqv/fasl/" :implementation)) :ignore-inherited-configuration))
(assert (not (equal (asdf:apply-output-translations #p"/one/package.fasl") (asdf:apply-output-translations #p"/two/package.fasl"))))
(dolist (system '(:clamsara :clamsara/generational :clamsara/quality/support))
  (assert (equal (truename #p"/tmp/clamsara-list-baseline-1099d62-xzks71ws/") (truename (asdf:system-source-directory system)))))
(format t "~&COPY-PROBE-SOURCE ~A~%" (asdf:system-source-directory :clamsara))
(asdf:load-system :clamsara/generational)
(asdf:load-system :clamsara/quality/support)
(load #p"/tmp/clamsara-list-baseline-1099d62-xzks71ws/test/quality/generational.lisp")
(assert (not (find-package "MACLINA.MACHINE")))
(format t "~&COPY-PROBE-BEFORE-SOURCE-LOAD~%")
(load #p"/tmp/clamsara-copy-action-regression-k5ucnx6e/copy-action-tests-v1.lisp")
(format t "~&COPY-PROBE-SOURCE-LOADED~%")
(load #p"/tmp/clamsara-copy-baseline-v1-tv8tnlqv/runner.lisp")
