(in-package #:clamsara.copy-action.independent.v1)
(defvar *native-probe-condition* nil)
(handler-case (run-focused-copy-tests)
  (error (condition) (setf *native-probe-condition* condition)
    (format t "~&COPY-PROBE-ERROR ~S ~A~%" (type-of condition) condition)))
(dolist (owner (reverse *copy-owners*))
  (let ((world (copy-owner-world owner)))
    (format t "~&COPY-PROBE-OWNER ~S phase=~S world=~S copies=~D inits=~D config=~S plan=~S roots-active=~S~%"
            (copy-owner-name owner) (copy-owner-phase owner) (not (null world))
            (copy-owner-copies owner) (copy-owner-inits owner)
            (and world (clamsara::%configuration-state (world-configuration world)))
            (and world (clamsara::%plan-state (world-plan world)))
            (and world (clamsara::simulator-provider-token-active-p (world-root-token world))))))
(format t "~&COPY-PROBE-COUNTS owners=~D actual-worlds=~D completed=~D expected-failure-retained=~D unexpected=~D~%"
        (length *copy-owners*) (count-if #'copy-owner-world *copy-owners*)
        (count :complete *copy-owners* :key #'copy-owner-phase)
        (count :expected-copy-failure-owner-retained *copy-owners* :key #'copy-owner-phase)
        (count :unexpected-failure-retained *copy-owners* :key #'copy-owner-phase))
(when *native-probe-condition* (error *native-probe-condition*))
(assert (= 16 (length *copy-owners*) (count-if #'copy-owner-world *copy-owners*)))
(assert (= 4 (count :complete *copy-owners* :key #'copy-owner-phase)))
(assert (= 12 (count :expected-copy-failure-owner-retained *copy-owners* :key #'copy-owner-phase)))
(format t "~&COPY-PROBE-STRICT-COMPLETE~%")
