;;;; test/client/protocol-contract.lisp
;;;; Native SBCL contract checks for the paper-v14 client protocol declarations.
;;;; These tests use isolated mocks only to check callback shape, raw CAS
;;;; encoding, and root snapshot lifetimes.  They do not pretend to provide a
;;;; target integration or a collector implementation.

(defpackage #:clamsara.client.test
  (:use #:cl #:clamsara)
  (:export #:run-v14-client-contracts))

(in-package #:clamsara.client.test)

(defun %fail (format-control &rest args)
  (error "v14 client contract failure: ~?" format-control args))

(defun %lambda-token (thing)
  (cond ((symbolp thing) (string-upcase (symbol-name thing)))
        ((consp thing) (cons (%lambda-token (car thing))
                             (%lambda-token (cdr thing))))
        (t thing)))

(defun %assert-lambda-list (name expected)
  #+sbcl
  (let* ((gf (symbol-function name))
         (actual (sb-mop:generic-function-lambda-list gf)))
    (unless (equal (%lambda-token actual) (%lambda-token expected))
      (%fail "~s lambda list ~s, expected ~s" name actual expected)))
  #-sbcl
  (declare (ignore name expected)))

(defparameter *v14-client-lambda-lists*
  '((make-object-start-binding (model space metadata))
    (describe-object-start-binding (model binding))
    (bind-object-model (model layout object-start-bindings))
    (valid-reference-p (model value))
    (normalize-reference (model reference))
    (rebuild-reference (model new-start descriptor))
    (reference-address (model start))
    (object-size (model start))
    (object-alignment (model start))
    (object-kind (model start))
    (object-kind-descriptor (model kind))
    (map-reference-locations (model start function))
    (map-weak-descriptors (model start function))
    (map-ephemeron-descriptors (model start function))
    (load-reference (model location &optional order))
    (store-reference-raw (model location value &optional order))
    (cas-reference-raw (model location old new order))
    (make-reference-location-handle (model source-start location))
    (call-with-reference-location (model handle function))
    (make-staged-reference-location-handle
     (model staged-object descriptor-strength descriptor-identity future-start))
    (initialize-object (model address kind size descriptor))
    (copy-object-representation (model source destination))
    (copy-object-to-staging (model source address byte-capacity))
    (map-staged-reference-locations (model staged-object function))
    (map-staged-weak-descriptors (model staged-object function))
    (map-staged-ephemeron-descriptors (model staged-object function))
    (install-staged-object (model staged-object destination))
    (reference-encoding-equal-p (model left right))
    (reference-equal (model left right))
    (make-object-kind-description
     (model name &key size-rule alignment-rule strong-layout
                  weak-descriptions ephemeron-descriptions))
    (describe-object-kind (model description))
    (make-weak-location-description (model identity referent-kind cleared-value))
    (describe-weak-location (model description))
    (make-ephemeron-description (model identity clear-key-p cleared-key cleared-value))
    (describe-ephemeron (model description))
    (make-metadata-field-offer
     (model identity width &key legal-values operations orders object-kinds
            overlaps copy-behavior checkpoint-preservation))
    (describe-metadata-field-offer (model offer))
    (offered-metadata-fields (model))
    (field-read (model field object-or-reference))
    (field-write (model field object-or-reference value))
    (field-cas (model field object-or-reference old new))
    (register-root-provider (root-client provider-id capacity provider))
    (map-provider-roots (provider function))
    (unregister-root-provider (root-client provider-token))
    (with-root-snapshot (root-client coverage function))
    (map-root-locations (snapshot function))
    (load-root (root-client location))
    (store-root (root-client location reference))
    (root-location-kind (root-client location))
    (root-provider-load (root-client provider-token location))
    (root-provider-read (root-client context provider-token location))
    (root-provider-store (root-client context provider-token location reference))
    (register-finalizer (registry context referent callback))
    (cancel-finalizer (registry context token))
    (map-finalizer-registrations (registry function))
    (correct-finalizer-referent (registry token expected corrected-referent))
    (freeze-finalizer-candidate (registry token expected corrected-referent))
    (publish-pending-finalizers (registry))
    (drain-pending-finalizers (registry context))
    (atomic-load (atomics place order))
    (atomic-store (atomics place value order))
    (atomic-cas (atomics place old new order))
    (atomic-fetch-add (atomics place delta order))
    (atomic-bit-set (atomics place index order))
    (atomic-bit-clear (atomics place index order))
    (fence (atomics order))
    (reserve-virtual-range (mapping range))
    (map-logical-pages (mapping range source access))
    (unmap-logical-pages (mapping range))
    (remap-logical-pages (mapping source destination count))
    (protect-logical-pages (mapping range access))
    (flush-address-translations (mapping range))
    (monotonic-clock (diagnostics))
    (fatal-diagnostic (diagnostics reason))
    (request-safepoint (coordinator scope reason))
    (await-safepoint (coordinator token))
    (release-safepoint (coordinator token))))

(defun test-generic-signatures ()
  (dolist (entry *v14-client-lambda-lists*)
    (destructuring-bind (name lambda-list) entry
      (unless (fboundp name) (%fail "missing generic ~s" name))
      (%assert-lambda-list name lambda-list)))
  t)

;;; An explicit mock object model.  Reference encodings differ by displacement,
;;; while REFERENCE-EQUAL compares their normalized object identity.
(defstruct (test-reference (:constructor %make-reference (object displacement)))
  object displacement)
(defstruct (test-location (:constructor %make-location (model object index)))
  model object index)
(defclass test-model ()
  ((objects :initform (make-hash-table) :reader test-objects)))

(defun test-add-object (model object slots)
  (setf (gethash object (test-objects model)) (copy-seq slots))
  (%make-reference object 0))

(defmethod valid-reference-p ((model test-model) value)
  (and (typep value 'test-reference)
       (nth-value 1 (gethash (test-reference-object value) (test-objects model)))))
(defmethod normalize-reference ((model test-model) reference)
  (unless (valid-reference-p model reference) (%fail "invalid test reference"))
  (values (%make-reference (test-reference-object reference) 0)
          (test-reference-displacement reference)))
(defmethod rebuild-reference ((model test-model) new-start descriptor)
  (unless (valid-reference-p model new-start) (%fail "invalid rebuild base"))
  (%make-reference (test-reference-object new-start) descriptor))
(defmethod reference-address ((model test-model) start)
  (unless (valid-reference-p model start) (%fail "invalid address reference"))
  (* 16 (test-reference-object start)))
(defmethod object-size ((model test-model) start)
  (unless (valid-reference-p model start) (%fail "invalid size reference"))
  (* 8 (length (gethash (test-reference-object start) (test-objects model)))))
(defmethod object-alignment ((model test-model) start)
  (unless (valid-reference-p model start) (%fail "invalid alignment reference"))
  8)
(defmethod object-kind ((model test-model) start)
  (unless (valid-reference-p model start) (%fail "invalid kind reference"))
  :test-kind)
(defmethod map-reference-locations ((model test-model) start function)
  (unless (valid-reference-p model start) (%fail "invalid map reference"))
  (dotimes (i (length (gethash (test-reference-object start) (test-objects model))))
    (funcall function i (%make-location model (test-reference-object start) i)))
  (values))
(defmethod load-reference ((model test-model) location &optional order)
  (declare (ignore order))
  (aref (gethash (test-location-object location) (test-objects model))
        (test-location-index location)))
(defmethod store-reference-raw ((model test-model) location value &optional order)
  (declare (ignore order))
  (setf (aref (gethash (test-location-object location) (test-objects model))
             (test-location-index location)) value))
(defmethod reference-encoding-equal-p ((model test-model) left right)
  (and (typep left 'test-reference) (typep right 'test-reference)
       (= (test-reference-object left) (test-reference-object right))
       (= (test-reference-displacement left) (test-reference-displacement right))))
(defmethod reference-equal ((model test-model) left right)
  (multiple-value-bind (l ignored-left) (normalize-reference model left)
    (declare (ignore ignored-left))
    (multiple-value-bind (r ignored-right) (normalize-reference model right)
      (declare (ignore ignored-right))
      (= (test-reference-object l) (test-reference-object r)))))
(defmethod cas-reference-raw ((model test-model) location old new order)
  (declare (ignore order))
  (let ((observed (load-reference model location)))
    (if (reference-encoding-equal-p model observed old)
        (progn (store-reference-raw model location new) (values observed t))
        (values observed nil))))

(defun test-object-model-semantics ()
  (let* ((model (make-instance 'test-model))
         (base (test-add-object model 11 (vector nil)))
         (tagged (rebuild-reference model base 3))
         (location (let (answer)
                     (map-reference-locations model base
                                               (lambda (id loc)
                                                 (declare (ignore id))
                                                 (setf answer loc)))
                     answer)))
    (unless (and (valid-reference-p model tagged)
                 (reference-equal model base tagged)
                 (not (reference-encoding-equal-p model base tagged)))
      (%fail "normalized identity and stored encoding were conflated"))
    (multiple-value-bind (observed success)
        (cas-reference-raw model location tagged base :acq-rel)
      (unless (and (eq observed nil) (not success))
        (%fail "raw CAS did not reject encoding mismatch")))
    (store-reference-raw model location tagged :release)
    (multiple-value-bind (observed success)
        (cas-reference-raw model location tagged base :acq-rel)
      (unless (and (reference-encoding-equal-p model observed tagged) success
                   (reference-encoding-equal-p model (load-reference model location) base))
        (%fail "raw CAS did not return observed encoding and update")))
    t))

;;; Root callback shape/lifetime mock.  No roots are invented by this test.
(defclass test-roots () ((value :initform nil :accessor test-root-value)))
(defmethod with-root-snapshot ((roots test-roots) coverage function)
  (unless (eq coverage :covered) (%fail "uncovered snapshot accepted"))
  (funcall function roots))
(defmethod map-root-locations ((snapshot test-roots) function)
  (funcall function snapshot :only-root-location)
  (values))
(defmethod load-root ((roots test-roots) location)
  (unless (eq location :only-root-location) (%fail "foreign root location"))
  (test-root-value roots))
(defmethod store-root ((roots test-roots) location reference)
  (unless (eq location :only-root-location) (%fail "foreign root location"))
  (setf (test-root-value roots) reference))
(defmethod root-location-kind ((roots test-roots) location)
  (declare (ignore roots))
  (if (eq location :only-root-location) :writable :invalid))
(defun test-root-semantics ()
  (let ((roots (make-instance 'test-roots)) (seen nil))
    (store-root roots :only-root-location :reference)
    (with-root-snapshot roots :covered
      (lambda (snapshot)
        (map-root-locations snapshot
          (lambda (owner location)
            (unless (and (eq owner roots) (eq location :only-root-location))
              (%fail "root callback did not expose owner and location"))
            (push (load-root roots location) seen)))))
    (unless (equal seen '(:reference)) (%fail "root snapshot missed stored value"))
    t))

(defclass unsupported-client () ())
(defun test-unsupported-capability-is-not-faked ()
  ;; A class with no methods must not appear to offer a mapping capability.
  (handler-case
      (progn (valid-reference-p (make-instance 'unsupported-client) :value)
             (%fail "unimplemented operation looked supported"))
    (error () t)))

(defun run-v14-client-contracts ()
  (test-generic-signatures)
  (test-object-model-semantics)
  (test-root-semantics)
  (test-unsupported-capability-is-not-faked)
  ;; Deliberately omitted target mechanisms (staging, provider guarded reads,
  ;; atomics, mapping, finalizer scheduling) are tested by concrete clients;
  ;; this protocol test never labels their absence as support.
  (values t :complete))
