;;;; test/test-strata.lisp -- stratum + matrix closure unit tests.

(in-package #:clamsara)

(deftest strata-scalar ()
  (let ((s (make-stratum :mark (g-word) :bit 65536)))
    (s-set-bit s 5) (s-set-bit s 100) (s-set-bit s 65535)
    (if (= (s-popcount s) 3) (values t "scalar ok")
        (values nil "popcount wrong"))))

(deftest strata-u4 ()
  (let ((s (make-stratum :age (g-word) :u4 65536)))
    (s-set s 8 7) (s-set s 9 15)
    (if (and (= (s-get s 8) 7) (= (s-get s 9) 15)) (values t "u4 ok")
        (values nil "u4 wrong"))))

(deftest strata-for-set-cells ()
  (let ((s (make-stratum :m (g-word) :bit 65536)) got)
    (s-set-bit s 5) (s-set-bit s 100) (s-set-bit s 65535)
    (s-for-set-cells s nil (lambda (a) (push a got)))
    (if (equal (sort got #'<) '(5 100 65535)) (values t "iter ok")
        (values nil "iteration wrong"))))

(deftest strata-project ()
  (let ((card (make-stratum :card (g-card) :bit 65536))
        (pg (make-stratum :pg (g-block) :bit 65536)))
    (s-set-bit card 0) (s-set-bit card (* 5 (g-card)))
    (s-project card pg :any)
    (if (= (s-popcount pg) 2) (values t "project ok")
        (values nil "project wrong"))))

(deftest matrix-closure ()
  (let ((m (make-matrix-stratum (g-block) 8)))
    (matrix-set m 0 1) (matrix-set m 1 2) (matrix-set m 2 4)
    (let ((roots (make-array 8 :element-type 'bit :initial-element 0)))
      (setf (sbit roots 0) 1)
      (let ((live (matrix-closure m roots)))
        (if (and (eql 1 (sbit live 0)) (eql 1 (sbit live 1))
                 (eql 1 (sbit live 2)) (eql 1 (sbit live 4))
                 (eql 0 (sbit live 3)))
            (values t "closure ok")
            (values nil "closure wrong"))))))

(deftest page-resource ()
  (let ((pr (make-instance 'bitmap-page-resource :total-pages 64 :heap nil)))
    (let ((p1 (page-resource-get pr 3)) (p2 (page-resource-get pr 2)))
      (page-resource-release pr p1 3)
      (if (and p1 p2 (not (= p1 p2)) (= (page-resource-get pr 3) p1))
          (values t "pr ok") (values nil "pr wrong")))))
