(require :asdf)
(asdf:initialize-source-registry
 '(:source-registry (:directory #p"/tmp/clamsara-mapc-integrated-tard99a7/") :ignore-inherited-configuration))
(asdf:initialize-output-translations
 '(:output-translations (t ("/tmp/clamsara-mapc-integration-native-q70qh9xb/fasl/" :implementation)) :ignore-inherited-configuration))
(assert (equal (truename #p"/tmp/clamsara-mapc-integrated-tard99a7/")
               (truename (asdf:system-source-directory :clamsara))))
(assert (not (equal (asdf:apply-output-translations #p"/one/package.fasl")
                    (asdf:apply-output-translations #p"/two/package.fasl"))))
(asdf:load-system :clamsara/workload)
(assert (equal (truename #p"/tmp/clamsara-mapc-integrated-tard99a7/")
               (truename (asdf:system-source-directory :clamsara/workload))))
(assert (equal (truename #p"/home/iskam/quicklisp/local-projects/Maclina/")
               (truename (asdf:system-source-directory :maclina))))


(asdf:test-system :clamsara)
(asdf:test-system :clamsara/tools/test)
(asdf:test-system :clamsara/workload/test)
(asdf:test-system :clamsara/generational/test)
(asdf:test-system :clamsara/quality/generational/test)
(asdf:load-system :clamsara/quality)
(clamsara.structure:assert-project-structure :include-optional-loaded t)
;; Unchanged independent behavior and capacity sources, in distinct packages.
(load #p"/tmp/clamsara-gcbench-52e08f1-tfa6uf75/independent-review/gabriel-next/mapc-strict-regression-v2.lisp")
(load #p"/tmp/clamsara-gcbench-52e08f1-tfa6uf75/independent-review/gabriel-next/native-strict9-c2zybsxw/runner.lisp")
(load #p"/tmp/clamsara-gcbench-52e08f1-tfa6uf75/independent-review/gabriel-next/capacity-strengthening-v3/capacity-ownership-v3.lisp")
(load #p"/tmp/clamsara-gcbench-52e08f1-tfa6uf75/independent-review/gabriel-next/capacity-native-v3-y4t009zr/runner.lisp")
(assert (clamsara.workload.mapc.test:run-workload-mapc-tests))
(assert (clamsara.workload.mapc-capacity.test:run-workload-mapc-capacity-tests))
(format t "~&MAPC-INTEGRATED-AND-ARCHIVED-REPLAY-PASS~%")
