(require :asdf)
(assert (equal (truename #p"/home/iskam/src/vibe/Clamsara/")
               (truename (asdf:system-source-directory :clamsara))))
(require :asdf)
(asdf:test-system :clamsara)
(asdf:test-system :clamsara/tools/test)
(asdf:test-system :clamsara/workload/test)
(asdf:test-system :clamsara/generational/test)
(asdf:test-system :clamsara/quality/generational/test)
(asdf:load-system :clamsara/quality)
(clamsara.structure:assert-project-structure :include-optional-loaded t)
(format t "~&GENERATIONAL-CHECKPOINT-COMPONENTS-PASS~%")

(load #p"/tmp/clamsara-staged-ledger-review-tirxn_0p/independent-review/cas-contract/acceptance-03.lisp")
(load #p"/tmp/clamsara-cas-boundary-red-5tso_czk/cases-02.lisp")
(format t "~&CAS-PARENT-EXPECTED-FATAL-WORLDS ~D~%" (length clamsara.cascade-probe::*expected-fatal-worlds*))
(format t "~&CAS-COMPONENTS-AND-102-HISTORIES-PASS~%")
