(require :asdf)
(assert (equal (truename #p"/home/iskam/src/vibe/Clamsara/")
               (truename (asdf:system-source-directory :clamsara))))
(require :asdf)
(asdf:test-system :clamsara)
(asdf:test-system :clamsara/tools/test)
(asdf:test-system :clamsara/workload/test)
(asdf:test-system :clamsara/generational/test)
(asdf:test-system :clamsara/quality/generational/test)
(asdf:load-system :clamsara/quality)
(clamsara.structure:assert-project-structure :include-optional-loaded t)
(format t "~&GENERATIONAL-CHECKPOINT-COMPONENTS-PASS~%")

(load #p"/tmp/clamsara-staged-ledger-review-tirxn_0p/independent-review/cas-contract/acceptance-03.lisp")
(load #p"/tmp/clamsara-cas-fixed-review-byz5pwd5/independent-review/cas-fixed/additional-05.lisp")
(load #p"/tmp/clamsara-cas-final-review-pvyqoprb/independent-review/cas-final/claims-transforms-03.lisp")
(uiop:symbol-call :clamsara.quality.barrier-history :run-barrier-history-tests)
(uiop:symbol-call :clamsara.quality.barrier-history :run-barrier-edge-tests)
(uiop:symbol-call :clamsara.quality.barrier-boundaries :run-barrier-boundary-tests)
(format t "~&CAS-INTEGRATED-164-REPEAT-INDEPENDENT-176-PASS~%")
