;;;; Parent probe of host CLOS semantics, not a Clamsara acceptance test.
(defpackage #:clamsara.opaque-mop-probe (:use #:cl))
(in-package #:clamsara.opaque-mop-probe)
(defclass token-a () ())
(defclass token-b () ())
(defgeneric around-only (token))
(defmethod around-only :around ((token token-a)) (declare (ignore token)) :around-return)
(defgeneric before-only (token))
(defmethod before-only :before ((token token-a)) (declare (ignore token)) nil)
(defgeneric after-only (token))
(defmethod after-only :after ((token token-a)) (declare (ignore token)) nil)
(defgeneric split-methods (token))
(defmethod split-methods ((token token-a)) (declare (ignore token)) :primary-a)
(defmethod split-methods :around ((token token-b)) (declare (ignore token)) :around-b)
(defgeneric guarded-around (token))
(defmethod guarded-around :around ((token token-a))
  (declare (ignore token))
  (if (next-method-p) (call-next-method) :without-next))
(defgeneric unguarded-around (token))
(defmethod unguarded-around :around ((token token-a))
  (declare (ignore token)) (call-next-method))
(defun observe (name function argument)
  (format t "~&MOP-PROBE ~S applicable=~S result=~S~%" name
          (mapcar #'method-qualifiers (compute-applicable-methods function (list argument)))
          (handler-case (list :returned (funcall function argument))
            (error (condition) (list :signaled (type-of condition) (princ-to-string condition))))))
(let ((a (make-instance 'token-a)) (b (make-instance 'token-b)))
  (observe :around-only #'around-only a)
  (observe :before-only #'before-only a)
  (observe :after-only #'after-only a)
  (observe :split-a #'split-methods a)
  (observe :split-b #'split-methods b)
  (observe :guarded-around #'guarded-around a)
  (observe :unguarded-around #'unguarded-around a)
  (format t "~&MOP-SPECIALIZERS ~S~%"
          (mapcar (lambda (method)
                    (mapcar #'class-name (sb-mop:method-specializers method)))
                  (sb-mop:generic-function-methods #'around-only))))
