(:STATUS :FAILED :ROOT "/tmp/clamsara-shared-copy-04bff62-xzksq1om/" :FILES
 ("/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/client/atomics.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/client/coordinator.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/client/diagnostics.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/client/finalizers.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/client/mapping.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/client/metadata.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/client/object-model.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/client/roots.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/construction/build.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/construction/graph.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/construction/layout.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/construction/protocol.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/construction/records.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/construction/validation.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/host/address-space.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/host/atomics.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/host/auxiliary.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/host/coordinator.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/host/object-model.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/host/resources.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/host/roots.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/metadata/metadata.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/package.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/runtime/allocation.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/runtime/barrier.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/runtime/cycle.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/runtime/finalizers.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/runtime/protocol.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/runtime/records.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/runtime/spaces.lisp"
  "/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/runtime/trace.lisp"
  #1="/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/workload/control.lisp"
  #2="/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/workload/gabriel.lisp"
  #3="/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/workload/gcbench.lisp"
  #4="/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/workload/maclina.lisp"
  #5="/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/workload/numbers.lisp"
  #6="/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/workload/protocol.lisp"
  #7="/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/workload/roots.lisp"
  #8="/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/workload/setup.lisp"
  #9="/tmp/clamsara-shared-copy-04bff62-xzksq1om/src/workload/source.lisp")
 :DEFINITION-COUNT 1018 :NATIVE-READER T :NATIVE-INTROSPECTION T
 :NATIVE-COMPILATION-PREREQUISITE
 "Load :CLAMSARA through ASDF before INSPECT-LOADED." :ISSUES
 ((:CODE :READER-ERROR :LOCATION
   (:FILE #1# :FORM-INDEX 1 :OFFSET 101 :LINE 3 :PATH NIL) :READER-POSITION 537
   :CONDITION-TYPE SB-INT:SIMPLE-READER-PACKAGE-ERROR :MESSAGE
   "Package MACLINA.MACHINE does not exist.

  Line: 10, Column: 63, File-Position: 536

  Stream: #<SB-SYS:FD-STREAM for \"file /tmp/clamsara-shared-copy-04bff62-xzksq1om/src/workload/control.lisp\" {1209C78373}>")
  (:CODE :READER-ERROR :LOCATION
   (:FILE #4# :FORM-INDEX 1 :OFFSET 504 :LINE 11 :PATH NIL) :READER-POSITION
   563 :CONDITION-TYPE SB-INT:SIMPLE-READER-PACKAGE-ERROR :MESSAGE
   "Package MACLINA.VM-CROSS does not exist.

  Line: 12, Column: 58, File-Position: 562

  Stream: #<SB-SYS:FD-STREAM for \"file /tmp/clamsara-shared-copy-04bff62-xzksq1om/src/workload/maclina.lisp\" {120B3A8373}>")
  (:CODE :READER-ERROR :LOCATION
   (:FILE #5# :FORM-INDEX 13 :OFFSET 5743 :LINE 122 :PATH NIL) :READER-POSITION
   6056 :CONDITION-TYPE SB-INT:SIMPLE-READER-PACKAGE-ERROR :MESSAGE
   "Package CLOSTRUM does not exist.

  Line: 128, Column: 42, File-Position: 6055

  Stream: #<SB-SYS:FD-STREAM for \"file /tmp/clamsara-shared-copy-04bff62-xzksq1om/src/workload/numbers.lisp\" {120B3F0373}>")
  (:CODE :READER-ERROR :LOCATION
   (:FILE #7# :FORM-INDEX 22 :OFFSET 9234 :LINE 192 :PATH NIL) :READER-POSITION
   9430 :CONDITION-TYPE SB-INT:SIMPLE-READER-PACKAGE-ERROR :MESSAGE
   "Package MACLINA.VM-CROSS does not exist.

  Line: 197, Column: 46, File-Position: 9429

  Stream: #<SB-SYS:FD-STREAM for \"file /tmp/clamsara-shared-copy-04bff62-xzksq1om/src/workload/roots.lisp\" {1202FC8363}>")
  (:CODE :READER-ERROR :LOCATION
   (:FILE #8# :FORM-INDEX 3 :OFFSET 10239 :LINE 189 :PATH NIL) :READER-POSITION
   11153 :CONDITION-TYPE SB-INT:SIMPLE-READER-PACKAGE-ERROR :MESSAGE
   "Package MACLINA.VM-CROSS does not exist.

  Line: 204, Column: 66, File-Position: 11152

  Stream: #<SB-SYS:FD-STREAM for \"file /tmp/clamsara-shared-copy-04bff62-xzksq1om/src/workload/setup.lisp\" {1203090363}>")
  (:CODE :READER-ERROR :LOCATION
   (:FILE #9# :FORM-INDEX 1 :OFFSET 95 :LINE 3 :PATH NIL) :READER-POSITION 602
   :CONDITION-TYPE SB-INT:SIMPLE-READER-PACKAGE-ERROR :MESSAGE
   "Package CLOSTRUM does not exist.

  Line: 13, Column: 34, File-Position: 601

  Stream: #<SB-SYS:FD-STREAM for \"file /tmp/clamsara-shared-copy-04bff62-xzksq1om/src/workload/source.lisp\" {120310A463}>")
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%GABRIEL-REFERENCE-PATH" :LOCATION
   (:FILE #2# :FORM-INDEX 3 :OFFSET 1388 :LINE 36 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%GABRIEL-ENTRY-FORM" :LOCATION
   (:FILE #2# :FORM-INDEX 4 :OFFSET 1484 :LINE 39 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::RUN-CANONICAL-GABRIEL" :LOCATION
   (:FILE #2# :FORM-INDEX 5 :OFFSET 1535 :LINE 42 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::RUN-CANONICAL-GABRIEL-TESTS" :LOCATION
   (:FILE #2# :FORM-INDEX 6 :OFFSET 3446 :LINE 78 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%BOEHM-ENTRY-FORM" :LOCATION
   (:FILE #3# :FORM-INDEX 3 :OFFSET 519 :LINE 12 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::RUN-UNMODIFIED-BOEHM-GCBENCH" :LOCATION
   (:FILE #3# :FORM-INDEX 4 :OFFSET 574 :LINE 15 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%GUEST-BIGNUM-P" :LOCATION
   (:FILE #5# :FORM-INDEX 3 :OFFSET 289 :LINE 7 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%BIGNUM-WORD" :LOCATION
   (:FILE #5# :FORM-INDEX 4 :OFFSET 552 :LINE 13 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%SET-BIGNUM-WORD" :LOCATION
   (:FILE #5# :FORM-INDEX 5 :OFFSET 740 :LINE 18 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%HOST-INTEGER->GUEST" :LOCATION
   (:FILE #5# :FORM-INDEX 6 :OFFSET 954 :LINE 24 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%GUEST-BIGNUM->HOST" :LOCATION
   (:FILE #5# :FORM-INDEX 7 :OFFSET 1751 :LINE 41 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%GUEST-NUMBER->HOST" :LOCATION
   (:FILE #5# :FORM-INDEX 8 :OFFSET 2797 :LINE 62 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%NUMERIC-PREDICATE-ARGUMENT" :LOCATION
   (:FILE #5# :FORM-INDEX 9 :OFFSET 3066 :LINE 68 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%ADMIT-NUMERIC-RESULT" :LOCATION
   (:FILE #5# :FORM-INDEX 10 :OFFSET 3436 :LINE 76 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%NUMERIC-RESULTS->GUEST" :LOCATION
   (:FILE #5# :FORM-INDEX 11 :OFFSET 3700 :LINE 82 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME "CLAMSARA::%GUEST-EQL"
   :LOCATION (:FILE #5# :FORM-INDEX 12 :OFFSET 4898 :LINE 104 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%NUMERIC-TYPE-SPECIFIER" :LOCATION
   (:FILE #5# :FORM-INDEX 13 :OFFSET 5258 :LINE 113 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::MAKE-WORKLOAD-KIND" :LOCATION
   (:FILE #6# :FORM-INDEX 6 :OFFSET 1565 :LINE 37 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%WORKLOAD-KIND" :LOCATION
   (:FILE #6# :FORM-INDEX 8 :OFFSET 3968 :LINE 79 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%POSITIVE-SIZE" :LOCATION
   (:FILE #6# :FORM-INDEX 9 :OFFSET 4173 :LINE 84 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%WORKLOAD-KIND-ALLOCATION" :LOCATION
   (:FILE #6# :FORM-INDEX 10 :OFFSET 4463 :LINE 91 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%REQUIRE-OPEN" :LOCATION
   (:FILE #6# :FORM-INDEX 11 :OFFSET 4936 :LINE 100 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%CONFIGURATION-SLOT" :LOCATION
   (:FILE #6# :FORM-INDEX 12 :OFFSET 5103 :LINE 105 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::MAKE-WORKLOAD-ENVIRONMENT" :LOCATION
   (:FILE #6# :FORM-INDEX 13 :OFFSET 5362 :LINE 112 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::CLOSE-WORKLOAD-ENVIRONMENT" :LOCATION
   (:FILE #6# :FORM-INDEX 14 :OFFSET 7817 :LINE 154 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%WITH-SLOT-LOCATION" :LOCATION
   (:FILE #6# :FORM-INDEX 15 :OFFSET 8438 :LINE 168 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::WORKLOAD-TEMPORARY-ROOT-CLEAR" :LOCATION
   (:FILE #6# :FORM-INDEX 16 :OFFSET 10202 :LINE 206 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::WORKLOAD-TEMPORARY-ROOT-LOAD" :LOCATION
   (:FILE #6# :FORM-INDEX 17 :OFFSET 10461 :LINE 215 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::WORKLOAD-READ-SLOT" :LOCATION
   (:FILE #6# :FORM-INDEX 18 :OFFSET 10671 :LINE 221 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::WORKLOAD-WRITE-SLOT" :LOCATION
   (:FILE #6# :FORM-INDEX 19 :OFFSET 11026 :LINE 230 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::WORKLOAD-REFERENCE-P" :LOCATION
   (:FILE #6# :FORM-INDEX 20 :OFFSET 12941 :LINE 272 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::WORKLOAD-ALLOCATE" :LOCATION
   (:FILE #6# :FORM-INDEX 21 :OFFSET 13121 :LINE 276 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::WORKLOAD-ENSURE-REFERENCE" :LOCATION
   (:FILE #6# :FORM-INDEX 22 :OFFSET 16077 :LINE 329 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::MAKE-WORKLOAD-ROOT-SET" :LOCATION
   (:FILE #7# :FORM-INDEX 3 :OFFSET 576 :LINE 16 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME "CLAMSARA::%ROOT-STORE"
   :LOCATION (:FILE #7# :FORM-INDEX 4 :OFFSET 1106 :LINE 26 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::WORKLOAD-ROOT-LOAD" :LOCATION
   (:FILE #7# :FORM-INDEX 5 :OFFSET 2000 :LINE 47 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::WORKLOAD-ROOT-CLEAR" :LOCATION
   (:FILE #7# :FORM-INDEX 6 :OFFSET 2310 :LINE 53 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::WORKLOAD-ROOT-PLACE" :LOCATION
   (:FILE #7# :FORM-INDEX 7 :OFFSET 2391 :LINE 56 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFMACRO :NAME
   "CLAMSARA::WITH-WORKLOAD-ROOT" :LOCATION
   (:FILE #7# :FORM-INDEX 8 :OFFSET 2480 :LINE 59 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFMACRO :NAME
   "CLAMSARA::WITH-WORKLOAD-ROOTS" :LOCATION
   (:FILE #7# :FORM-INDEX 9 :OFFSET 3023 :LINE 71 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%WITH-WORKLOAD-ROOT-VALUES" :LOCATION
   (:FILE #7# :FORM-INDEX 10 :OFFSET 3722 :LINE 86 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%NEW-WORKLOAD-ROOT-WALK" :LOCATION
   (:FILE #7# :FORM-INDEX 14 :OFFSET 5114 :LINE 116 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%CLEAR-WORKLOAD-ROOT-WALK" :LOCATION
   (:FILE #7# :FORM-INDEX 15 :OFFSET 5308 :LINE 121 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::%MAKE-WORKLOAD-NATIVE-CELLS" :LOCATION
   (:FILE #7# :FORM-INDEX 16 :OFFSET 5481 :LINE 126 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::MAKE-WORKLOAD-ROOT-PROVIDER" :LOCATION
   (:FILE #7# :FORM-INDEX 18 :OFFSET 6714 :LINE 146 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::WORKLOAD-PROVIDER-TEMPORARY-LOCATIONS" :LOCATION
   (:FILE #7# :FORM-INDEX 19 :OFFSET 8345 :LINE 171 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::WORKLOAD-PROVIDER-LOCATION" :LOCATION
   (:FILE #7# :FORM-INDEX 20 :OFFSET 8581 :LINE 176 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::WORKLOAD-PROVIDER-BIND-MACLINA" :LOCATION
   (:FILE #7# :FORM-INDEX 21 :OFFSET 8880 :LINE 182 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::WORKLOAD-PROVIDER-BIND-VM" :LOCATION
   (:FILE #7# :FORM-INDEX 22 :OFFSET 9130 :LINE 188 :PATH NIL))
  (:CODE :MISSING-LOADED-FUNCTION :OPERATOR DEFUN :NAME
   "CLAMSARA::MAKE-WORKLOAD-RUNTIME" :LOCATION
   (:FILE #8# :FORM-INDEX 3 :OFFSET 610 :LINE 14 :PATH NIL))))
