(require :asdf)
(asdf:initialize-source-registry '(:source-registry (:directory #p"/tmp/clamsara-shared-copy-04bff62-xzksq1om/") :ignore-inherited-configuration))
(asdf:initialize-output-translations '(:output-translations (t ("/tmp/clamsara-shared-copy-full-ykcuj5ss/fasl/" :implementation)) :ignore-inherited-configuration))
(assert (not (equal (asdf:apply-output-translations #p"/one/package.fasl") (asdf:apply-output-translations #p"/two/package.fasl"))))
(assert (equal (truename #p"/tmp/clamsara-shared-copy-04bff62-xzksq1om/") (truename (asdf:system-source-directory :clamsara))))
(format t "~&SHARED-COPY-CANDIDATE-SOURCE ~A~%" (asdf:system-source-directory :clamsara))
(asdf:test-system :clamsara)
(format t "~&SHARED-COPY-MAIN-PASS~%")
(asdf:test-system :clamsara/tools/test)
(format t "~&SHARED-COPY-TOOLS-PASS~%")
(asdf:test-system :clamsara/generational/test)
(format t "~&SHARED-COPY-GENERATIONAL-PASS~%")
(asdf:test-system :clamsara/quality/generational/test)
(format t "~&SHARED-COPY-GENERATIONAL-QUALITY-PASS~%")
(asdf:load-system :clamsara/quality)
(uiop:symbol-call :clamsara.structure :assert-project-structure :include-optional-loaded t)
(format t "~&SHARED-COPY-STRUCTURE-PASS~%")
(assert (not (find-package "MACLINA.MACHINE")))
(format t "~&SHARED-COPY-CORE-SUITES-COMPLETE~%")
