;;;; Native executable contracts for the v14 construction kernel.
(require :asdf)
(asdf:load-asd (truename "clamsara.asd"))
(asdf:load-system :clamsara/construction)

(in-package #:clamsara)

(defvar *ct-checks* 0)
(defvar *ct-log* nil)
(defun %ct-check (truth format-control &rest arguments)
  (incf *ct-checks*)
  (unless truth (error (apply #'format nil format-control arguments))))
(defun %ct-reason (thunk)
  (handler-case (progn (funcall thunk) nil)
    (construction-rejected (condition)
      (construction-rejection-reason condition))
    (error (condition)
      (declare (ignore condition))
      :other-error)))

(defclass %ct-component (component)
  ((name :initarg :name :reader %ct-name)
   (dependencies :initform nil :accessor %ct-dependencies)
   (resources :initform nil :accessor %ct-resources)
   (placements :initform nil :accessor %ct-placements)
   (constraints :initform nil :accessor %ct-constraints)
   (barriers :initform nil :accessor %ct-barriers)
   (results :initform nil :accessor %ct-results)
   (cohort :initform nil :accessor %ct-cohort)
   (requires-model-p :initform nil :initarg :requires-model-p
                     :accessor %ct-requires-model-p)
   (fail-init-p :initform nil :initarg :fail-init-p
                :accessor %ct-fail-init-p)
   (declaration-count :initform 0 :accessor %ct-declaration-count)))
(defclass %ct-space (%ct-component)
  ((map :initarg :map :reader %ct-map)
   (map-description-count :initform 0 :accessor %ct-map-description-count)))

(defmethod component-dependencies ((component %ct-component))
  (incf (%ct-declaration-count component))
  (copy-list (%ct-dependencies component)))
(defmethod component-resources ((component %ct-component))
  (copy-list (%ct-resources component)))
(defmethod component-placement-requests ((component %ct-component))
  (copy-list (%ct-placements component)))
(defmethod component-constraints ((component %ct-component))
  (copy-list (%ct-constraints component)))
(defmethod component-barrier-contributions ((component %ct-component))
  (copy-list (%ct-barriers component)))
(defmethod component-result-contributions ((component %ct-component))
  (copy-list (%ct-results component)))
(defmethod component-cohort ((component %ct-component)) (%ct-cohort component))
(defmethod component-requires-bound-object-model-p ((component %ct-component))
  (%ct-requires-model-p component))
(defmethod space-object-start-map ((space %ct-space))
  (when (> (incf (%ct-map-description-count space)) 1)
    (error "SPACE-OBJECT-START-MAP called more than once"))
  (%ct-map space))
(defmethod initialize-component ((component %ct-component) context)
  (call-next-method)
  (when (%ct-requires-model-p component)
    (%ct-check (typep (configuration-object-model
                       (construction-configuration context))
                      '%ct-bound-model)
               "~S initialized without bound model" (%ct-name component)))
  (push (list :initialize (%ct-name component)) *ct-log*)
  (when (%ct-fail-init-p component)
    (error "injected init failure")))
(defmethod validate-component ((component %ct-component) configuration)
  (call-next-method)
  (%ct-check (eq :private (%configuration-state configuration))
             "validation observed publication")
  (push (list :validate (%ct-name component)) *ct-log*))
(defmethod activate-component ((component %ct-component) context)
  (call-next-method)
  (%ct-check (eq :private
                 (%configuration-state (construction-configuration context)))
             "activation observed publication")
  (push (list :activate (%ct-name component)) *ct-log*))
(defmethod deactivate-component ((component %ct-component) context)
  (declare (ignore context))
  (call-next-method)
  (push (list :deactivate (%ct-name component)) *ct-log*))

(defstruct (%ct-offer (:constructor %make-ct-offer))
  name base extent alignment page-size accesses address-width exclusions)
(defclass %ct-address ()
  ((offer :initform (%make-ct-offer :name :test :base 4096 :extent 4096
                                    :alignment 16 :page-size 256
                                    :accesses '(:read :write :atomic)
                                    :address-width 32 :exclusions nil)
          :reader %ct-offer)
   (installed :initform nil :accessor %ct-installed)))
(defclass %ct-installed-layout ()
  ((solution :initarg :solution :reader %ct-solution)))
(defmethod managed-arena-offer ((address %ct-address)) (%ct-offer address))
(defmethod describe-managed-arena-offer
    ((address %ct-address) (offer %ct-offer))
  (declare (ignore address))
  (values (%ct-offer-name offer) (%ct-offer-base offer)
          (%ct-offer-extent offer) (%ct-offer-alignment offer)
          (%ct-offer-page-size offer) (copy-list (%ct-offer-accesses offer))
          (%ct-offer-address-width offer) (copy-tree (%ct-offer-exclusions offer))))
(defmethod %address-space-policy-supported-p
    ((address %ct-address) kind identity)
  (declare (ignore address))
  (case kind
    (:lifetime (eql identity :configuration))
    (:mobility (eql identity :fixed))
    (:reclaimability (eql identity :collector))
    (otherwise nil)))
(defmethod %evaluate-construction-constraint
    ((address %ct-address) kind values parameters)
  (declare (ignore address kind values parameters))
  (values nil nil))
(defmethod validate-managed-layout
    ((address %ct-address) (layout %reference-layout))
  (%ct-check (null (%ct-installed address)) "layout replaced a live layout")
  (%ct-check (typep layout '%reference-layout) "wrong solved layout")
  (values))
(defmethod install-managed-layout
    ((address %ct-address) (layout %reference-layout))
  (let ((installed (make-instance '%ct-installed-layout :solution layout)))
    (setf (%ct-installed address) installed)
    (push '(:acquire :layout) *ct-log*)
    (values installed (cons address installed))))
(defmethod release-managed-layout ((address %ct-address) capability)
  (unless (null (cdr capability))
    (%ct-check (and (eq address (car capability))
                    (eq (%ct-installed address) (cdr capability)))
               "foreign layout capability")
    (push '(:release :layout) *ct-log*)
    (setf (%ct-installed address) nil
          (cdr capability) nil))
  (values))

(defstruct (%ct-binding (:constructor %make-ct-binding)) space map)
(defclass %ct-model () ())
(defclass %ct-bound-model ()
  ((layout :initarg :layout) (bindings :initarg :bindings)))
(defmethod make-object-start-binding
    ((model %ct-model) space metadata)
  (declare (ignore model))
  (%make-ct-binding :space space :map metadata))
(defmethod describe-object-start-binding
    ((model %ct-model) (binding %ct-binding))
  (declare (ignore model))
  (values (%ct-binding-space binding) (%ct-binding-map binding)))
(defmethod bind-object-model ((model %ct-model) layout bindings)
  (declare (ignore model))
  (push '(:bind :model) *ct-log*)
  (make-instance '%ct-bound-model :layout layout :bindings (copy-seq bindings)))

(defun %register-installed-layout-auxiliary (construction layout identity)
  (%register-resource-auxiliary construction identity layout)
  (%register-resource-auxiliary construction identity (%ct-solution layout))
  (values))
(defun %register-bound-object-model-auxiliary (construction model identity)
  (%register-resource-auxiliary construction identity model)
  (values))

(defstruct (%ct-resource-release (:constructor %make-ct-resource-release))
  clients identity manifest (closed-p nil) (released-p nil))
(defclass %ct-clients ()
  ((model :initarg :model :reader construction-object-model)
   (coordinator :initarg :coordinator :reader construction-stop-coordinator)
   (address :initarg :address :reader construction-address-space-client)))
(defmethod construction-client-profile ((clients %ct-clients))
  (declare (ignore clients)) :sequential-host)
(defmethod construction-root-client ((clients %ct-clients))
  (declare (ignore clients)) :test-roots)
(defmethod construction-atomics-client ((clients %ct-clients))
  (declare (ignore clients)) :test-atomics)
(defmethod construction-diagnostics-client ((clients %ct-clients))
  (declare (ignore clients)) :test-diagnostics)
(defmethod %acquire-construction-resource
    ((clients %ct-clients) construction description placement)
  (declare (ignore construction))
  (%ct-check (null placement) "test provider received addressed resource")
  (let* ((identity (%resource-description-identity description))
         (entries (%resource-description-logical-entry-bound description))
         (handle (make-array entries))
         (release (%make-ct-resource-release :clients clients :identity identity)))
    (push (list :acquire identity) *ct-log*)
    (values handle
            (max (%resource-description-minimum-physical-bytes description)
                 entries)
            entries
            (%resource-description-auxiliary-bytes description)
            release)))
(defmethod %release-acquired-construction-resource
    ((clients %ct-clients) (release %ct-resource-release))
  (%ct-check (eq clients (%ct-resource-release-clients release))
             "foreign resource release")
  (unless (%ct-resource-release-released-p release)
    (setf (%ct-resource-release-released-p release) t)
    (push (list :release (%ct-resource-release-identity release)) *ct-log*))
  (values))
(defun %register-resource-auxiliary (construction identity object)
  (let* ((state (gethash identity (%context-resources construction)))
         (release (and state (%resource-state-release-capability state))))
    (unless (and release (not (%ct-resource-release-closed-p release)))
      (error 'construction-rejected :reason :test-manifest-closed))
    (pushnew object (%ct-resource-release-manifest release) :test #'eq)
    object))
(defun %close-resource-manifests (construction)
  (maphash
   (lambda (identity state)
     (declare (ignore identity))
     (let ((release (%resource-state-release-capability state)))
       (unless (%ct-resource-release-closed-p release)
         (setf (%ct-resource-release-closed-p release) t
               (%resource-state-auxiliary-bytes state)
               (max (%resource-state-auxiliary-bytes state)
                    (length (%ct-resource-release-manifest release)))))))
   (%context-resources construction))
  (values))

(defclass %ct-barrier ()
  ((actuals :initarg :actuals :reader %ct-barrier-actuals)
   (facts :initarg :facts :reader %ct-barrier-facts)
   (model :initarg :model :reader %ct-barrier-model)))
(defun make-composed-barrier (actuals facts model)
  (make-instance '%ct-barrier :actuals actuals :facts facts :model model))
(unless (fboundp 'configuration-barrier)
  (eval '(defgeneric configuration-barrier (configuration))))
(defmethod configuration-barrier ((configuration %configuration))
  (unless (%configuration-barrier-bound-p configuration)
    (error 'construction-rejected :reason :barrier-not-bound))
  (%configuration-barrier configuration))

(defvar *ct-drains* (make-hash-table :test #'eq))
(defun %close-configuration-runtime (configuration)
  (setf (gethash configuration *ct-drains*) 0)
  (push '(:runtime :closed) *ct-log*)
  (values))
(defun %drain-configuration-runtime (configuration)
  (if (zerop (gethash configuration *ct-drains*))
      (progn (setf (gethash configuration *ct-drains*) 1)
             (values :retained :test-active-call))
      (values :complete nil)))

(defun %ct-make-graph (&key fail-init-p cycle-without-cohort)
  (let* ((map (make-instance '%ct-component :name :map))
         (space (make-instance '%ct-space :name :space :map map
                               :requires-model-p t))
         (consumer (make-instance '%ct-component :name :consumer
                                  :requires-model-p t
                                  :fail-init-p fail-init-p))
         (plan (make-instance '%ct-component :name :plan))
         (coordinator (make-instance '%ct-component :name :coordinator))
         (address (make-instance '%ct-address))
         (clients (make-instance '%ct-clients :model (make-instance '%ct-model)
                                 :coordinator coordinator :address address)))
    (setf (%ct-dependencies space) (list map)
          (%ct-dependencies consumer) (list space)
          (%ct-dependencies plan) (list space consumer))
    (when cycle-without-cohort
      (setf (%ct-dependencies map) (list space)))
    (setf (%ct-placements space)
          (list (make-placement-request
                 space :space-range 64 96 128 :alignment 64 :granularity 32
                 :access '(:read :write) :lifetime :configuration
                 :mobility :fixed :reclaimability :collector)))
    (setf (%ct-placements plan)
          (list (make-placement-request
                 plan :after-range 32 32 32 :alignment 32 :granularity 32
                 :access '(:read) :lifetime :configuration
                 :mobility :fixed :reclaimability :collector))
          (%ct-constraints plan)
          (list (make-construction-constraint
                 plan :adjacent
                 '((:placement :space-range) (:placement :after-range))
                 :parameters 0 :description "space then auxiliary range")))
    (setf (%ct-resources plan)
          (list
           (make-resource-contribution
            plan :configuration-auxiliary :runtime-object-vector
            :minimum-physical-bytes 1 :logical-entry-bound 2048
            :auxiliary-bytes 1 :allocation-context :construction
            :exhaustion-action :reject-before-publication)
           (make-resource-contribution
            plan :queue :runtime-index-vector
            :minimum-physical-bytes 8 :logical-entry-bound 8
            :allocation-context :construction
            :exhaustion-action :reject-before-publication)))
    (let* ((claim (make-barrier-reservation-claim
                   plan '(:resource :queue) :runtime-index-vector 3))
           (events (list :store :cas)))
      (setf (%ct-barriers plan)
            (list (make-barrier-contribution
                   plan :remember events :reservation-claims (list claim)
                   :needs-old-p t :needs-new-p t
                   :replacement-policy :observe
                   :failure-policy :retry-before-exposure/fatal-after)))
      ;; Mutation after the builder snapshots is exercised by callers through
      ;; the barrier facts; the original list is intentionally not retained here.
      (values plan clients map space consumer coordinator address events))))

(defun %ct-log-position (entry)
  (position entry (reverse *ct-log*) :test #'equal))

(defun %ct-tree-conses (tree)
  (let ((seen (make-hash-table :test #'eq)) (result nil))
    (labels ((walk (value)
               (when (and (consp value) (not (gethash value seen)))
                 (setf (gethash value seen) t)
                 (push value result)
                 (walk (car value))
                 (walk (cdr value)))))
      (walk tree))
    result))

(defun %ct-check-builder-manifest (configuration)
  (let* ((construction (configuration-construction-context configuration))
         (state (gethash :configuration-auxiliary
                         (%context-resources construction)))
         (release (%resource-state-release-capability state))
         (manifest (%ct-resource-release-manifest release))
         (barrier (configuration-barrier configuration))
         (facts (%ct-barrier-facts barrier))
         (account (%configuration-capacity-account configuration))
         (entry (find :configuration-auxiliary account
                      :key #'%capacity-account-entry-identity :test #'eql)))
    (%ct-check (%ct-resource-release-closed-p release)
               "configuration manifest was not closed")
    (%ct-check (= (length manifest)
                  (length (remove-duplicates manifest :test #'eq)))
               "configuration manifest contains duplicate identities")
    (dolist (object (list configuration construction
                          (%configuration-graph configuration)
                          (%configuration-component-order configuration)
                          (%context-resources construction)
                          (%context-placements construction)
                          (%context-transaction-log construction)
                          (%configuration-capacity-account configuration)
                          barrier (%ct-barrier-actuals barrier) facts
                          (configuration-layout configuration)
                          (configuration-object-model configuration)))
      (%ct-check (member object manifest :test #'eq)
                 "retained builder object was not manifested: ~S" object))
    (dotimes (index (length facts))
      (let ((fact (aref facts index)))
        (dolist (cell (%ct-tree-conses fact))
          (%ct-check (member cell manifest :test #'eq)
                     "retained barrier fact cons was not manifested"))))
    (%ct-check (and entry
                    (= (%capacity-account-entry-auxiliary-bytes entry)
                       (%resource-state-auxiliary-bytes state))
                    (>= (%capacity-account-entry-auxiliary-bytes entry)
                        (length manifest)))
               "final capacity account did not snapshot measured manifest")
    t))

(defun %ct-test-success-and-shutdown ()
  (setf *ct-log* nil)
  (multiple-value-bind (plan clients map space consumer coordinator address events)
      (%ct-make-graph)
    (declare (ignore consumer coordinator))
    (let ((configuration (construct-plan plan clients)))
      (%ct-check (eq :published (%configuration-state configuration))
                 "configuration did not publish")
      (%ct-check (= 1 (%ct-declaration-count map))
                 "EQ-shared map discovered ~D times" (%ct-declaration-count map))
      (%ct-check (= 1 (%ct-map-description-count space))
                 "space authoritative map was described more than once")
      (%ct-check (typep (configuration-object-model configuration)
                        '%ct-bound-model)
                 "configuration lacks bound model")
      (%ct-check (typep (configuration-barrier configuration) '%ct-barrier)
                 "configuration lacks composed barrier")
      (%ct-check-builder-manifest configuration)
      (setf (car events) :bulk)
      (%ct-check (equal '(:store :cas)
                        (getf (aref (%ct-barrier-facts
                                    (configuration-barrier configuration)) 0)
                              :events))
                 "barrier facts observed later mutation")
      (%ct-check (< (%ct-log-position '(:initialize :map))
                    (%ct-log-position '(:bind :model))
                    (%ct-log-position '(:initialize :space)))
                 "object-model binding order is wrong: ~S" (reverse *ct-log*))
      (multiple-value-bind (base limit present-p)
          (construction-placement
           (configuration-construction-context configuration) :space-range)
        (%ct-check (and present-p (= base 4096) (= limit (+ base 96)))
                   "unexpected preferred placement ~S..~S" base limit))
      (multiple-value-bind (base limit present-p)
          (construction-placement
           (configuration-construction-context configuration) :after-range)
        (%ct-check (and present-p (= base (+ 4096 96)) (= limit (+ base 32)))
                   "adjacent hard constraint was violated ~S..~S" base limit))
      (multiple-value-bind (status reason)
          (shutdown-configuration configuration)
        (%ct-check (and (eq status :retained)
                        (eq reason :test-active-call)
                        (%ct-installed address))
                   "retained shutdown released state"))
      (multiple-value-bind (status reason)
          (shutdown-configuration configuration)
        (%ct-check (and (eq status :complete) (null reason)
                        (null (%ct-installed address)))
                   "shutdown did not complete"))
      (let ((ordered (reverse *ct-log*)))
        (%ct-check (< (position '(:release :queue) ordered :test #'equal)
                       (position '(:release :configuration-auxiliary)
                                 ordered :test #'equal)
                       (position '(:release :layout) ordered :test #'equal))
                   "release order is not exact reverse: ~S" ordered)))))

(defun %ct-test-failure-unwind ()
  (setf *ct-log* nil)
  (multiple-value-bind (plan clients map space consumer coordinator address events)
      (%ct-make-graph :fail-init-p t)
    (declare (ignore map space coordinator events))
    (%ct-check (eql :other-error
                    (%ct-reason (lambda () (construct-plan plan clients))))
               "initialization error was not reported")
    (%ct-check (member (list :deactivate (%ct-name consumer)) *ct-log*
                       :test #'equal)
               "partially initialized component was not deactivated")
    (%ct-check (null (%ct-installed address))
               "failed construction retained installed layout")
    (let ((ordered (reverse *ct-log*)))
      (%ct-check (< (position '(:release :queue) ordered :test #'equal)
                     (position '(:release :configuration-auxiliary)
                               ordered :test #'equal)
                     (position '(:release :layout) ordered :test #'equal))
                 "failure release order is wrong: ~S" ordered))))

(defun %ct-test-explicit-cycle-cohort ()
  (setf *ct-log* nil)
  (multiple-value-bind (plan clients map space consumer coordinator address events)
      (%ct-make-graph)
    (declare (ignore map space consumer coordinator address events))
    (let ((left (make-instance '%ct-component :name :cycle-left))
          (right (make-instance '%ct-component :name :cycle-right)))
      (setf (%ct-cohort left) :cycle
            (%ct-cohort right) :cycle
            (%ct-dependencies left) (list right)
            (%ct-dependencies right) (list left)
            (%ct-dependencies plan)
            (append (%ct-dependencies plan) (list left)))
      (let ((configuration (construct-plan plan clients)))
        (%ct-check (and (= 1 (%ct-declaration-count left))
                        (= 1 (%ct-declaration-count right)))
                   "cohort cycle was not EQ-discovered once")
        (%ct-check (< (%ct-log-position '(:initialize :cycle-left))
                      (%ct-log-position '(:initialize :cycle-right)))
                   "cohort initialization order was unstable")
        (shutdown-configuration configuration)
        (shutdown-configuration configuration)))))

(defun %ct-test-pre-effect-rejections ()
  (setf *ct-log* nil)
  (multiple-value-bind (plan clients map space consumer coordinator address events)
      (%ct-make-graph :cycle-without-cohort t)
    (declare (ignore map space consumer coordinator address events))
    (%ct-check (eql :dependency-cycle-without-cohort
                    (%ct-reason (lambda () (construct-plan plan clients))))
               "uncohorted cycle was accepted")
    (%ct-check (notany (lambda (entry) (eql (first entry) :acquire)) *ct-log*)
               "pre-effect rejection acquired resources"))
  (setf *ct-log* nil)
  (multiple-value-bind (plan clients map space consumer coordinator address events)
      (%ct-make-graph)
    (declare (ignore map space consumer coordinator address events))
    (defmethod construction-client-profile ((object (eql clients)))
      :unsupported-target)
    (%ct-check (eql :unsupported-construction-profile
                    (%ct-reason (lambda () (construct-plan plan clients))))
               "unsupported target profile was admitted")
    (%ct-check (null *ct-log*) "target rejection caused effects")))

(defun run-v14-construction-contracts ()
  (%ct-test-success-and-shutdown)
  (%ct-test-failure-unwind)
  (%ct-test-explicit-cycle-cohort)
  (%ct-test-pre-effect-rejections)
  (format t "~&v14 construction contracts: ~D checks passed~%" *ct-checks*)
  t)

(run-v14-construction-contracts)
