;;;; Metadata contract tests.  The ASDF test harness supplies package,
;;;; component/construction and client protocol files before this file.
(in-package #:clamsara)

(defclass metadata-test-model ()
  ((values :initform (make-hash-table :test #'equal))))
(defmethod describe-metadata-field-offer
    ((model metadata-test-model) field)
  (declare (ignore model))
  (values field 1 '(0 1) '(:read :write :cas) '(:relaxed)
          nil nil :preserve :preserve))
(defmethod field-read ((model metadata-test-model) field key)
  (gethash (list field key) (slot-value model 'values) 0))
(defmethod field-write ((model metadata-test-model) field key value)
  (setf (gethash (list field key) (slot-value model 'values)) value))
(defmethod field-cas ((model metadata-test-model) field key old new)
  (let ((observed (field-read model field key)))
    (if (eql observed old)
        (progn (field-write model field key new) (values observed t))
        (values observed nil))))


(defclass metadata-test-context ()
  ((resources :initform (make-hash-table :test #'eq))))
(defmethod construction-resource ((context metadata-test-context) identity)
  (destructuring-bind (handle physical logical auxiliary)
      (or (gethash identity (slot-value context 'resources))
          (list nil nil nil nil))
    (values handle (not (null handle)) physical logical auxiliary)))

(defmethod construction-placement ((context metadata-test-context) identity)
  (declare (ignore context identity))
  (values 4096 4160 t))

(defun metadata-test-context-for (storage)
  (let* ((context (make-instance 'metadata-test-context))
         (base (or (metadata-domain-base (metadata-domain storage)) 4096))
         (limit (or (metadata-domain-limit (metadata-domain storage)) 4160))
         (n (ceiling (- limit base)
                     (metadata-domain-granularity (metadata-domain storage))))
         (handle (cond ((typep storage 'packed-bit-storage)
                        (make-array n :element-type 'bit :initial-element 0))
                       (t (make-array n :initial-element
                                      (if (typep storage 'side-forwarding) nil 0))))))
    (setf (gethash storage (slot-value context 'resources))
          (list handle 4096 n 32))
    context))

(defun run-metadata-tests ()
  (let* ((domain (make-metadata-domain :base 4096 :limit 4160
                                       :granularity 16))
         (side (make-instance 'side-marks :domain domain))
         (scalar-side (make-instance 'scalar-side-marks :domain domain))
         (model (make-instance 'metadata-test-model))
         (inline (make-instance 'inline-marks :domain domain :model model
                                :field :marks))
         (side-context (metadata-test-context-for side))
         (scalar-context (metadata-test-context-for scalar-side))
         (inline-context (make-instance 'metadata-test-context)))
    (initialize-component side side-context)
    (initialize-component scalar-side scalar-context)
    (initialize-component inline inline-context)
    (assert (eq (metadata-domain side) domain))
    (assert (typep side 'range-metadata))
    (assert (typep scalar-side 'range-metadata))
    (assert (typep inline 'range-metadata))
    (assert (= (metadata-set-bit side 4112) 0))
    (assert (= (metadata-ref side 4112) 1))
    (assert (= (metadata-set-bit scalar-side 4112) 0))
    (assert (= (metadata-ref scalar-side 4112) 1))
    (assert (= (metadata-set-bit inline 4112) 0))
    (assert (= (metadata-ref inline 4112) 1))
    (metadata-transfer side 4112 side 4128)
    (metadata-transfer inline 4112 inline 4128)
    (assert (= (metadata-ref side 4128) 1))
    (assert (= (metadata-ref inline 4128) 1))
    (assert (= (metadata-fold side (cons 4096 4160)
                                  (lambda (value accumulator)
                                    (+ value accumulator)) 0)
               2))
    ;; Interior scalar keys are valid; interior bulk endpoints are not.
    (assert (= (metadata-ref side 4113) 1))
    (handler-case
        (progn (metadata-reset-range side (cons 4096 4113))
               (error "invalid range was accepted"))
      (metadata-key-error () nil))
    ;; Source and destination cells are preserved on a failed CAS.
    (multiple-value-bind (observed success)
        (metadata-cas side 4112 0 0)
      (assert (= observed 1))
      (assert (not success))
      (assert (= (metadata-ref side 4112) 1)))
    ;; Placement-derived geometry resolves before the resource handle.
    (let* ((placed-domain (make-metadata-domain
                           :placement-identity :space-placement
                           :granularity 16))
           (placed (make-instance 'side-marks :domain placed-domain)))
      (initialize-component placed (metadata-test-context-for placed))
      (assert (equal (multiple-value-list (metadata-bounds placed))
                     '(4096 4160 16))))
    ;; Two different storage objects can project; aliases cannot.
    (let ((destination (make-instance 'side-marks :domain domain)))
      (initialize-component destination (metadata-test-context-for destination))
      (metadata-project side destination (lambda (source-value destination-value)
                                          (logior source-value destination-value)))
      (assert (= (metadata-ref destination 4112) 1)))
    (let ((scalar (make-instance 'scalar-inline-marks :domain domain
                                 :model model :field :scalar)))
      (assert (not (typep scalar 'range-metadata))))
    (values t)))
