(require :asdf)
(asdf:initialize-source-registry '(:source-registry (:directory #p"/tmp/clamsara-opaque-integrated54-2nmikfx1/") :ignore-inherited-configuration))
(asdf:initialize-output-translations '(:output-translations (t ("/tmp/clamsara-opaque-integration-native-v31gi669/fasl/" :implementation)) :ignore-inherited-configuration))
(assert (equal (truename #p"/tmp/clamsara-opaque-integrated54-2nmikfx1/") (truename (asdf:system-source-directory :clamsara))))
;; Distinct source paths must not collide in the private FASL cache.
(let ((left (asdf:apply-output-translations #p"/one/package.fasl"))
      (right (asdf:apply-output-translations #p"/two/package.fasl")))
  (format t "~&PRIVATE-OUTPUT-PATHS ~S ~S~%" left right)
  (assert (not (equal left right))))
(asdf:test-system :clamsara)
(asdf:test-system :clamsara/tools/test)
(asdf:test-system :clamsara/workload/test)
(asdf:test-system :clamsara/generational/test)
(asdf:test-system :clamsara/quality/generational/test)
(asdf:load-system :clamsara/quality)
(clamsara.structure:assert-project-structure :include-optional-loaded t)
(format t "~&GENERATIONAL-CHECKPOINT-COMPONENTS-PASS~%")

(load #p"/tmp/clamsara-opaque-integrated54-2nmikfx1/docs/evidence/cas-boundaries-a3a0bae/independent-baseline/acceptance-03.lisp")
(load #p"/tmp/clamsara-opaque-integrated54-2nmikfx1/docs/evidence/cas-boundaries-a3a0bae/fixed-review/additional-05.lisp")
(load #p"/tmp/clamsara-opaque-integrated54-2nmikfx1/docs/evidence/cas-boundaries-a3a0bae/final-review/claims-transforms-03.lisp")
(uiop:symbol-call :clamsara.quality.barrier-history :run-barrier-history-tests)
(uiop:symbol-call :clamsara.quality.barrier-history :run-barrier-edge-tests)
(uiop:symbol-call :clamsara.quality.barrier-boundaries :run-barrier-boundary-tests)
(uiop:symbol-call :clamsara.quality.barrier-claims :run-barrier-claim-tests)
(format t "~&CAS-INTEGRATED-184-REPEAT-INDEPENDENT-176-PASS~%")

(format t "~&OPAQUE-INTEGRATED-COMPONENTS-CAS-PASS root=~A~%" (asdf:system-source-directory :clamsara))

(load #p"/tmp/clamsara-cas-staged-yik9o9qk/independent-review/opaque-admission/acceptance-source-02.lisp")
(load #p"/tmp/clamsara-opaque-draft-8qjnkk81/independent-review/opaque-admission/additional-source-02.lisp")
(uiop:symbol-call :clamsara.independent.opaque-admission :run-opaque-admission-tests)
(uiop:symbol-call :clamsara.independent.opaque-edges :run-opaque-admission-edge-tests)
(uiop:symbol-call :clamsara.quality.barrier-admission :run-opaque-admission-tests)
(uiop:symbol-call :clamsara.quality.barrier-admission-edges :run-opaque-admission-edge-tests)
(format t "~&OPAQUE-INTEGRATED-54-ARCHIVED-54-REPEAT-PASS~%")
