;;;; src/host/atomics.lisp -- serialized hosted atomic capability.
(in-package #:clamsara)

(defstruct (host-atomic-place (:constructor make-host-atomic-place
                               (&key storage index width alignment)))
  storage index width alignment)
(defclass host-atomics ()
  ((word-width :initarg :word-width :initform 64 :reader host-atomics-word-width)
   (profile :initarg :profile :initform :sequential-host :reader host-atomics-profile)))
(defun make-host-atomics (&key (word-width 64) (profile :sequential-host))
  (unless (and (member profile '(:sequential-host :sequential) :test #'eq)
               (member word-width '(8 16 32 64) :test #'=))
    (error "Hosted atomics only support sequential 8/16/32/64-bit words"))
  (make-instance 'host-atomics :word-width word-width :profile profile))

(defun %atomic-order (order operation)
  (let ((valid (case operation
                 (:load '(:relaxed :acquire :sequential))
                 (:store '(:relaxed :release :sequential))
                 (:rmw '(:relaxed :acquire :release :acq-rel :sequential))
                 (:fence '(:acquire :release :acq-rel :sequential)))))
    (unless (member order valid :test #'eq)
      (error "Order ~S is invalid for ~S" order operation))) order)
(defun %atomic-place (atomics place)
  (unless (typep atomics 'host-atomics) (error "Foreign atomic capability"))
  (unless (eq (host-atomics-profile atomics) :sequential-host)
    (error "Unsupported hosted atomic profile"))
  (unless (typep place 'host-atomic-place) (error "Foreign atomic place"))
  (let ((storage (host-atomic-place-storage place))
        (index (host-atomic-place-index place))
        (width (host-atomic-place-width place))
        (alignment (host-atomic-place-alignment place)))
    (unless (and (arrayp storage) (integerp index) (<= 0 index) (< index (array-total-size storage))
                 (member width '(8 16 32 64) :test #'=)
                 (<= width (host-atomics-word-width atomics))
                 (integerp alignment) (plusp alignment) (zerop (mod alignment (ceiling width 8))))
      (error "Invalid atomic place width/alignment/index")))
  place)
(defun %word (p)
  (let ((x (row-major-aref (host-atomic-place-storage p) (host-atomic-place-index p))))
    (unless (integerp x) (error "Atomic place does not contain an integer word"))
    (mod x (ash 1 (host-atomic-place-width p)))))
(defun (setf %word) (x p)
  (setf (row-major-aref (host-atomic-place-storage p) (host-atomic-place-index p))
        (mod x (ash 1 (host-atomic-place-width p)))))

(defmethod atomic-load ((atomics host-atomics) place order)
  (%atomic-order order :load) (%word (%atomic-place atomics place)))
(defmethod atomic-store ((atomics host-atomics) place value order)
  (%atomic-order order :store)
  (unless (integerp value) (error "Atomic store value must be an integer"))
  (let ((p (%atomic-place atomics place)))
    (setf (%word p) value)
    (%word p)))
(defmethod atomic-cas ((atomics host-atomics) place old new order)
  (%atomic-order order :rmw)
  (unless (and (integerp old) (integerp new)) (error "CAS words must be integers"))
  (let* ((p (%atomic-place atomics place)) (seen (%word p)))
    (when (= seen (mod old (ash 1 (host-atomic-place-width p)))) (setf (%word p) new))
    seen))
(defmethod atomic-fetch-add ((atomics host-atomics) place delta order)
  (%atomic-order order :rmw)
  (unless (integerp delta) (error "Fetch-add delta must be an integer"))
  (let* ((p (%atomic-place atomics place)) (seen (%word p))) (setf (%word p) (+ seen delta)) seen))
(defmethod atomic-bit-set ((atomics host-atomics) place index order)
  (%atomic-order order :rmw)
  (unless (and (integerp index) (<= 0 index)) (error "Bit index out of range"))
  (let ((p (%atomic-place atomics place)))
    (unless (< index (host-atomic-place-width p)) (error "Bit index out of range"))
    (let* ((word (%word p)) (mask (ash 1 index)))
      (setf (%word p) (logior word mask)) (not (zerop (logand word mask))))))
(defmethod atomic-bit-clear ((atomics host-atomics) place index order)
  (%atomic-order order :rmw)
  (unless (and (integerp index) (<= 0 index)) (error "Bit index out of range"))
  (let ((p (%atomic-place atomics place)))
    (unless (< index (host-atomic-place-width p)) (error "Bit index out of range"))
    (let* ((word (%word p)) (mask (ash 1 index)))
      (setf (%word p) (logandc2 word mask))
      (not (zerop (logand word mask))))))
(defmethod fence ((atomics host-atomics) order)
  (%atomic-order order :fence) nil)
