;;;; Bounded serialized simulator coordination; no native scheduler claim.
(in-package #:clamsara)

(defclass coordinator (component) ())
(defvar *simulator-next-stop-identity* 1)
(defclass simulator-coordinator (coordinator)
  ((roots :initarg :roots :reader simulator-coordinator-roots)
   (coverage :initarg :coverage :reader simulator-coordinator-coverage)
   (base :initarg :base :reader simulator-stop-base)
   (next :initform 0 :accessor simulator-stop-next)
   (await-bound :initarg :await-bound :reader simulator-await-bound)
   (joined :initarg :joined :reader simulator-joined-providers)
   (wake-counts :initarg :wake-counts :reader simulator-wake-counts)
   (current :initform nil :accessor simulator-current-stop)
   (state :initform :idle :accessor simulator-stop-state)
   (retired-p :initform nil :accessor simulator-coordinator-retired-p)
   (configuration :initform nil :accessor simulator-coordinator-configuration)
   ;; Deterministic injected host failure before/after any partial join.
   (fail-after :initform nil :accessor simulator-await-fail-after)
   (last-await-steps :initform 0 :accessor simulator-last-await-steps)))

(defun make-simulator-coordinator (roots &key (stop-capacity 16384) await-bound)
  (unless (and (typep roots 'simulator-root-client)
               (typep stop-capacity '(integer 1 #.most-positive-fixnum)))
    (host-reject :invalid-coordinator-capacity))
  (let* ((provider-capacity (length (simulator-root-providers roots)))
         (bound (or await-bound (1+ provider-capacity)))
         (base *simulator-next-stop-identity*))
    (unless (and (typep bound '(integer 1 #.most-positive-fixnum))
                 (<= stop-capacity (- most-positive-fixnum base)))
      (host-reject :invalid-coordinator-bound))
    (let* ((coverage (make-array stop-capacity))
           (coordinator (make-instance 'simulator-coordinator :roots roots
                         :coverage coverage :base base :await-bound bound
                         :joined (make-array provider-capacity :element-type 'bit
                                             :initial-element 0)
                         :wake-counts (make-array provider-capacity :initial-element 0))))
      (dotimes (i stop-capacity)
        (setf (aref coverage i)
              (%make-simulator-coverage :coordinator coordinator
                                       :token (+ base i) :roots roots)))
      ;; Reserve nonoverlapping token identities at ordinary construction.
      (incf *simulator-next-stop-identity* stop-capacity)
      coordinator)))

(defun %simulator-current-coverage (coordinator)
  (aref (simulator-coordinator-coverage coordinator)
        (- (simulator-current-stop coordinator) (simulator-stop-base coordinator))))
(defun %simulator-stop-admitted-p (coordinator)
  (and (not (simulator-coordinator-retired-p coordinator))
       (let ((configuration (simulator-coordinator-configuration coordinator)))
         (or (null configuration) (eq :published (%configuration-state configuration))))))

(defmethod request-safepoint ((coordinator simulator-coordinator) scope reason)
  (unless (eq scope :all)
    (return-from request-safepoint (values nil :unsupported-scope)))
  (unless (and reason (symbolp reason))
    (return-from request-safepoint (values nil :invalid-reason)))
  (unless (%simulator-stop-admitted-p coordinator)
    (return-from request-safepoint (values nil :configuration-closed)))
  (when (member (simulator-stop-state coordinator) '(:pending :covered :coverage-failed))
    (return-from request-safepoint (values nil :busy)))
  (when (= (simulator-stop-next coordinator)
           (length (simulator-coordinator-coverage coordinator)))
    (return-from request-safepoint (values nil :insufficient-reserve)))
  (let ((roots (simulator-coordinator-roots coordinator)))
    (when (or (simulator-root-admission-closed-p roots)
              (simulator-root-snapshot-active-p (simulator-client-snapshot roots)))
      (return-from request-safepoint (values nil :busy)))
    (let ((token (+ (simulator-stop-base coordinator) (simulator-stop-next coordinator))))
      (incf (simulator-stop-next coordinator))
      (setf (simulator-current-stop coordinator) token
            (simulator-stop-state coordinator) :pending
            (simulator-root-admission-closed-p roots) t
            (simulator-last-await-steps coordinator) 0)
      (fill (simulator-joined-providers coordinator) 0)
      (setf (simulator-coverage-root-generation (%simulator-current-coverage coordinator))
            (simulator-root-generation roots))
      (values token nil))))

(defmethod await-safepoint ((coordinator simulator-coordinator) token)
  (unless (and (eql token (simulator-current-stop coordinator))
               (eq :pending (simulator-stop-state coordinator))
               (not (simulator-coordinator-retired-p coordinator)))
    (host-reject :invalid-await-token))
  (let* ((roots (simulator-coordinator-roots coordinator))
         (providers (simulator-root-providers roots))
         (joined (simulator-joined-providers coordinator))
         (count 0) (steps 0)
         (fail-after (simulator-await-fail-after coordinator))
         (coverage (%simulator-current-coverage coordinator)))
    (block attempt
      ;; One final step is reserved for completion/failure publication.
      (dotimes (i (length providers))
        (when (or (>= steps (1- (simulator-await-bound coordinator)))
                  (and fail-after (>= count fail-after)))
          (return-from attempt nil))
        (incf steps)
        (when (aref providers i)
          ;; Serialized execution has no concurrent writer; this is an
          ;; explicit provider acknowledgement, not a native thread save.
          (setf (sbit joined i) 1)
          (incf count)))
      (when (and fail-after (>= count fail-after)) (return-from attempt nil))
      (when (/= (simulator-coverage-root-generation coverage)
                (simulator-root-generation roots))
        (return-from attempt nil))
      (setf (simulator-coverage-protected-p coverage) t
            (simulator-stop-state coordinator) :covered))
    (setf (simulator-last-await-steps coordinator) (1+ steps))
    (if (eq :covered (simulator-stop-state coordinator))
        (values token coverage nil)
        (progn
          (setf (simulator-stop-state coordinator) :coverage-failed)
          (values token nil :coverage-failed)))))

(defmethod release-safepoint ((coordinator simulator-coordinator) token)
  ;; The retained finite reserve identifies every admitted token, including
  ;; exact repeats older than the current stop. No token identity is reused.
  (unless (and (typep token 'fixnum)
               (<= (simulator-stop-base coordinator) token)
               (< token (+ (simulator-stop-base coordinator)
                           (simulator-stop-next coordinator))))
    (return-from release-safepoint :invalid))
  (let ((coverage (aref (simulator-coordinator-coverage coordinator)
                        (- token (simulator-stop-base coordinator)))))
    (when (simulator-coverage-terminal-result coverage)
      (return-from release-safepoint :already-released)))
  (when (or (simulator-coordinator-retired-p coordinator)
            (not (eql token (simulator-current-stop coordinator))))
    (return-from release-safepoint :invalid))
  (case (simulator-stop-state coordinator)
    ((:released :cancelled) (return-from release-safepoint :already-released))
    ((:covered :coverage-failed))
    (otherwise (return-from release-safepoint :invalid)))
  (let* ((coverage (%simulator-current-coverage coordinator))
         (failed (eq :coverage-failed (simulator-stop-state coordinator)))
         (joined (simulator-joined-providers coordinator))
         (wake-counts (simulator-wake-counts coordinator)))
    (when (or (plusp (simulator-coverage-borrowers coverage))
              (simulator-coverage-correction-failed-p coverage))
      (return-from release-safepoint :invalid))
    (setf (simulator-coverage-protected-p coverage) nil)
    (dotimes (i (length joined))
      (when (= 1 (sbit joined i))
        (setf (sbit joined i) 0)
        (incf (aref wake-counts i))))
    (setf (simulator-root-admission-closed-p (simulator-coordinator-roots coordinator)) nil
          (simulator-stop-state coordinator) (if failed :cancelled :released)
          (simulator-coverage-terminal-result coverage) (if failed :cancelled :released))
    (if failed :cancelled :released)))

(defmethod initialize-component :after ((coordinator simulator-coordinator) context)
  (setf (simulator-coordinator-configuration coordinator) (construction-configuration context)))
(defmethod validate-component :after ((coordinator simulator-coordinator) configuration)
  (unless (and (eq (construction-client-profile (configuration-clients configuration))
                   :sequential-host)
               (plusp (simulator-await-bound coordinator))
               (not (simulator-coordinator-retired-p coordinator))
               (eq (simulator-coordinator-roots coordinator)
                   (construction-root-client (configuration-clients configuration))))
    (error 'construction-rejected :reason :unsupported-coordinator-profile)))
(defmethod deactivate-component :before ((coordinator simulator-coordinator) context)
  (declare (ignore context))
  (when (member (simulator-stop-state coordinator) '(:pending :covered :coverage-failed))
    (host-reject :coordinator-stop-retained))
  (setf (simulator-coordinator-retired-p coordinator) t))

(defclass simulator-diagnostics ()
  ((reason :initform nil :accessor simulator-fatal-reason)
   (escape :initarg :escape :reader simulator-fatal-escape)))
(defun make-simulator-diagnostics (&key (escape 'simulator-fatal))
  (make-instance 'simulator-diagnostics :escape escape))
(defmethod monotonic-clock ((diagnostics simulator-diagnostics))
  (declare (ignore diagnostics)) (get-internal-real-time))
(defmethod fatal-diagnostic ((diagnostics simulator-diagnostics) reason)
  (setf (simulator-fatal-reason diagnostics) reason)
  (throw (simulator-fatal-escape diagnostics) reason))

;;; ------------------------------------------------------------------
;;; One root pass over the actual stop and root operations (threst.tex).
;;; There is no unconditional unwind release: failed Await has no coverage
;;; and takes explicit cancellation, while callback failure after partial
;;; correction retains the stop and enters closed failure.

(defun stopped-root-pass (coordinator root-client diagnostics function)
  (multiple-value-bind (token request-failure)
      (request-safepoint coordinator :all :collection)
    (if request-failure
        (values nil request-failure)
        (multiple-value-bind (same-token coverage await-failure)
            (await-safepoint coordinator token)
          (declare (ignore same-token))
          (if await-failure
              (progn
                (unless (eq :cancelled (release-safepoint coordinator token))
                  (fatal-diagnostic diagnostics :safepoint-cancel-invariant))
                (values nil await-failure))
              (progn
                (with-root-snapshot root-client coverage function)
                (unless (eq :released (release-safepoint coordinator token))
                  (fatal-diagnostic diagnostics :safepoint-release-invariant))
                (values t nil)))))))
