;;;; src/host/object-model.lisp -- bounded serialized simulator object ABI
(in-package #:clamsara)

(defstruct (host-slot-description (:constructor make-host-slot-description (&key identity offset))) identity offset)
(defstruct (host-ephemeron-location-description (:constructor make-host-ephemeron-location-description (&key identity key-offset value-offset))) identity key-offset value-offset)
(defstruct (host-object-kind-description (:constructor %host-kind (name size-rule alignment-rule strong-layout weak-descriptions ephemeron-descriptions index))) name size-rule alignment-rule strong-layout weak-descriptions ephemeron-descriptions index)
(defstruct (host-weak-location-description (:constructor %host-weak (identity referent-kind cleared-value offset))) identity referent-kind cleared-value offset)
(defstruct (host-ephemeron-description (:constructor %host-eph (identity clear-key-p cleared-key cleared-value key-offset value-offset))) identity clear-key-p cleared-key cleared-value key-offset value-offset)

;;; Host references are immutable by protocol discipline and are all allocated
;;; at binding.  A Lisp INTEGER is never a managed reference.
(defstruct (host-reference (:constructor %host-ref (model descriptor generation address kind tag displacement))) model descriptor generation address kind tag displacement)
(defstruct (host-route (:constructor %host-route (parent space map base limit q count descriptors bases generation arena-offset))) parent space map base limit q count descriptors bases generation arena-offset)
(defstruct (host-descriptor (:constructor %host-desc)) start size alignment kind descriptor generation route cell active)
(defstruct (host-location (:constructor %host-location)) model descriptor generation word-index identity strength active stage)
(defstruct (host-handle (:constructor %host-handle)) model active descriptor generation identity strength index stage)
(defstruct (host-variant (:constructor %host-variant)) active reference descriptor generation kind tag displacement)
(defstruct (host-stage (:constructor %host-stage)) model active generation source destination size alignment kind descriptor bytes words descriptor-id)
(defstruct (host-binding (:constructor %host-binding (space map base limit q generation))) space map base limit q generation)

(defclass host-object-model ()
  ((profile :initarg :profile :initform :sequential-host :reader host-model-profile)
   (capacity :initarg :capacity :reader host-model-capacity)
   (max-object-bytes :initarg :max-object-bytes :reader host-model-max-object-bytes)
   (variant-capacity :initarg :variant-capacity :reader host-model-variant-capacity)
   (location-capacity :initarg :location-capacity :reader host-model-location-capacity)
   (handle-capacity :initarg :handle-capacity :reader host-model-handle-capacity)
   (stage-capacity :initarg :stage-capacity :reader host-model-stage-capacity)
   (max-displacement :initarg :max-displacement :reader host-model-max-displacement)
   (tag-capacity :initarg :tag-capacity :reader host-model-tag-capacity)
   (kind-capacity :initarg :kind-capacity :reader host-model-kind-capacity)
   (slot-capacity :initarg :slot-capacity :reader host-model-slot-capacity)
   (kinds :initarg :kinds :reader host-model-kinds) (kind-count :initform 0 :accessor host-model-kind-count)
   (layout :initarg :layout :initform nil :accessor host-model-layout)
   (bindings :initarg :bindings :initform #() :accessor host-model-bindings)
   (routes :initarg :routes :initform #() :accessor host-model-routes)
   (arena :initarg :arena :initform nil :accessor host-model-arena)
   (words :initarg :words :initform nil :accessor host-model-words)
   (descriptors :initarg :descriptors :initform nil :accessor host-model-descriptors)
   (variants :initarg :variants :initform nil :accessor host-model-variants)
   (handles :initarg :handles :initform nil :accessor host-model-handles)
   (locations :initarg :locations :initform nil :accessor host-model-locations)
   (stages :initarg :stages :initform nil :accessor host-model-stages)
   (next-descriptor :initform 0 :accessor host-model-next-descriptor)
   (next-variant :initform 0 :accessor host-model-next-variant)
   (bound-p :initarg :bound-p :initform nil :reader host-model-bound-p)))
(defclass host-bound-object-model (host-object-model) ())

(defun make-host-object-model (&key (capacity 65536) (max-object-bytes 65536)
  (variant-capacity 1024) (location-capacity 8) (handle-capacity 1024)
  (stage-capacity 4) (max-displacement 64) (tag-capacity 8)
  (kind-capacity 64) (slot-capacity 64) (profile :sequential-host))
  (unless (member profile '(:sequential-host :sequential) :test #'eq) (error "Unsupported profile"))
  (unless (every (lambda (x) (and (integerp x) (plusp x)))
                (list capacity max-object-bytes variant-capacity location-capacity handle-capacity
                      stage-capacity (1+ max-displacement) (1+ tag-capacity) kind-capacity slot-capacity))
    (error "Invalid model capacity"))
  (make-instance 'host-object-model :profile profile :capacity capacity
    :max-object-bytes max-object-bytes :variant-capacity variant-capacity
    :location-capacity location-capacity :handle-capacity handle-capacity
    :stage-capacity stage-capacity :max-displacement max-displacement
    :tag-capacity tag-capacity :kind-capacity kind-capacity :slot-capacity slot-capacity
    :kinds (make-array kind-capacity)))
(defun %hm (m) (unless (typep m 'host-object-model) (error "Foreign host model")) m)
(defun %bm (m) (%hm m) (unless (host-model-bound-p m) (error "Model is not bound")) m)
(defun %copyv (v) (let ((x (make-array (length v)))) (replace x v) x))
(defun %rulev (r arg label) (let ((x (if (functionp r) (funcall r arg) r))) (unless (and (integerp x) (plusp x)) (error "Invalid ~A" label)) x))
(defun %p2 (n) (and (integerp n) (plusp n) (zerop (logand n (1- n)))))
(defun %slot (x default)
  (cond ((typep x 'host-slot-description) (values (host-slot-description-identity x) (host-slot-description-offset x)))
        ((and (consp x) (keywordp (car x))) (values (getf x :identity x) (getf x :offset default)))
        ((integerp x) (values x x)) (t (values x default))))
(defun %kind (m x) (or (and (typep x 'host-object-kind-description) x)
  (loop for i below (host-model-kind-count m) for k = (aref (host-model-kinds m) i)
        when (equal x (host-object-kind-description-name k)) do (return k))))
(defun %kind! (m x) (or (%kind m x) (error "Unknown kind ~S" x)))

(defmethod make-object-kind-description ((m host-object-model) name &key size-rule alignment-rule strong-layout weak-descriptions ephemeron-descriptions)
  (%hm m)
  (when (or (null name) (%kind m name)) (error "Duplicate/empty object kind"))
  (let ((s (coerce (or strong-layout '()) 'vector)) (w (coerce (or weak-descriptions '()) 'vector)) (e (coerce (or ephemeron-descriptions '()) 'vector)))
    (when (> (+ (length s) (length w) (* 2 (length e))) (host-model-slot-capacity m)) (error "Kind slot bound exceeded"))
    (loop for i below (length s) do (multiple-value-bind (id off) (%slot (aref s i) (* i 8))
      (unless (and id (integerp off) (<= 0 off) (zerop (mod off 8))) (error "Invalid strong slot"))))
    (when (>= (host-model-kind-count m) (host-model-kind-capacity m)) (error "Kind capacity exhausted"))
    (let ((d (%host-kind name size-rule alignment-rule (%copyv s) (%copyv w) (%copyv e) (host-model-kind-count m))))
      (setf (aref (host-model-kinds m) (host-model-kind-count m)) d) (incf (host-model-kind-count m)) d)))
(defmethod describe-object-kind ((m host-object-model) d)
  (%hm m) (unless (typep d 'host-object-kind-description) (error "Foreign kind"))
  (values (host-object-kind-description-name d) (host-object-kind-description-size-rule d)
          (host-object-kind-description-alignment-rule d) (host-object-kind-description-strong-layout d)
          (host-object-kind-description-weak-descriptions d) (host-object-kind-description-ephemeron-descriptions d)))
(defmethod make-weak-location-description ((m host-object-model) identity referent-kind cleared-value)
  (%hm m) (when (valid-reference-p m cleared-value) (error "Weak clear value is a reference"))
  (multiple-value-bind (id off) (%slot identity 0) (%host-weak id referent-kind cleared-value off)))
(defmethod describe-weak-location ((m host-object-model) d)
  (%hm m) (unless (typep d 'host-weak-location-description) (error "Foreign weak descriptor"))
  (values (host-weak-location-description-identity d) (host-weak-location-description-referent-kind d) (host-weak-location-description-cleared-value d)))
(defmethod make-ephemeron-description ((m host-object-model) identity clear-key-p cleared-key cleared-value)
  (%hm m) (when (or (valid-reference-p m cleared-key) (valid-reference-p m cleared-value)) (error "Ephemeron clear value is a reference"))
  (if (typep identity 'host-ephemeron-location-description)
      (%host-eph (host-ephemeron-location-description-identity identity) (not (null clear-key-p)) cleared-key cleared-value
                 (host-ephemeron-location-description-key-offset identity) (host-ephemeron-location-description-value-offset identity))
      (%host-eph identity (not (null clear-key-p)) cleared-key cleared-value 0 8)))
(defmethod describe-ephemeron ((m host-object-model) d)
  (%hm m) (unless (typep d 'host-ephemeron-description) (error "Foreign ephemeron"))
  (values (host-ephemeron-description-identity d) (host-ephemeron-description-clear-key-p d)
          (host-ephemeron-description-cleared-key d) (host-ephemeron-description-cleared-value d)))

;;; Parent construction owns the installed-layout class/range records.
(defun %fn (name) (let ((s (find-symbol name :clamsara))) (and s (fboundp s) (symbol-function s))))
(defun %rf (r suffix) (let ((f (%fn (format nil "%SIMULATOR-LAYOUT-RANGE-~A" suffix)))) (unless f (error "Missing layout range accessor")) (funcall f r)))
(defun %ranges (layout) (let ((f (%fn "SIMULATOR-LAYOUT-RANGES"))) (unless f (error "Missing installed-layout ranges")) (coerce (funcall f layout) 'vector)))
(defun %map-bounds (map) (multiple-value-bind (b l q) (metadata-bounds map) (values b l q)))
(defmethod make-object-start-binding ((m host-object-model) space metadata)
  (%hm m) (multiple-value-bind (b l q) (%map-bounds metadata)
    (unless (and (integerp b) (integerp l) (<= b l) (plusp q)) (error "Invalid object-start map geometry"))
    (%host-binding space metadata b l q 0)))
(defmethod describe-object-start-binding ((m host-object-model) b)
  (%hm m) (unless (typep b 'host-binding) (error "Foreign binding")) (values (host-binding-space b) (host-binding-map b)))
(defun %route-for-binding (ranges b)
  (loop for r across ranges when (and (eq (host-binding-space b) (%rf r "SPACE")) (eq (host-binding-map b) (%rf r "MAP"))) do (return r)))

(defmethod bind-object-model ((m host-object-model) layout object-start-bindings)
  (%hm m)
  (let ((ic (find-class 'simulator-installed-layout nil))) (unless (and ic (typep layout ic)) (error "Not installed layout")))
  (let* ((rr (%ranges layout)) (bs (coerce object-start-bindings 'vector)))
    (unless (= (length rr) (length bs)) (error "Binding coverage mismatch"))
    (loop for b across bs unless (%route-for-binding rr b) do (error "Foreign binding"))
    (let* ((total (loop for r across rr sum (- (%rf r "LIMIT") (%rf r "BASE"))))
           (arena (make-array total :element-type '(unsigned-byte 8) :initial-element 0))
           (words (make-array (ceiling total 8) :initial-element nil))
           (descs (make-array (loop for z across rr sum (ceiling (- (%rf z "LIMIT") (%rf z "BASE")) (nth-value 2 (%map-bounds (%rf z "MAP")))))))
           (variants (make-array (host-model-variant-capacity m)))
           (handles (make-array (host-model-handle-capacity m)))
           (locs (make-array (host-model-location-capacity m)))
           (stages (make-array (host-model-stage-capacity m)))
           (bound (make-instance 'host-bound-object-model :profile (host-model-profile m)
             :capacity (host-model-capacity m) :max-object-bytes (host-model-max-object-bytes m)
             :variant-capacity (host-model-variant-capacity m) :location-capacity (host-model-location-capacity m)
             :handle-capacity (host-model-handle-capacity m) :stage-capacity (host-model-stage-capacity m)
             :max-displacement (host-model-max-displacement m) :tag-capacity (host-model-tag-capacity m)
             :kind-capacity (host-model-kind-capacity m) :slot-capacity (host-model-slot-capacity m)
             :kinds (host-model-kinds m) :layout layout :bindings bs :arena arena :words words
             :descriptors descs :variants variants :handles handles :locations locs :stages stages :bound-p t)))
      (dotimes (i (length descs)) (setf (aref descs i) (%host-desc)))
      (dotimes (i (length variants)) (setf (aref variants i) (%host-variant)))
      (dotimes (i (length handles)) (setf (aref handles i) (%host-handle)))
      (dotimes (i (length locs)) (setf (aref locs i) (%host-location :model bound)))
      (dotimes (i (length stages))
        (let ((s (%host-stage :model bound :bytes (make-array (host-model-max-object-bytes bound) :element-type '(unsigned-byte 8) :initial-element 0)
                              :words (make-array (ceiling (host-model-max-object-bytes bound) 8) :initial-element nil))))
          (setf (aref stages i) s)))
      (let ((routes (make-array (length rr))) (base-off 0))
        (loop with arena-off = 0 for i below (length rr) for parent = (aref rr i)
              for b = (%rf parent "BASE") for l = (%rf parent "LIMIT")
              for q = (multiple-value-bind (mb ml mq) (%map-bounds (%rf parent "MAP")) (declare (ignore mb ml)) mq)
              for n = (ceiling (- l b) q) for dvec = (make-array n)
              for bases = (make-array n)
              do (dotimes (c n)
                   (setf (aref dvec c) (aref descs base-off)
                         (aref bases c) (%host-ref bound base-off 0 (+ b (* c q)) :base nil 0)
                         base-off (1+ base-off)))
                 (setf (aref routes i)
                       (%host-route parent (%rf parent "SPACE") (%rf parent "MAP") b l q n dvec bases (%rf parent "GENERATION") arena-off))
                 (incf arena-off (- l b))))
        (setf (host-model-routes bound) routes))
      bound)))

(defun %route-at (m address)
  (loop for route across (host-model-routes m) when (and (<= (host-route-base route) address) (< address (host-route-limit route))) do (return route)))
(defun %route-live (m route)
  (let ((rs (%ranges (host-model-layout m))))
    (loop for r across rs when (and (= (%rf r "BASE") (host-route-base route)) (= (%rf r "LIMIT") (host-route-limit route))) do
      (setf (host-route-space route) (%rf r "SPACE") (host-route-map route) (%rf r "MAP") (host-route-generation route) (%rf r "GENERATION")) (return route))))
(defun %binding-at (m address)
  (let ((r (%route-live m (%route-at m address))))
    (and r (loop for b across (host-model-bindings m) when (and (eq (host-binding-space b) (host-route-space r)) (eq (host-binding-map b) (host-route-map r))) do (return b)))))
(defun %map-canonical (m b address)
  (multiple-value-bind (base limit q) (%map-bounds (host-binding-map b))
    (declare (ignore limit))
    (loop for x from (+ base (* (floor (- address base) q) q)) downto base by q
          when (let ((v (metadata-ref (host-binding-map b) x))) (or (eql v 1) (eql v t) (eql v x))) do (return x))))
(defun %cell (route address) (floor (- address (host-route-base route)) (host-route-q route)))
(defun %desc-at (m address)
  (let* ((r (%route-at m address)) (i (and r (%cell r address)))) (and r i (aref (host-route-descriptors r) i))))
(defun %word-index (m address)
  (let ((r (%route-at m address)))
    (unless r (error "Address outside installed arena"))
    (floor (+ (host-route-arena-offset r)
              (- address (host-route-base r))) 8)))
(defun simulator-reference-address (ref) (and (typep ref 'host-reference) (host-reference-address ref)))
(defun %simulator-model-layout (m) (and (typep m 'host-bound-object-model) (host-model-layout m)))

(defmethod valid-reference-p ((m host-object-model) v) (and (typep v 'host-reference) (eq m (host-reference-model v))))
(defun %ref-address (m v) (unless (valid-reference-p m v) (error "Immediate/foreign reference")) (host-reference-address v))
(defun %direct-descriptor (m ref)
  (let ((d (and (valid-reference-p m ref) (host-reference-descriptor ref))))
    (and d (< d (length (host-model-descriptors m))) (aref (host-model-descriptors m) d))))
(defmethod normalize-reference ((m host-object-model) ref)
  (%bm m) (let* ((a (%ref-address m ref)) (b (%binding-at m a)) (s (and b (%map-canonical m b a)))
                       (d (and s (%direct-descriptor m (%base-ref-at m s)))))
    (unless (and d (host-descriptor-active d) (= (host-descriptor-start d) s)
                 (< a (+ s (host-descriptor-size d)))) (error "Stale/non-object reference"))
    (values (%base-ref-at m s)
            (case (host-reference-kind ref)
              (:base 0) (:interior (+ #x10000000 (- a s)))
              (:tagged-base (+ #x20000000 (host-reference-tag ref)))
              (:tagged-interior (+ #x30000000 (ash (host-reference-tag ref) 20) (- a s)))))))
(defun %base-ref-at (m address)
  (let* ((r (%route-at m address)) (i (and r (zerop (mod (- address (host-route-base r)) (host-route-q r))) (%cell r address))))
    (and r i (aref (host-route-bases r) i))))
(defun %descriptor-code (d)
  (cond ((eql d 0) (values :base 0 0)) ((and (<= #x10000000 d) (< d #x20000000)) (values :interior 0 (- d #x10000000)))
        ((and (<= #x20000000 d) (< d #x30000000)) (values :tagged-base (logand d #xffff) 0))
        ((and (<= #x30000000 d) (< d #x40000000)) (let ((x (- d #x30000000))) (values :tagged-interior (ldb (byte 12 20) x) (logand x (1- (ash 1 20))))))
        (t (error "Malformed descriptor"))))
(defun %variant-find (m descriptor generation kind tag disp)
  (loop for v across (host-model-variants m) when (and (host-variant-active v) (= descriptor (host-variant-descriptor v)) (= generation (host-variant-generation v)) (eq kind (host-variant-kind v)) (= tag (host-variant-tag v)) (= disp (host-variant-displacement v))) do (return (host-variant-reference v))))
(defmethod rebuild-reference ((m host-object-model) new-start descriptor)
  (%bm m) (unless (valid-reference-p m new-start) (error "Foreign destination"))
  (let ((base (%base-ref-at m (host-reference-address new-start))))
    (unless base (error "Destination is not an admitted base encoding"))
    (multiple-value-bind (kind tag disp) (%descriptor-code descriptor)
      (if (eq kind :base) base
          (let* ((d (%direct-descriptor m base)) (gen (and d (host-descriptor-generation d)))
                 (old (%variant-find m (host-reference-model base) gen kind tag disp)))
            (or old (let ((i (loop for j below (length (host-model-variants m)) when (not (host-variant-active (aref (host-model-variants m) j))) do (return j))))
                    (unless i (error "Reference encoding capacity exhausted"))
                    (let ((v (aref (host-model-variants m) i))
                          (r (%host-ref m (host-reference-descriptor base) gen
                                        (+ (host-reference-address base) disp)
                                        kind tag disp)))
                      (setf (host-variant-active v) t (host-variant-reference v) r (host-variant-descriptor v) (host-reference-descriptor base)
                            (host-variant-generation v) gen (host-variant-kind v) kind (host-variant-tag v) tag (host-variant-displacement v) disp) r))))))))
(defmethod reference-address ((m host-object-model) start) (host-reference-address (multiple-value-bind (x d) (normalize-reference m start) (declare (ignore d)) x)))
(defmethod object-size ((m host-object-model) start) (host-descriptor-size (%direct-descriptor m (multiple-value-bind (x d) (normalize-reference m start) (declare (ignore d)) x))))
(defmethod object-alignment ((m host-object-model) start) (host-descriptor-alignment (%direct-descriptor m (multiple-value-bind (x d) (normalize-reference m start) (declare (ignore d)) x))))
(defmethod object-kind ((m host-object-model) start) (host-descriptor-kind (%direct-descriptor m (multiple-value-bind (x d) (normalize-reference m start) (declare (ignore d)) x))))
(defmethod object-kind-descriptor ((m host-object-model) kind) (%kind! m kind))
(defmethod reference-encoding-equal-p ((m host-object-model) a b) (%hm m) (eq a b))
(defmethod reference-equal ((m host-object-model) a b) (cond ((and (not (valid-reference-p m a)) (not (valid-reference-p m b))) (eql a b)) ((or (not (valid-reference-p m a)) (not (valid-reference-p m b))) nil) (t (multiple-value-bind (x d) (normalize-reference m a) (declare (ignore d)) (multiple-value-bind (y e) (normalize-reference m b) (declare (ignore e)) (eq x y))))))

(defun %init-desc (m address kind size descriptor)
  (let* ((r (%route-at m address)) (cell (and r (%cell r address))) (d (and r (aref (host-route-descriptors r) cell))))
    (unless (and r d (= (host-descriptor-start d) 0) (<= (+ address size) (host-route-limit r))) (error "Descriptor cell unavailable"))
    (let ((gen (1+ (host-descriptor-generation d)))) (when (= gen most-positive-fixnum) (error "Generation exhausted"))
      (setf (host-descriptor-start d) address (host-descriptor-size d) size
            (host-descriptor-alignment d) (%rulev (host-object-kind-description-alignment-rule kind) kind "alignment")
            (host-descriptor-kind d) kind (host-descriptor-descriptor d) descriptor (host-descriptor-generation d) gen
            (host-descriptor-route d) r (host-descriptor-cell d) cell (host-descriptor-active d) t)
      (%base-ref-at m address))))
(defun %descriptor-index (m d) (position d (host-model-descriptors m) :test #'eq))
(defmethod initialize-object ((m host-object-model) address kind size descriptor)
  (%bm m) (let* ((k (%kind! m kind)) (sz (%rulev (host-object-kind-description-size-rule k) k "size")) (al (%rulev (host-object-kind-description-alignment-rule k) k "alignment")))
    (unless (and (= size sz) (%p2 al) (zerop (mod address al)) (<= size (host-model-max-object-bytes m)) (eq descriptor k)) (error "Invalid initialization"))
    (let ((ref (%init-desc m address k size descriptor)))
      (let ((start (%word-index m address)) (end (+ start (ceiling size 8))))
        (loop for i from start below end do (setf (aref (host-model-words m) i) nil)))
      (loop for d across (host-object-kind-description-weak-descriptions k) do (setf (aref (host-model-words m) (+ (%word-index m address) (floor (host-weak-location-description-offset d) 8))) (host-weak-location-description-cleared-value d)))
      (loop for d across (host-object-kind-description-ephemeron-descriptions k) do (setf (aref (host-model-words m) (+ (%word-index m address) (floor (host-ephemeron-description-key-offset d) 8))) (host-ephemeron-description-cleared-key d) (aref (host-model-words m) (+ (%word-index m address) (floor (host-ephemeron-description-value-offset d) 8))) (host-ephemeron-description-cleared-value d)))
      ref)))
(defun %byte-index (m address) (%word-index m address))
(defmethod copy-object-representation ((m host-object-model) source destination)
  (%bm m) (let* ((s (host-reference-address (multiple-value-bind (x d) (normalize-reference m source) (declare (ignore d)) x))) (sd (%direct-descriptor m (%base-ref-at m s))) (daddr (if (valid-reference-p m destination) (host-reference-address destination) destination)) (dd (%desc-at m daddr)))
    (unless (and sd dd (not (host-descriptor-active dd)) (eq (host-descriptor-kind sd) (host-descriptor-kind dd))) (error "Invalid copy destination"))
    (dotimes (i (ceiling (host-descriptor-size sd) 8)) (setf (aref (host-model-words m) (+ (%word-index m daddr) i)) (aref (host-model-words m) (+ (%word-index m s) i))))
    (dotimes (i (host-descriptor-size sd)) (setf (aref (host-model-arena m) (+ (%word-index m daddr) (* i 8))) (aref (host-model-arena m) (+ (%word-index m s) (* i 8))))) destination))

(defun %borrow (m d generation word identity strength &optional stage)
  (let ((l (loop for x across (host-model-locations m) when (not (host-location-active x)) do (return x))))
    (unless l (error "Borrowed location capacity exhausted"))
    (setf (host-location-model l) m (host-location-descriptor l) d (host-location-generation l) generation (host-location-word-index l) word (host-location-identity l) identity (host-location-strength l) strength (host-location-stage l) stage (host-location-active l) t) l))
(defun %release (l) (setf (host-location-active l) nil))
(defun %loc-valid (m l) (unless (and (typep l 'host-location) (eq m (host-location-model l)) (host-location-active l)) (error "Invalid/stale location")) l)
(defun %loc-value (l) (aref (host-model-words (host-location-model l)) (host-location-word-index l)))
(defmethod load-reference ((m host-object-model) location &optional (order :relaxed)) (declare (ignore order)) (%loc-value (%loc-valid m location)))
(defmethod store-reference-raw ((m host-object-model) location value &optional (order :relaxed)) (declare (ignore order)) (setf (aref (host-model-words m) (host-location-word-index (%loc-valid m location))) value))
(defmethod cas-reference-raw ((m host-object-model) location old new order) (declare (ignore order)) (let* ((l (%loc-valid m location)) (x (%loc-value l))) (if (eq x old) (progn (setf (aref (host-model-words m) (host-location-word-index l)) new) (values x t)) (values x nil))))

(defun %map-kind-locations (m start fn which)
  (%bm m) (let* ((base (multiple-value-bind (x d) (normalize-reference m start) (declare (ignore d)) x)) (a (host-reference-address base)) (desc (%direct-descriptor m base)) (k (host-descriptor-kind desc)) (vec (ecase which (:strong (host-object-kind-description-strong-layout k)) (:weak (host-object-kind-description-weak-descriptions k)) (:eph (host-object-kind-description-ephemeron-descriptions k)))) (gen (host-descriptor-generation desc)))
    (loop for i below (length vec) do (multiple-value-bind (id off) (%slot (aref vec i) (* i 8)) (let ((l (%borrow m (%descriptor-index m desc) gen (+ (%word-index m a) (floor off 8)) id which))) (unwind-protect (ecase which (:strong (funcall fn id l)) (:weak (funcall fn id l (host-weak-location-description-cleared-value (aref vec i)))) (:eph nil)) (%release l)))))) nil)
(defmethod map-reference-locations ((m host-object-model) s f) (%map-kind-locations m s f :strong))
(defmethod map-weak-descriptors ((m host-object-model) s f) (%map-kind-locations m s f :weak))
(defmethod map-ephemeron-descriptors ((m host-object-model) s f) (%bm m) (let* ((base (multiple-value-bind (x d) (normalize-reference m s) (declare (ignore d)) x)) (a (host-reference-address base)) (desc (%direct-descriptor m base)) (gen (host-descriptor-generation desc)) (k (host-descriptor-kind desc)) (vec (host-object-kind-description-ephemeron-descriptions k))) (loop for i below (length vec) for x = (aref vec i) do (let ((l1 (%borrow m (%descriptor-index m desc) gen (+ (%word-index m a) (floor (host-ephemeron-description-key-offset x) 8)) (host-ephemeron-description-identity x) :key)) (l2 (%borrow m (%descriptor-index m desc) gen (+ (%word-index m a) (floor (host-ephemeron-description-value-offset x) 8)) (host-ephemeron-description-identity x) :value))) (unwind-protect (funcall f (host-ephemeron-description-identity x) l1 l2 (host-ephemeron-description-clear-key-p x) (host-ephemeron-description-cleared-key x) (host-ephemeron-description-cleared-value x)) (%release l2) (%release l1)))) nil)

(defun host-retire-object (m start) (%bm m) (let* ((base (multiple-value-bind (x d) (normalize-reference m start) (declare (ignore d)) x)) (a (host-reference-address base)) (r (%route-at m a)) (d (%direct-descriptor m base))) (when (or (null d) (host-descriptor-active d)) (setf (host-descriptor-active d) nil (host-descriptor-start d) 0)) nil))
(defmethod object-size ((m host-object-model) s) (host-descriptor-size (%direct-descriptor m (multiple-value-bind (x d) (normalize-reference m s) (declare (ignore d)) x))))
(defmethod object-alignment ((m host-object-model) s) (host-descriptor-alignment (%direct-descriptor m (multiple-value-bind (x d) (normalize-reference m s) (declare (ignore d)) x))))
(defmethod object-kind ((m host-object-model) s) (host-descriptor-kind (%direct-descriptor m (multiple-value-bind (x d) (normalize-reference m s) (declare (ignore d)) x))))
(defmethod object-kind-descriptor ((m host-object-model) k) (%kind! m k))

(defun host-object-payload-read (m s off) (aref (host-model-arena m) (+ (%word-index m (reference-address m s)) off)))
(defun host-object-payload-write (m s off v) (setf (aref (host-model-arena m) (+ (%word-index m (reference-address m s)) off)) v))
(defun %call-with-simulator-array-element (m s index f) (%bm m) (let* ((base (multiple-value-bind (x d) (normalize-reference m s) (declare (ignore d)) x)) (desc (%direct-descriptor m base))) (unless (and (integerp index) (<= 0 index) (< (* index 8) (host-descriptor-size desc))) (return-from %call-with-simulator-array-element :stale)) (let ((l (%borrow m (%descriptor-index m desc) (host-descriptor-generation desc) (+ (%word-index m (host-reference-address base)) index) index :numeric))) (unwind-protect (progn (funcall f l) :present) (%release l)))))

;;; Construction-time staged copies use fixed buffers; mappers borrow locations.
(defmethod copy-object-to-staging ((m host-object-model) source address cap) (%bm m) (let ((s (loop for x across (host-model-stages m) when (not (host-stage-active x)) do (return x)))) (unless s (error "Stage capacity exhausted")) (let* ((base (multiple-value-bind (x d) (normalize-reference m source) (declare (ignore d)) x)) (desc (%direct-descriptor m base)) (size (host-descriptor-size desc))) (unless (>= cap size) (error "Stage capacity exhausted")) (setf (host-stage-active s) t
           (host-stage-generation s) (host-descriptor-generation desc)
           (host-stage-source s) (host-reference-address base)
           (host-stage-destination s) address
           (host-stage-size s) size
           (host-stage-alignment s) (host-descriptor-alignment desc)
           (host-stage-kind s) (host-descriptor-kind desc)
           (host-stage-descriptor s) (host-descriptor-descriptor desc)) (dotimes (i size) (setf (aref (host-stage-bytes s) i) (aref (host-model-arena m) (+ (%word-index m (host-reference-address base)) i)))) (dotimes (i (ceiling size 8)) (setf (aref (host-stage-words s) i) (aref (host-model-words m) (+ (%word-index m (host-reference-address base)) i)))) (values s size))))
(defmethod map-staged-reference-locations ((m host-object-model) stage f) (declare (ignore f)) (%bm m) (unless (typep stage 'host-stage) (error "Foreign stage")) nil)
(defmethod map-staged-weak-descriptors ((m host-object-model) stage f) (declare (ignore f)) (%bm m) (unless (typep stage 'host-stage) (error "Foreign stage")) nil)
(defmethod map-staged-ephemeron-descriptors ((m host-object-model) stage f) (declare (ignore f)) (%bm m) (unless (typep stage 'host-stage) (error "Foreign stage")) nil)
(defmethod install-staged-object ((m host-object-model) stage destination) (%bm m) (unless (and (typep stage 'host-stage) (host-stage-active stage)) (error "Foreign/inactive stage")) (let ((d (%desc-at m destination))) (unless d (error "Invalid stage destination")) (dotimes (i (host-stage-size stage)) (setf (aref (host-model-arena m) (+ (%word-index m destination) i)) (aref (host-stage-bytes stage) i))) (dotimes (i (ceiling (host-stage-size stage) 8)) (setf (aref (host-model-words m) (+ (%word-index m destination) i)) (aref (host-stage-words stage) i))) (setf (host-stage-active stage) nil) nil))

(defmethod make-reference-location-handle ((m host-object-model) source location) (%bm m) (unless (typep location 'host-location) (return-from make-reference-location-handle (values nil :failed :invalid-location))) (let ((h (loop for x across (host-model-handles m) when (not (host-handle-active x)) do (return x))) (d (%direct-descriptor m source))) (unless h (return-from make-reference-location-handle (values nil :retry :capacity-exhausted))) (unless d (return-from make-reference-location-handle (values nil :failed :invalid-location))) (setf (host-handle-active h) t (host-handle-model h) m (host-handle-descriptor h) (%descriptor-index m d) (host-handle-generation h) (host-descriptor-generation d) (host-handle-identity h) (host-location-identity location) (host-handle-strength h) (host-location-strength location) (host-handle-index h) (host-location-word-index location)) (values h :complete nil)))
(defmethod call-with-reference-location ((m host-object-model) h f) (%bm m) (unless (functionp f) (error "Callback not callable")) (if (and (typep h 'host-handle) (host-handle-active h) (eq m (host-handle-model h))) (let ((d (aref (host-model-descriptors m) (host-handle-descriptor h)))) (if (and (host-descriptor-active d) (= (host-descriptor-generation d) (host-handle-generation h))) (let ((l (%borrow m (host-handle-descriptor h) (host-handle-generation h) (host-handle-index h) (host-handle-identity h) (host-handle-strength h)))) (unwind-protect (progn (funcall f l) :present) (%release l))) :stale)) :stale))
(defmethod make-staged-reference-location-handle ((m host-object-model) stage strength identity future) (declare (ignore stage strength identity future)) (%bm m) (values nil :failed :unsupported))


(defun %register-bound-object-model-auxiliary (construction model identity)
  "Charge the fixed planes and records created by BIND-OBJECT-MODEL.
The construction resource service owns duplicate identity checking."
  (unless (typep model 'host-bound-object-model)
    (error "Auxiliary registration requires a bound hosted model"))
  (let ((f (and (fboundp '%register-resource-auxiliary)
                #'%register-resource-auxiliary)))
    (unless f (error "Construction auxiliary registration is unavailable"))
    (funcall f construction identity model)
    (dolist (x (list (host-model-arena model) (host-model-words model)
                     (host-model-descriptors model) (host-model-variants model)
                     (host-model-handles model) (host-model-locations model)
                     (host-model-stages model) (host-model-routes model)))
      (funcall f construction identity x))
    (dotimes (i (length (host-model-routes model)))
      (let ((r (aref (host-model-routes model) i)))
        (funcall f construction identity r)
        (funcall f construction identity (host-route-descriptors r))
        (funcall f construction identity (host-route-bases r))))))
  (values))
