;;;; v14 serialized simulator root service. No native stack-map claim.
(in-package #:clamsara)

(define-condition host-protocol-error (error)
  ((reason :initarg :reason :reader host-error-reason))
  (:report (lambda (c s) (format s "Host protocol error: ~S" (host-error-reason c)))))
(defun host-reject (reason) (error 'host-protocol-error :reason reason))

(defgeneric host-root-value (location))
(defgeneric (setf host-root-value) (value location))
(defgeneric host-root-kind (location))
(defgeneric store-provider-root (client context token location reference))

(defclass simulator-root-location ()
  ((value :initform nil :accessor host-root-value)))
(defmethod host-root-kind ((location simulator-root-location))
  (declare (ignore location)) :exact)
(defclass simulator-root-provider ()
  ((locations :initarg :locations :reader simulator-provider-locations)))
(defun make-simulator-root-provider (capacity)
  (unless (typep capacity '(integer 0 #.most-positive-fixnum))
    (host-reject :invalid-provider-capacity))
  (let ((locations (make-array capacity)))
    (dotimes (i capacity)
      (setf (aref locations i) (make-instance 'simulator-root-location)))
    (make-instance 'simulator-root-provider :locations locations)))
(defun simulator-root-location (provider index)
  (aref (simulator-provider-locations provider) index))
(defmethod map-provider-roots ((provider simulator-root-provider) function)
  (let ((locations (simulator-provider-locations provider)))
    (dotimes (i (length locations)) (funcall function (aref locations i))))
  (values))

(defstruct (simulator-provider-token (:constructor %make-provider-token))
  owner identity generation provider locations (active-p nil) (position 0))
(defstruct (simulator-root-entry (:constructor %make-root-entry))
  token (seen 0))
(defstruct (simulator-coverage (:constructor %make-simulator-coverage))
  coordinator token roots (root-generation 0) (protected-p nil)
  (correction-failed-p nil) (borrowers 0) terminal-result)
(defstruct (simulator-root-snapshot (:constructor %make-root-snapshot))
  client coverage (active-p nil))
(defclass simulator-root-client ()
  ((providers :initarg :providers :reader simulator-root-providers)
   (directory :initform (make-hash-table :test #'eq) :reader simulator-root-directory)
   (generation :initform 0 :accessor simulator-root-generation)
   (admission-closed-p :initform nil :accessor simulator-root-admission-closed-p)
   (snapshot :initform (%make-root-snapshot) :reader simulator-client-snapshot)
   (pass :initform 0 :accessor simulator-root-pass)))
(defun make-simulator-root-client (&key (provider-capacity 64))
  (unless (typep provider-capacity '(integer 1 #.most-positive-fixnum))
    (host-reject :invalid-provider-capacity))
  (make-instance 'simulator-root-client
                 :providers (make-array provider-capacity :initial-element nil)))

(defun %valid-provider-token (client token)
  (and (simulator-provider-token-p token)
       (eq client (simulator-provider-token-owner token))
       (simulator-provider-token-active-p token)
       (eq token (aref (simulator-root-providers client)
                       (simulator-provider-token-position token)))))
(defun %provider-entry (client token location)
  (unless (%valid-provider-token client token) (host-reject :invalid-provider-token))
  (let ((entry (gethash location (simulator-root-directory client))))
    (unless (and entry (eq token (simulator-root-entry-token entry)))
      (host-reject :invalid-root-location))
    entry))

(defmethod register-root-provider ((client simulator-root-client)
                                   provider-id capacity provider)
  (when (or (simulator-root-admission-closed-p client)
            (simulator-root-snapshot-active-p (simulator-client-snapshot client)))
    (host-reject :root-registration-closed))
  (unless (and provider-id (typep capacity '(integer 0 #.most-positive-fixnum)))
    (host-reject :invalid-provider-description))
  (when (= most-positive-fixnum (simulator-root-generation client))
    (host-reject :root-generation-exhausted))
  (let* ((providers (simulator-root-providers client))
         (position (position nil providers))
         (locations (make-array capacity :initial-element nil))
         (count 0))
    (unless position (host-reject :provider-capacity-exhausted))
    (dotimes (i (length providers))
      (let ((other (aref providers i)))
        (when (and other (eql provider-id (simulator-provider-token-identity other)))
          (host-reject :duplicate-provider-identity))))
    ;; Enumeration and all validation precede registration publication.
    (map-provider-roots provider
      (lambda (location)
        (when (or (= count capacity) (null location))
          (host-reject :invalid-provider-enumeration))
        (when (or (gethash location (simulator-root-directory client))
                  (position location locations :end count :test #'eq))
          (host-reject :duplicate-root-location))
        (unless (eq :exact (host-root-kind location))
          (host-reject :unsupported-root-kind))
        (setf (aref locations count) location)
        (incf count)))
    (let* ((exact (subseq locations 0 count))
           (token (%make-provider-token
                   :owner client :identity provider-id
                   :generation (1+ (simulator-root-generation client))
                   :provider provider :locations exact :position position))
           (entries (map 'vector (lambda (unused)
                                   (declare (ignore unused))
                                   (%make-root-entry :token token)) exact))
           (committed nil))
      (unwind-protect
           (progn
             (dotimes (i count)
               (setf (gethash (aref exact i) (simulator-root-directory client))
                     (aref entries i)))
             (setf (simulator-root-generation client)
                   (simulator-provider-token-generation token)
                   (simulator-provider-token-active-p token) t
                   (aref providers position) token
                   committed t)
             token)
        (unless committed
          (dotimes (i count)
            (remhash (aref exact i) (simulator-root-directory client))))))))

(defmethod unregister-root-provider ((client simulator-root-client) token)
  (unless (%valid-provider-token client token) (host-reject :invalid-provider-token))
  (when (or (simulator-root-admission-closed-p client)
            (simulator-root-snapshot-active-p (simulator-client-snapshot client)))
    (host-reject :root-generation-protected))
  (when (= most-positive-fixnum (simulator-root-generation client))
    (host-reject :root-generation-exhausted))
  (let ((locations (simulator-provider-token-locations token)))
    (dotimes (i (length locations))
      (remhash (aref locations i) (simulator-root-directory client))))
  (setf (aref (simulator-root-providers client)
              (simulator-provider-token-position token)) nil
        (simulator-provider-token-active-p token) nil)
  (incf (simulator-root-generation client))
  (values))

(defmethod root-provider-load ((client simulator-root-client) token location)
  (%provider-entry client token location)
  (when (simulator-root-admission-closed-p client)
    (host-reject :root-access-stopped))
  (host-root-value location))
(defmethod root-provider-store ((client simulator-root-client) context token location reference)
  (%provider-entry client token location)
  (when (simulator-root-admission-closed-p client)
    (host-reject :root-access-stopped))
  ;; Context and reference admission, reservations, and sole exposure belong
  ;; to the runtime's composed :ROOT-STORE route. No raw-store fallback.
  (store-provider-root client context token location reference))

(defvar *simulator-borrowed-root-client* nil)
(defvar *simulator-borrowed-root-location* nil)
(defvar *simulator-root-map-client* nil)
(defvar *simulator-root-map-token* nil)
(defvar *simulator-root-map-function* nil)
(defvar *simulator-root-map-count* 0)
(defvar *simulator-root-map-pass* 0)
(defun %simulator-root-visitor (location)
  (let* ((client *simulator-root-map-client*)
         (entry (%provider-entry client *simulator-root-map-token* location)))
    (when (= *simulator-root-map-pass* (simulator-root-entry-seen entry))
      (host-reject :duplicate-root-enumeration))
    (setf (simulator-root-entry-seen entry) *simulator-root-map-pass*)
    (incf *simulator-root-map-count*)
    (let ((*simulator-borrowed-root-client* client)
          (*simulator-borrowed-root-location* location))
      (funcall *simulator-root-map-function* client location))))
(defun %check-borrowed-root (client location)
  (unless (and (eq client *simulator-borrowed-root-client*)
               (eq location *simulator-borrowed-root-location*)
               (simulator-root-snapshot-active-p (simulator-client-snapshot client)))
    (host-reject :root-location-not-borrowed)))
(defmethod load-root ((client simulator-root-client) location)
  (%check-borrowed-root client location)
  (host-root-value location))
(defmethod store-root ((client simulator-root-client) location reference)
  (%check-borrowed-root client location)
  (setf (host-root-value location) reference))
(defmethod root-location-kind ((client simulator-root-client) location)
  (%check-borrowed-root client location)
  (host-root-kind location))

(defmethod with-root-snapshot ((client simulator-root-client) coverage function)
  (unless (and (simulator-coverage-p coverage)
               (eq client (simulator-coverage-roots coverage))
               (simulator-coverage-protected-p coverage)
               (not (simulator-coverage-correction-failed-p coverage))
               (= (simulator-root-generation client)
                  (simulator-coverage-root-generation coverage)))
    (host-reject :invalid-root-coverage))
  (let ((snapshot (simulator-client-snapshot client)) (complete nil))
    (when (simulator-root-snapshot-active-p snapshot)
      (host-reject :snapshot-already-active))
    (setf (simulator-root-snapshot-client snapshot) client
          (simulator-root-snapshot-coverage snapshot) coverage
          (simulator-root-snapshot-active-p snapshot) t)
    (incf (simulator-coverage-borrowers coverage))
    (unwind-protect
         (multiple-value-prog1 (funcall function snapshot) (setf complete t))
      (unless complete (setf (simulator-coverage-correction-failed-p coverage) t))
      (setf (simulator-root-snapshot-active-p snapshot) nil
            (simulator-root-snapshot-coverage snapshot) nil)
      (decf (simulator-coverage-borrowers coverage)))))
(defmethod map-root-locations ((snapshot simulator-root-snapshot) function)
  (unless (and (simulator-root-snapshot-active-p snapshot)
               (simulator-coverage-protected-p (simulator-root-snapshot-coverage snapshot)))
    (host-reject :inactive-root-snapshot))
  (let* ((client (simulator-root-snapshot-client snapshot))
         (providers (simulator-root-providers client)))
    (when (= most-positive-fixnum (simulator-root-pass client))
      ;; Safe reset under covering stop, before this pass visits a location.
      (dotimes (i (length providers))
        (let ((token (aref providers i)))
          (when token
            (let ((locations (simulator-provider-token-locations token)))
              (dotimes (j (length locations))
                (setf (simulator-root-entry-seen
                       (gethash (aref locations j) (simulator-root-directory client))) 0))))))
      (setf (simulator-root-pass client) 0))
    (let ((*simulator-root-map-client* client)
          (*simulator-root-map-function* function)
          (*simulator-root-map-pass* (incf (simulator-root-pass client))))
      (dotimes (i (length providers))
        (let ((*simulator-root-map-token* (aref providers i))
              (*simulator-root-map-count* 0))
          (when *simulator-root-map-token*
            (map-provider-roots
             (simulator-provider-token-provider *simulator-root-map-token*)
             #'%simulator-root-visitor)
            (unless (= *simulator-root-map-count*
                       (length (simulator-provider-token-locations *simulator-root-map-token*)))
              (host-reject :missing-root-location)))))))
  (values))
