(require :asdf)
(asdf:initialize-source-registry '(:source-registry (:directory #p"/tmp/clamsara-cas-staged-yik9o9qk/") :ignore-inherited-configuration))
(asdf:initialize-output-translations '(:output-translations (t ("/tmp/clamsara-cas-staged-native-lhcu6e0_/fasl/" :implementation)) :ignore-inherited-configuration))
(assert (equal (truename #p"/tmp/clamsara-cas-staged-yik9o9qk/") (truename (asdf:system-source-directory :clamsara))))
;; Distinct source paths must not collide in the private FASL cache.
(let ((left (asdf:apply-output-translations #p"/one/package.fasl"))
      (right (asdf:apply-output-translations #p"/two/package.fasl")))
  (format t "~&PRIVATE-OUTPUT-PATHS ~S ~S~%" left right)
  (assert (not (equal left right))))
(asdf:test-system :clamsara)
(asdf:test-system :clamsara/tools/test)
(asdf:test-system :clamsara/workload/test)
(asdf:test-system :clamsara/generational/test)
(asdf:test-system :clamsara/quality/generational/test)
(asdf:load-system :clamsara/quality)
(clamsara.structure:assert-project-structure :include-optional-loaded t)
(format t "~&GENERATIONAL-CHECKPOINT-COMPONENTS-PASS~%")

(load #p"/tmp/clamsara-cas-staged-yik9o9qk/docs/evidence/cas-boundaries-a3a0bae/independent-baseline/acceptance-03.lisp")
(load #p"/tmp/clamsara-cas-staged-yik9o9qk/docs/evidence/cas-boundaries-a3a0bae/fixed-review/additional-05.lisp")
(load #p"/tmp/clamsara-cas-staged-yik9o9qk/docs/evidence/cas-boundaries-a3a0bae/final-review/claims-transforms-03.lisp")
(uiop:symbol-call :clamsara.quality.barrier-history :run-barrier-history-tests)
(uiop:symbol-call :clamsara.quality.barrier-history :run-barrier-edge-tests)
(uiop:symbol-call :clamsara.quality.barrier-boundaries :run-barrier-boundary-tests)
(uiop:symbol-call :clamsara.quality.barrier-claims :run-barrier-claim-tests)
(format t "~&CAS-INTEGRATED-184-REPEAT-INDEPENDENT-176-PASS~%")

(format t "~&CAS-ONLY-STAGED-TREE-PASS root=~A~%" (asdf:system-source-directory :clamsara))
