;;;; Integrated independent 15 public-claim and five managed-transform histories.
;;;; Original claims-transforms-03.lisp and both review logs remain archived.
;;;; The explicit runner preserves earlier failed owners across repetitions.
;;;; Independent public-claim/pool and non-identity transform proofs.
;;;; Real make-quality-world configure-plan seam; no production method override.
(defpackage #:clamsara.quality.barrier-claims
  (:use #:cl #:clamsara #:clamsara.quality.support)
  (:export #:run-barrier-claim-tests))
(in-package #:clamsara.quality.barrier-claims)
(defvar *capacity* 4)
(defvar *world* nil)
(defvar *last-plan* nil)
(defvar *cases* 0)
(defvar *failures* 0)
(defvar *failed-worlds* nil)
(defvar *capture* nil)
(defvar *trace* nil)
(defvar *trace-count* 0)
(defvar *loads* 0)
(defvar *stores* 0)
(defvar *expected-live* 4)
(defvar *transform-proof* nil)
(defvar *raw-old* nil)
(defvar *caller-new* nil)
(defvar *read-middle* nil)
(defvar *read-final* nil)
(defvar *write-middle* nil)
(defvar *write-final* nil)
(define-condition proof-fault (error) ())
(defclass claim-rule ()
  ((name :initarg :name :reader rule-name)
   (events :initarg :events :reader rule-events)
   (before :initarg :before :reader rule-before)
   (plan :initarg :plan :reader rule-plan)
   (claims :initarg :claims :reader rule-claims)
   (retry-phase :initform nil :accessor rule-retry-phase)
   (retried :initform nil :accessor rule-retried)
   (acquires :initform 0 :accessor rule-acquires)
   (cancels :initform 0 :accessor rule-cancels)
   (consumes :initform 0 :accessor rule-consumes)
   (exposure-checks :initform 0 :accessor rule-exposure-checks)
   (fault :initform (make-condition 'proof-fault) :reader rule-fault)))
(defclass pool-plan (clamsara::semispace-plan)
  ((rules :initform nil :accessor plan-rules)
   (capacity :initarg :capacity :reader plan-capacity)
   (pool :initform nil :accessor plan-pool)
   (live :initform 0 :accessor plan-live)
   (peak :initform 0 :accessor plan-peak)))
(defun note (rule phase operation)
  (when *capture*
    (when (> (+ *trace-count* 4) (length *trace*)) (error (rule-fault rule)))
    (setf (aref *trace* *trace-count*) phase
          (aref *trace* (+ *trace-count* 1)) (rule-name rule)
          (aref *trace* (+ *trace-count* 2)) operation
          (aref *trace* (+ *trace-count* 3)) (plan-live (rule-plan rule)))
    (incf *trace-count* 4)))
(defun names-at (phase)
  (loop for i from 0 below *trace-count* by 4
        when (eq (aref *trace* i) phase) collect (aref *trace* (+ i 1))))
(defun rows ()
  (loop for i from 0 below *trace-count* by 4
        collect (list (aref *trace* i) (aref *trace* (+ i 1))
                      (aref *trace* (+ i 2)) (aref *trace* (+ i 3)))))
(defun raw-observer (kind)
  (ecase kind (:load (incf *loads*)) (:store (incf *stores*))))
(defmethod component-resources ((plan pool-plan))
  (append (call-next-method)
          (list (make-resource-contribution
                 plan :independent-cas-pool :runtime-object-vector
                 :minimum-physical-bytes (+ 16 (* 8 (plan-capacity plan)))
                 :logical-entry-bound (plan-capacity plan) :auxiliary-bytes 0
                 :allocation-context :construction-only
                 :exhaustion-action :reject-before-publication))))
(defmethod component-barrier-contributions ((plan pool-plan)) (copy-list (plan-rules plan)))
(defmethod initialize-component ((plan pool-plan) construction)
  (call-next-method)
  (multiple-value-bind (handle present physical entries auxiliary)
      (construction-resource construction :independent-cas-pool)
    (declare (ignore physical auxiliary))
    (unless (and present (typep handle 'simple-vector)
                 (= entries (plan-capacity plan)) (= entries (length handle)))
      (error "Public pool resource mismatch"))
    (setf (plan-pool plan) handle)))
(defmethod clamsara::map-construction-auxiliary-storage ((plan pool-plan) f)
  (call-next-method)
  (clamsara::%map-construction-cons-storage (plan-rules plan) f)
  (dolist (rule (plan-rules plan))
    (funcall f rule) (funcall f (rule-fault rule))
    (clamsara::%map-construction-cons-storage (rule-events rule) f)
    (clamsara::%map-construction-cons-storage (rule-before rule) f)
    (clamsara::%map-construction-cons-storage (rule-claims rule) f)
    (dolist (claim (rule-claims rule)) (funcall f claim)))
  ;; The pool handle is the acquired resource itself; do not double-charge it
  ;; as unrelated configuration auxiliary backing.
  (values))
(defun configure-pool-plan (plan)
  (change-class plan 'pool-plan :capacity *capacity*)
  (setf *last-plan* plan
        (plan-rules plan)
        (loop for (name event next) in '((:w1 :cas :r1) (:r1 :read :w2)
                                        (:w2 :cas :r2) (:r2 :read nil))
              collect (make-instance
                       'claim-rule :name name :events (list event)
                       :before (when next (list next)) :plan plan
                       :claims (list (make-barrier-reservation-claim
                                      plan '(:resource :independent-cas-pool)
                                      :runtime-object-vector 1)))))
  plan)
(defmethod describe-barrier-contribution ((rule claim-rule))
  (values (rule-name rule) (copy-list (rule-events rule)) (copy-list (rule-claims rule))
          t t (copy-list (rule-before rule)) nil :transform
          :retry-before-exposure/fatal-after))
(defun retry-here (rule phase)
  (when (and *capture* (eq (rule-retry-phase rule) phase) (not (rule-retried rule)))
    (setf (rule-retried rule) t) t))
(defun valid-token (rule token)
  (unless (and (typep token 'fixnum) (<= 0 token) (< token (length (plan-pool (rule-plan rule))))
               (eq rule (aref (plan-pool (rule-plan rule)) token)))
    (error (rule-fault rule))))
(defmethod barrier-contribution-reserve ((rule claim-rule) context operation location)
  (declare (ignore context location))
  (note rule :reserve operation)
  (when (retry-here rule :reserve) (return-from barrier-contribution-reserve (values nil :retry)))
  (let* ((plan (rule-plan rule))
         ;; The public per-rule claim is ONE maximum simultaneous entry,
         ;; including competing invocations. Enforce it even while other pool
         ;; cells remain free, rather than assuming a single caller.
         (index (unless (find rule (plan-pool plan) :test #'eq)
                  (position nil (plan-pool plan)))))
    (unless index (return-from barrier-contribution-reserve (values nil :retry)))
    (setf (aref (plan-pool plan) index) rule)
    (incf (plan-live plan))
    (setf (plan-peak plan) (max (plan-peak plan) (plan-live plan)))
    (incf (rule-acquires rule))
    (note rule :acquire operation)
    ;; Reservation is an index into the genuine acquired shared pool. It holds
    ;; no borrowed location or managed reference.
    (values index :ready)))
(defmethod barrier-contribution-admit ((rule claim-rule) token context operation location)
  (declare (ignore context location))
  (valid-token rule token)
  (when *capture*
    (unless (and (= (plan-live (rule-plan rule)) *expected-live*) (zerop *loads*))
      (error (rule-fault rule))))
  (note rule :admit operation)
  (if (retry-here rule :admit) :retry :complete))
(defmethod barrier-contribution-transform ((rule claim-rule) token context operation location old candidate)
  (declare (ignore context location))
  (valid-token rule token)
  (note rule :transform operation)
  (let ((next candidate))
    (when *transform-proof*
      (unless (eq old *raw-old*) (error (rule-fault rule)))
      (ecase (rule-name rule)
        (:r1 (unless (eq candidate *raw-old*) (error (rule-fault rule)))
             (setf next *read-middle*))
        (:r2 (unless (eq candidate *read-middle*) (error (rule-fault rule)))
             (setf next *read-final*))
        (:w1 (unless (eq candidate *caller-new*) (error (rule-fault rule)))
             (setf next *write-middle*))
        (:w2 (unless (eq candidate *write-middle*) (error (rule-fault rule)))
             (setf next *write-final*))))
    (values next (if (retry-here rule :transform) :retry :complete))))
(defun check-exposure-values (rule old final operation)
  (when *transform-proof*
    (unless (and (eq old *raw-old*)
                 (eq final (if (eq operation :read) *read-final* *write-final*)))
      (error (rule-fault rule)))
    (incf (rule-exposure-checks rule))))
(defmethod barrier-contribution-before-exposure ((rule claim-rule) token context operation location old final)
  (declare (ignore context location))
  (valid-token rule token)
  (check-exposure-values rule old final operation)
  (note rule :before operation)
  (values))
(defun settle (rule token phase operation)
  (valid-token rule token)
  (note rule phase operation)
  (setf (aref (plan-pool (rule-plan rule)) token) nil)
  (decf (plan-live (rule-plan rule)))
  (ecase phase (:cancel (incf (rule-cancels rule))) (:after (incf (rule-consumes rule))))
  (values))
(defmethod barrier-contribution-after-exposure ((rule claim-rule) token context operation location old final)
  (declare (ignore context location))
  (check-exposure-values rule old final operation)
  (settle rule token :after operation))
(defmethod barrier-contribution-cancel ((rule claim-rule) token) (settle rule token :cancel nil))
(defun reset-observer (w)
  (let ((plan (world-plan w)))
    (check (and (zerop (plan-live plan)) (every #'null (plan-pool plan))) "Observer reset would hide an owned pool entry")
    (setf (plan-peak plan) 0 *loads* 0 *stores* 0 *trace-count* 0)
    (fill *trace* nil)
    (dolist (rule (plan-rules plan))
      (setf (rule-acquires rule) 0 (rule-cancels rule) 0 (rule-consumes rule) 0
            (rule-retried rule) nil (rule-exposure-checks rule) 0))))
(defun settled (w)
  (let ((plan (world-plan w)))
    (check (and (zerop (plan-live plan)) (every #'null (plan-pool plan))) "Shared resource entry still owned")
    (dolist (rule (plan-rules plan))
      (check (= (rule-acquires rule) (+ (rule-cancels rule) (rule-consumes rule))) "Resource not settled exactly once"))))
(defun verify-public-claims (w)
  (let ((plan (world-plan w)) (sum 0))
    (dolist (rule (component-barrier-contributions plan))
      (dolist (claim (nth-value 2 (describe-barrier-contribution rule)))
        (multiple-value-bind (resource representation maximum) (describe-barrier-reservation-claim claim)
          (check (equal resource '(:resource :independent-cas-pool)) "Claim names wrong public resource")
          (check (eq representation :runtime-object-vector) "Claim entry representation mismatch")
          (check (= maximum 1) "Unexpected per-rule public claim")
          (incf sum maximum))))
    (multiple-value-bind (handle present physical entries auxiliary)
        (construction-resource (clamsara::configuration-construction-context (world-configuration w))
                               :independent-cas-pool)
      (declare (ignore physical auxiliary))
      (check (and present (= entries sum 4) (= (length handle) 4)
                  (eq handle (plan-pool plan)))
             "Test does not use exact-capacity acquired public claim pool"))))
(defun invoke (w source operation expected new)
  ;; Values and targets are fetched from registered roots by the caller before
  ;; this measured interval. The observer sees no incidental root reads.
  (let ((*capture* t)
        (clamsara.quality.support::*reference-operation-observer* #'raw-observer)
        (a nil) (b nil) (c nil) (index 0) (found nil)
        (barrier (configuration-barrier (world-configuration w))))
    (map-reference-locations
     (world-model w) source
     (lambda (identity location)
       (declare (ignore identity))
       (when (= index 1)
         (setf found t)
         (multiple-value-setq (a b c)
           (ecase operation
             (:cas (barrier-compare-exchange barrier (world-context w) location expected new))
             (:read (barrier-read barrier (world-context w) location)))))
       (incf index)))
    (check found "No real source reference location")
    (values a b c)))
(defun raw-slot (w source)
  (let ((index 0) (value nil))
    (map-reference-locations
     (world-model w) source
     (lambda (identity location)
       (declare (ignore identity))
       (when (= index 1) (setf value (load-reference (world-model w) location :acquire)))
       (incf index)))
    value))
(defun clear-retries (w)
  (dolist (rule (plan-rules (world-plan w))) (setf (rule-retry-phase rule) nil)))
(defun one (label body &key (capacity 4))
  (incf *cases*)
  (let ((*capacity* capacity) (*world* nil) (*last-plan* nil)
        (*capture* nil) (*trace* (make-array 1024 :initial-element nil))
        (*trace-count* 0) (*loads* 0) (*stores* 0) (*expected-live* 4))
    (handler-case
        (progn
          (setf *world* (make-quality-world :configure-plan #'configure-pool-plan :root-count 12))
          (verify-public-claims *world*)
          (let ((source (allocate-node *world* 701)) (old (allocate-node *world* 702))
                (new (allocate-node *world* 703)))
            (set-world-root *world* 0 source)
            (set-world-root *world* 1 old)
            (set-world-root *world* 2 new)
            (set-node-slot *world* source 1 old)
            (reset-observer *world*)
            (let ((outcome
                    (catch 'clamsara::simulator-fatal
                      (funcall body *world* source old new)
                      :body-complete)))
              (check (eq outcome :body-complete)
                     "Unexpected fatal diagnostic in public claim history: ~S" outcome)))
          (settled *world*)
          (clear-retries *world*)
          (close-quality-world *world*)
          (format t "~&CLAIM-PROOF-PASS ~S~%" label))
      (error (condition)
        (incf *failures*)
        (push (list label *world* *last-plan* condition (rows)) *failed-worlds*)
        (format t "~&CLAIM-PROOF-FAIL ~S [~S] ~A~%TRACE ~S~%" label (type-of condition) condition (rows))))))

(defun assert-match (w source old new)
  (multiple-value-bind (observed success status) (invoke w source :cas old new)
    (check (and (eq observed old) success (eq status :complete)) "Exact-capacity match result"))
  (check (and (= *loads* 1) (= *stores* 1)) "Match is not one real load/store")
  (check (= (plan-peak (world-plan w)) 4) "Read/write union was not simultaneously owned")
  (check (eq (raw-slot w source) new) "Matched raw slot did not receive caller new")
  (check (equal (names-at :before) '(:w1 :r1 :w2 :r2)) "Shared-pool global before order")
  (check (equal (names-at :after) '(:w1 :r1 :w2 :r2)) "Shared-pool consume order")
  (check (null (names-at :cancel)) "Successful pool reservation canceled")
  (dolist (rule (plan-rules (world-plan w)))
    (check (= (rule-acquires rule) (rule-consumes rule) 1) "Success did not consume once"))
  (settled w))

(defun install-transform-targets (w old)
  ;; Root every managed transform target before using it as an entry argument.
  (loop for index from 3 to 8 for id from 704 to 709
        do (set-world-root w index (allocate-node w id)))
  (set-node-slot w (read-world-root w 6) 1 (read-world-root w 7))
  (set-node-slot w old 1 (read-world-root w 8)))
(defun check-post-gc-graph (w matched)
  ;; Drop independent target roots only after the measured entry and its rooted
  ;; argument/transform bindings have ended. The stored edge must retain them.
  (loop for index from 1 below 12 do (set-world-root w index nil))
  (let ((expected (if matched '((701 707 nil) (707 708 nil) (708 nil nil))
                     '((701 702 nil) (702 709 nil) (709 nil nil)))))
    (dotimes (pass 2)
      (let ((report (collect-world w)))
        (check (eq (cycle-result-status report) :complete) "Real post-transform collection did not complete")
        (when (zerop pass)
          (multiple-value-bind (dead known) (cycle-result-count report :objects-dead)
            (check (and known (= dead 6)) "Unstored transform alternatives retained or live target lost"))))
      (let ((snapshot (snapshot-world-graph w)))
        (check (equal (first snapshot) (cons 701 (make-list 11 :initial-element nil))) "Post-GC root graph changed")
        (check (equal (second snapshot) expected) "Actual post-GC stored graph differs from target graph")))))
(defun test-transform (mode)
  (one (list :managed-nonidentity-transform mode)
    (lambda (w source old new)
      (declare (ignore new))
      (install-transform-targets w old)
      ;; All ROOT-PROVIDER-LOAD calls precede the raw-operation observer binding.
      (let* ((*raw-old* (read-world-root w 1)) (*caller-new* (read-world-root w 2))
             (*read-middle* (read-world-root w 3)) (*read-final* (read-world-root w 4))
             (*write-middle* (read-world-root w 5)) (*write-final* (read-world-root w 6))
             (*transform-proof* t)
             (*expected-live* (if (eq mode :read) 2 4))
             (operation (if (eq mode :read) :read :cas))
             (expected (if (eq mode :mismatch-expected-is-read-result) *read-final* *raw-old*))
             (retry-rule (case mode
                           (:read-transform-retry (second (plan-rules (world-plan w))))
                           (:write-transform-retry (third (plan-rules (world-plan w)))))))
        (check (and (not (eq *raw-old* *read-middle*)) (not (eq *read-middle* *read-final*))
                    (not (eq *caller-new* *write-middle*)) (not (eq *write-middle* *write-final*)))
               "Targets do not exercise non-identity transforms")
        (reset-observer w)
        (when retry-rule (setf (rule-retry-phase retry-rule) :transform))
        (when retry-rule
          (multiple-value-bind (observed success status) (invoke w source :cas expected *caller-new*)
            (check (and (null observed) (null success) (eq status :retry)) "Transformed retry leaked a managed candidate"))
          (check (and (= *loads* 1) (zerop *stores*) (eq (raw-slot w source) old)) "Transform retry changed raw slot")
          (check (equal (names-at :cancel) '(:r2 :w2 :r1 :w1)) "Transform retry lost real resource claims")
          (check (and (null (names-at :before)) (null (names-at :after))) "Transform retry exposed candidate")
          (settled w)
          (clear-retries w)
          (reset-observer w))
        (multiple-value-bind (observed success status) (invoke w source operation expected *caller-new*)
          (check (eq observed *read-final*) "Returned observed is not the final managed READ target")
          (if (eq operation :read)
              (check (eq success :complete) "Read status")
              (check (and (eq status :complete)
                          (eq (not (null success)) (not (eq mode :mismatch-expected-is-read-result))))
                     "CAS compared transformed observed instead of raw expected")))
        (let ((matched (not (member mode '(:read :mismatch-expected-is-read-result)))))
          (check (= *loads* 1) "Incidental root reads were counted as the sole slot load")
          (check (= *stores* (if matched 1 0)) "Wrong number of raw stores after transforms")
          (check (eq (raw-slot w source) (if matched *write-final* *raw-old*)) "Physical stored target wrong")
          (check (equal (names-at :transform) (if matched '(:r1 :r2 :w1 :w2) '(:r1 :r2)))
                 "Write transforms ran on a mismatch/read or candidate chain order changed")
          (check (equal (names-at :before) (if matched '(:w1 :r1 :w2 :r2) '(:r1 :r2)))
                 "Non-identity exposure global order")
          (check (equal (names-at :after) (if matched '(:w1 :r1 :w2 :r2) '(:r1 :r2)))
                 "Non-identity after order")
          (dolist (rule (plan-rules (world-plan w)))
            (check (= (rule-exposure-checks rule)
                      (if (or matched (member :read (rule-events rule))) 2 0))
                   "Raw-old/per-path-final callback assertions did not run"))
          (settled w)))
      ;; No transform target escapes as an unrooted input across these real GCs.
      ;; The entry-only authored transform bindings ended above. The unchanged
      ;; collector scans actual heap slots; the graph oracle reads real objects.
      (check-post-gc-graph w (not (member mode '(:read :mismatch-expected-is-read-result)))))))
(defun run-barrier-claim-tests ()
  (let ((*cases* 0) (*failures* 0)
        (old-failed (length *failed-worlds*)))
    ;; Actual claims total 4 entries. Capacity 3 must fail before publication and
    ;; release the real acquisition transaction, not merely trip a busy marker.
    (incf *cases*)
    (let ((*capacity* 3) (*world* nil) (*last-plan* nil)
          (*construction-observation* (make-construction-observation)))
      (handler-case
          (let ((rejection nil))
            (handler-case
                (setf *world* (make-quality-world :configure-plan #'configure-pool-plan :root-count 12))
              (clamsara::construction-rejected (condition) (setf rejection condition)))
            (check (and rejection
                        (eq (clamsara::construction-rejection-reason rejection) :barrier-claim-capacity-exhausted))
                   "Undersized public claim pool did not reject for its capacity")
            (check (clamsara::construction-rejection-paths rejection) "Capacity rejection has no resource path")
            (let* ((construction (observed-construction *construction-observation*))
                   (configuration (clamsara::construction-configuration construction))
                   (resource (gethash :independent-cas-pool (clamsara::%context-resources construction))))
              (check construction "No real resource acquisition observed")
              (check (eq (clamsara::%configuration-state configuration) :failed) "Undersized configuration published")
              (check (not (clamsara::%configuration-barrier-bound-p configuration)) "Capacity checked after barrier publication")
              (check (eq (clamsara::%context-state construction) :released) "Capacity rejection did not unwind")
              (check (= (clamsara::%resource-state-entry-capacity resource) 3) "Not the intended undersized resource")
              (check (clamsara::%resource-state-released-p resource) "Rejected pool resource not released")
              (check (every #'clamsara::%transaction-entry-released-p
                            (clamsara::%context-transaction-log construction)) "Acquisition unwind incomplete")
              (check (null (plan-pool *last-plan*)) "Rejected plan initialized runtime pool"))
            (format t "~&CLAIM-PROOF-PASS :PUBLIC-CLAIMS-UNDERSIZED-REJECT~%"))
        (error (condition)
          (incf *failures*)
          (push (list :public-claims-undersized-reject *world* *last-plan* condition nil) *failed-worlds*)
          (format t "~&CLAIM-PROOF-FAIL :PUBLIC-CLAIMS-UNDERSIZED-REJECT [~S] ~A~%" (type-of condition) condition))))
    (one :exact-capacity-match-and-reuse
      (lambda (w source old new)
        (assert-match w source old new)
        (reset-observer w)
        (assert-match w source new old)))
    (one :exact-capacity-mismatch-and-reuse
      (lambda (w source old new)
        (multiple-value-bind (observed success status) (invoke w source :cas nil new)
          (check (and (eq observed old) (null success) (eq status :complete)) "Shared-pool mismatch result"))
        (check (and (= *loads* 1) (zerop *stores*) (eq (raw-slot w source) old)) "Mismatch mutated slot/load count")
        (check (= (plan-peak (world-plan w)) 4) "Mismatch omitted simultaneous write/read reservation")
        (check (equal (names-at :cancel) '(:w2 :w1)) "Mismatch did not reverse-cancel write-only pool entries")
        (check (equal (names-at :transform) '(:r1 :r2)) "Mismatch ran a write transform")
        (check (equal (names-at :before) '(:r1 :r2)) "Mismatch exposed write-only rule")
        (check (equal (names-at :after) '(:r1 :r2)) "Mismatch consumed wrong pool entries")
        (dolist (row (rows))
          (when (eq (first row) :before) (check (= (fourth row) 2) "Read exposure retained write-only pool entries")))
        (settled w)
        (reset-observer w)
        (assert-match w source old new)))
    (dolist (phase '(:reserve :admit :transform))
      (dotimes (position 4)
        (one (list :public-claim-retry phase position)
          (lambda (w source old new)
            (let* ((rules (plan-rules (world-plan w))) (rule (nth position rules)))
              (setf (rule-retry-phase rule) phase)
              (multiple-value-bind (observed success status) (invoke w source :cas old new)
                (check (and (null observed) (null success) (eq status :retry)) "Resource retry exposed candidate"))
              (check (eq (raw-slot w source) old) "Resource retry changed slot")
              (check (= *loads* (if (eq phase :transform) 1 0)) "Resource retry raw-load count")
              (check (zerop *stores*) "Resource retry performed a raw store")
              (check (= (plan-peak (world-plan w)) (if (eq phase :reserve) position 4))
                     "Resource live peak does not match actual acquired claims")
              (check (equal (names-at :cancel)
                            (reverse (mapcar #'rule-name (if (eq phase :reserve) (subseq rules 0 position) rules))))
                     "Resource retry reverse settlement order")
              (check (and (null (names-at :before)) (null (names-at :after))) "Retry exposed/consumed entries")
              (loop for r in rules for i from 0
                    for n = (if (and (eq phase :reserve) (>= i position)) 0 1)
                    do (check (= (rule-acquires r) (rule-cancels r) n) "Resource acquired/canceled twice")
                       (check (zerop (rule-consumes r)) "Retry consumed resource instead of cancellation"))
              (settled w)
              (clear-retries w)
              (reset-observer w)
              (assert-match w source old new))))))

    (dolist (mode '(:match-raw-expected :mismatch-expected-is-read-result :read
                    :read-transform-retry :write-transform-retry))
      (test-transform mode))
    (format t "~&BARRIER-CLAIM-SUMMARY cases=~D failures=~D failed-worlds=~D retained-total=~D~%"
            *cases* *failures* (- (length *failed-worlds*) old-failed)
            (length *failed-worlds*))
    (check (= *cases* 20) "Public claim/transform matrix changed: ~D" *cases*)
    (check (zerop *failures*) "Independent public claim/transform proofs failed")))
