;;;; Hosted opaque-reservation admission histories.
;;;; Based on the unchanged independent 34-case baseline; no load-time runner.
;;;; Tests structural checks and real execution, not full method-domain or
;;;; Mezzano admission. Retained owners survive repeated test invocations.
(defpackage #:clamsara.quality.barrier-admission
  (:use #:cl #:clamsara #:clamsara.quality.support)
  (:export #:run-opaque-admission-tests #:*failed-worlds* #:*rejected-builds*))
(in-package #:clamsara.quality.barrier-admission)

(define-condition proof-fault (error) ())
(defclass private-token ()
  ((owner :initarg :owner :reader token-owner)
   (active-p :initform nil :accessor token-active-p)))
(defclass private-token-child (private-token) ())
(defclass rule ()
  ((token :accessor rule-token)
   (token-class :initarg :token-class :initform 'private-token :reader rule-token-class)
   (events :initform (list :read) :reader rule-events)
   (mode :initform nil :accessor rule-mode)
   (calls :initform (make-array 6 :initial-element 0) :reader rule-calls)
   (auxiliary-calls :initform (make-array 4 :initial-element 0) :reader rule-auxiliary-calls)
   (fault :initform (make-condition 'proof-fault) :reader rule-fault)))
(defmethod initialize-instance :after ((r rule) &key)
  (setf (rule-token r) (make-instance (rule-token-class r) :owner r)))
(defmethod describe-barrier-contribution ((r rule))
  (values (class-name (class-of r)) (copy-list (rule-events r)) nil
          t nil nil nil :transform :retry-before-exposure/fatal-after))

(defclass proof-plan (clamsara::semispace-plan)
  ((rules :initarg :rules :reader plan-rules)))
(defmethod component-barrier-contributions ((p proof-plan))
  (copy-list (plan-rules p)))
(defmethod clamsara::map-construction-auxiliary-storage ((p proof-plan) f)
  (call-next-method)
  (clamsara::%map-construction-cons-storage (plan-rules p) f)
  (dolist (r (plan-rules p))
    (funcall f r) (funcall f (rule-token r)) (funcall f (rule-fault r))
    (funcall f (rule-calls r)) (funcall f (rule-auxiliary-calls r))
    (clamsara::%map-construction-cons-storage (rule-events r) f))
  (values))
(defvar *rule* nil)
(defvar *last-plan* nil)
(defvar *cases* 0)
(defvar *failures* 0)
(defvar *failed-worlds* nil)
(defvar *rejected-builds* nil)
(defun configure-plan (plan)
  (check (typep plan 'clamsara::semispace-plan) "Expected real SemiSpace plan")
  (change-class plan 'proof-plan :rules (list *rule*))
  (setf *last-plan* plan))

(defun reserve-token (r)
  (when (token-active-p (rule-token r))
    (return-from reserve-token (values nil :retry)))
  (setf (token-active-p (rule-token r)) t)
  (incf (aref (rule-calls r) 0))
  (values (rule-token r) :ready))
(defun perform-phase (r token phase &optional candidate)
  ;; The author inspects ONLY its own token. It contains no location or
  ;; managed reference; its owner is this host-side contribution object.
  (unless (and (eq token (rule-token r)) (eq (token-owner token) r)
               (token-active-p token))
    (error (rule-fault r)))
  (incf (aref (rule-calls r) phase))
  (case phase
    (1 :complete)
    (2 (if (eq (rule-mode r) :retry-transform)
           (values nil :retry) (values candidate :complete)))
    (3 (values))
    ((4 5) (setf (token-active-p token) nil) (values))
    (otherwise (error (rule-fault r)))))

;; Generate distinct classes and their own methods. RULE itself has NO barrier
;; execution methods. There is NO broad reservation fallback for a typed phase.
(defmacro define-rule (name &key typed missing eql-read wrong-event auxiliary-only)
  (let ((forms (list `(defclass ,name (rule) ())))
        (phases '(:reserve :admit :transform :before :after :cancel)))
    (dolist (phase phases)
      (unless (eq phase missing)
        (let* ((generic (ecase phase
                          (:reserve 'barrier-contribution-reserve)
                          (:admit 'barrier-contribution-admit)
                          (:transform 'barrier-contribution-transform)
                          (:before 'barrier-contribution-before-exposure)
                          (:after 'barrier-contribution-after-exposure)
                          (:cancel 'barrier-contribution-cancel)))
               (reservation (if (or (eq typed :all) (eq typed phase))
                                '(reservation private-token) 'reservation))
               (operation (cond ((eq wrong-event phase) '(operation (eql :store)))
                                (eql-read '(operation (eql :read)))
                                (t 'operation)))
               (qualifier (when (and auxiliary-only (eq phase :admit))
                            (list auxiliary-only)))
               (arguments
                 (ecase phase
                   (:reserve `((r ,name) context ,operation location))
                   (:admit `((r ,name) ,reservation context ,operation location))
                   ((:transform :before :after)
                    `((r ,name) ,reservation context ,operation location old value))
                   (:cancel `((r ,name) ,reservation))))
               (ignored (case phase
                          (:cancel nil)
                          ((:transform :before :after) '(context operation location old))
                          (otherwise '(context operation location))))
               (body
                 (ecase phase
                   (:reserve '(reserve-token r))
                   (:admit '(perform-phase r reservation 1))
                   (:transform '(perform-phase r reservation 2 value))
                   (:before '(perform-phase r reservation 3 value))
                   (:after '(perform-phase r reservation 4 value))
                   (:cancel '(perform-phase r reservation 5)))))
          (push `(defmethod ,generic ,@qualifier ,arguments
                   ,@(when ignored `((declare (ignore ,@ignored))))
                   ,body)
                forms))))
    `(progn ,@(nreverse forms))))

(define-rule broad-rule)
(define-rule typed-admit-rule :typed :admit)
(define-rule typed-transform-rule :typed :transform)
(define-rule typed-before-rule :typed :before)
(define-rule typed-after-rule :typed :after)
(define-rule typed-cancel-rule :typed :cancel)
(define-rule typed-all-rule :typed :all)
(define-rule typed-eql-read-rule :typed :all :eql-read t)
(define-rule observe-no-transform-rule :typed :all :missing :transform)
(defmethod describe-barrier-contribution ((r observe-no-transform-rule))
  (values (class-name (class-of r)) (copy-list (rule-events r)) nil
          t nil nil nil :observe :retry-before-exposure/fatal-after))
(define-rule missing-reserve-rule :missing :reserve)
(define-rule missing-admit-rule :missing :admit)
(define-rule missing-transform-rule :missing :transform)
(define-rule missing-before-rule :missing :before)
(define-rule missing-after-rule :missing :after)
(define-rule missing-cancel-rule :missing :cancel)
(define-rule wrong-reserve-event-rule :wrong-event :reserve)
(define-rule wrong-admit-event-rule :wrong-event :admit)
(define-rule wrong-transform-event-rule :wrong-event :transform)
(define-rule wrong-before-event-rule :wrong-event :before)
(define-rule wrong-after-event-rule :wrong-event :after)
;; Standard combination needs an applicable primary. Auxiliary presence alone
;; is not a successful execution method, even if the NIL probe finds it.
(define-rule before-only-rule :auxiliary-only :before)
(define-rule after-only-rule :auxiliary-only :after)
(define-rule around-only-rule :auxiliary-only :around)
(define-rule combined-rule :typed :all)
(defmethod barrier-contribution-admit :before
    ((r combined-rule) (reservation private-token) context operation location)
  (declare (ignore reservation context operation location))
  (incf (aref (rule-auxiliary-calls r) 0)))
(defmethod barrier-contribution-admit :after
    ((r combined-rule) (reservation private-token) context operation location)
  (declare (ignore reservation context operation location))
  (incf (aref (rule-auxiliary-calls r) 1)))
(defmethod barrier-contribution-admit :around
    ((r combined-rule) (reservation private-token) context operation location)
  (declare (ignore reservation context operation location))
  (incf (aref (rule-auxiliary-calls r) 2))
  (multiple-value-prog1 (call-next-method)
    (incf (aref (rule-auxiliary-calls r) 3))))

(defun assert-never-executed (r)
  (check (every #'zerop (rule-calls r)) "Construction executed an authored barrier method")
  (check (every #'zerop (rule-auxiliary-calls r)) "Construction ran method-combination effects")
  (check (not (token-active-p (rule-token r))) "Construction reserved a private token"))
(defun invoke-read (world source)
  (let ((index 0) (found nil) (value nil) (status nil))
    (map-reference-locations
     (world-model world) source
     (lambda (identity location)
       (declare (ignore identity))
       (when (= index 1)
         (setf found t)
         (multiple-value-setq (value status)
           (barrier-read (configuration-barrier (world-configuration world))
                         (world-context world) location)))
       (incf index)))
    (check found "No real managed reference location")
    (values value status)))
(defun raw-left (world source)
  (let ((index 0) (found nil) (value nil))
    (map-reference-locations
     (world-model world) source
     (lambda (identity location)
       (declare (ignore identity))
       (when (= index 1)
         (setf found t value (load-reference (world-model world) location :acquire)))
       (incf index)))
    (check found "No raw source slot")
    value))
(defun invoke-and-check (world source old retry-p combined-p)
  (let* ((raw-counts (make-array 2 :initial-element 0))
         (clamsara.quality.support::*reference-operation-observer*
           (lambda (kind) (ecase kind
                            (:load (incf (aref raw-counts 0)))
                            (:store (incf (aref raw-counts 1)))))))
    (multiple-value-bind (value status) (invoke-read world source)
      (check (if retry-p (and (null value) (eq status :retry))
                 (and (eq value old) (eq status :complete)))
             "Wrong real read result/status: ~S/~S" value status))
    (check (equalp raw-counts #(1 0)) "Read/transform retry did not do exactly one raw load"))
  (check (eq (raw-left world source) old) "Read or retry changed the real slot")
  (check (equalp (rule-calls *rule*)
                 (cond (retry-p #(1 1 1 0 0 1))
                       ((typep *rule* 'observe-no-transform-rule) #(1 1 0 1 1 0))
                       (t #(1 1 1 1 1 0))))
         "Required token-specialized phases did not complete/settle exactly once: ~S" (rule-calls *rule*))
  (check (equalp (rule-auxiliary-calls *rule*) (if combined-p #(1 1 1 1) #(0 0 0 0)))
         "Method-combination control did not run exact auxiliaries")
  (check (not (token-active-p (rule-token *rule*))) "Reservation not consumed/canceled")
  (check (zerop (clamsara::%plan-barrier-pin-count (world-plan world))) "Entry leaked a plan pin")
  (check (eq (clamsara::%context-barrier-state (world-context world)) :idle) "Context not idle"))

(defun check-rejection (condition observation)
  (check (typep condition 'clamsara::construction-rejected) "Missing method published instead of rejecting")
  (check (eq (clamsara::construction-rejection-reason condition) :barrier-composition-signaled)
         "Wrong outer rejection")
  (let ((cause (clamsara::construction-rejection-cause condition))
        (construction (observed-construction observation)))
    (check (and (typep cause 'clamsara::runtime-rejection)
                (eq (clamsara::runtime-rejection-reason cause) :missing-barrier-execution-method))
           "Missing/event-incompatible/non-primary method has wrong complaint")
    (check (clamsara::construction-rejection-paths condition) "Missing contributor path")
    (check construction "No real acquired construction observed")
    (let ((configuration (clamsara::construction-configuration construction)))
      (check (eq (clamsara::%configuration-state configuration) :failed) "Rejected configuration published")
      (check (not (clamsara::%configuration-barrier-bound-p configuration)) "Method check ran after barrier binding")
      (check (eq (clamsara::%context-state construction) :released) "Rejected construction did not unwind")
      (check (plusp (length (clamsara::%context-transaction-log construction))) "No actual resource transaction")
      (check (every #'clamsara::%transaction-entry-released-p
                    (clamsara::%context-transaction-log construction)) "Acquisition unwind incomplete")))
  (assert-never-executed *rule*))

(defun one (class mode &key reject (token-class 'private-token))
  (incf *cases*)
  (let* ((*rule* (make-instance class :token-class token-class)) (*last-plan* nil)
         (*construction-observation* (make-construction-observation))
         (world nil) (construction-error nil) (label (list class mode token-class)))
    (handler-case
        (progn
          (handler-case (setf world (make-quality-world :configure-plan #'configure-plan))
            (clamsara::construction-rejected (condition) (setf construction-error condition)))
          (if reject
              (progn
                (check-rejection construction-error *construction-observation*)
                ;; Retain the real, fully unwound construction as diagnostic evidence.
                (push (list label *last-plan* *rule* *construction-observation* construction-error)
                      *rejected-builds*))
              (progn
                (check (null construction-error) "Valid own-token contributor rejected: ~A" construction-error)
                (check world "No real published fixture")
                (assert-never-executed *rule*)
                (let ((source (allocate-node world 801)) (old (allocate-node world 802)))
                  (set-world-root world 0 source) (set-world-root world 1 old)
                  (set-node-slot world source 1 old)
                  (setf (rule-mode *rule*) mode)
                  (let ((outcome
                          (catch 'clamsara::simulator-fatal
                            (invoke-and-check world source old (eq mode :retry-transform)
                                              (eq class 'combined-rule))
                            :complete)))
                    (check (eq outcome :complete) "Unexpected fatal escape: ~S" outcome))
                  ;; Exercise cancellation reuse through the same private token.
                  (when (eq mode :retry-transform)
                    (fill (rule-calls *rule*) 0) (fill (rule-auxiliary-calls *rule*) 0)
                    (setf (rule-mode *rule*) nil)
                    (invoke-and-check world source old nil (eq class 'combined-rule))))
                ;; The managed entry bindings end before this real collection.
                (setf (rule-mode *rule*) nil)
                (let ((result (collect-world world)))
                  (check (eq (cycle-result-status result) :complete) "Real post-entry GC did not complete"))
                (let ((snapshot (snapshot-world-graph world)))
                  (check (equal (second snapshot) '((801 802 nil) (802 nil nil)))
                         "Rooted managed graph changed"))
                (close-quality-world world)))
          (format t "~&OPAQUE-ADMISSION-PASS ~S~%" label))
      (error (condition)
        (incf *failures*)
        ;; Never erase a failed owner or force a fatal world closed.
        (push (list label world *last-plan* *rule* *construction-observation* condition)
              *failed-worlds*)
        (format t "~&OPAQUE-ADMISSION-FAIL ~S [~S] ~A~%" label (type-of condition) condition)))))

(defun run-opaque-admission-tests ()
  (let ((*cases* 0) (*failures* 0)
        (previous-failed (length *failed-worlds*))
        (previous-rejected (length *rejected-builds*)))
    (dolist (mode '(nil :retry-transform)) (one 'broad-rule mode))
    (dolist (class '(typed-admit-rule typed-transform-rule typed-before-rule
                     typed-after-rule typed-cancel-rule typed-all-rule typed-eql-read-rule))
      (dolist (mode '(nil :retry-transform)) (one class mode)))
    (one 'typed-all-rule nil :token-class 'private-token-child)
    (one 'observe-no-transform-rule nil)
    (dolist (class '(missing-reserve-rule missing-admit-rule missing-transform-rule
                     missing-before-rule missing-after-rule missing-cancel-rule
                     wrong-reserve-event-rule wrong-admit-event-rule wrong-transform-event-rule
                     wrong-before-event-rule wrong-after-event-rule
                     before-only-rule after-only-rule around-only-rule))
      (one class :reject :reject t))
    (dolist (mode '(nil :retry-transform)) (one 'combined-rule mode))
    (format t "~&OPAQUE-ADMISSION-SUMMARY cases=~D failures=~D new-failed=~D new-rejected=~D retained-failed=~D retained-rejected=~D~%"
            *cases* *failures* (- (length *failed-worlds*) previous-failed)
            (- (length *rejected-builds*) previous-rejected)
            (length *failed-worlds*) (length *rejected-builds*))
    (check (= *cases* 34) "Opaque admission matrix changed: ~D" *cases*)
    (check (zerop *failures*) "Opaque admission acceptance failures: ~D" *failures*)))
