;;;; Hosted shared-copy graph and failure regressions.
;;;; Independent original: docs/evidence/shared-copy-04bff62/regression-source/.
;;;; Private-action preservation only, not full protocol or target conformance.
(defpackage #:clamsara.quality.copy-action
  (:use #:cl #:clamsara #:clamsara.quality.support)
  (:export #:run-focused-copy-tests #:run-copy-action-tests #:*copy-owners*))
(in-package #:clamsara.quality.copy-action)

(defstruct copy-owner name world (phase :created) condition result
  fault-at (copies 0) (inits 0) last-init-address
  (copy-events nil) (raw-allocators nil) (cancelled-allocators nil)
  source destination before-graph before-allocators before-starts before-context-allocator
  (injected-p nil))
(defvar *copy-owners* nil)
(defvar *active-copy-owner* nil)
(define-condition injected-copy-failure (error) ())

(defun cycle-of (o) (clamsara::%plan-cycle (world-plan (copy-owner-world o))))
(defun owner-model-p (o model) (eq model (world-model (copy-owner-world o))))
(defun space-starts (space)
  (let ((result nil))
    (metadata-map-present (clamsara::%space-object-start-map space)
                          (clamsara::%space-range space)
                          (lambda (address bit)
                            (check (= bit 1) "Non-start bit at ~D" address)
                            (push address result)))
    (sort result #'<)))
(defun start-snapshot (world)
  (loop for space in (clamsara::%plan-spaces (world-plan world))
        collect (list space (space-starts space))))
(defun forwarding-entries (space)
  (let ((result nil))
    (metadata-map-present (clamsara::%space-forwarding space)
                          (clamsara::%space-range space)
                          (lambda (address reference) (push (cons address reference) result)))
    (sort result #'< :key #'car)))
(defun allocator-state (allocator)
  ;; Only ownership-relevant fields. Inactive last-cursor/last-index scratch is
  ;; not required to roll back to a previous value after ownership is canceled.
  (etypecase allocator
    (clamsara::bump-runtime-allocator
      (list :bump (clamsara::%allocator-cursor allocator)
            (clamsara::%allocator-limit allocator)
            (clamsara::%allocator-last-valid-p allocator)))
    (clamsara::free-list-runtime-allocator
      (let ((count (clamsara::%free-count allocator)))
        (list :free-list count
              (loop for i below count collect (aref (clamsara::%free-starts allocator) i))
              (loop for i below count collect (aref (clamsara::%free-limits allocator) i))
              (clamsara::%allocator-last-valid-p allocator))))))
(defun allocation-snapshot (world)
  (loop for space in (clamsara::%plan-spaces (world-plan world))
        collect (list space (clamsara::%space-allocator space)
                      (allocator-state (clamsara::%space-allocator space)))))
(defun same-allocation-state-p (left right)
  (and (= (length left) (length right))
       (every (lambda (a b)
                (and (eq (first a) (first b)) (eq (second a) (second b))
                     (equal (third a) (third b)))) left right)))

(defun copy-completed-observer (model source destination)
  (let* ((o *active-copy-owner*) (cycle (cycle-of o))
         (address (copy-owner-last-init-address o))
         (source-address (reference-address model source)))
    (incf (copy-owner-copies o))
    (check (= (copy-owner-copies o) (copy-owner-inits o))
           "Expected exactly one genuine destination initialization per copy")
    (check (and address
                (<= (clamsara::%space-base (copy-owner-destination o)) address)
                (< address (clamsara::%space-limit (copy-owner-destination o))))
           "Copy initialized outside its real destination")
    ;; The real COPY primary has run, but this action has not yet published
    ;; the destination's authoritative start or its source forwarding edge.
    (check (zerop (metadata-ref
                   (clamsara::%space-object-start-map (copy-owner-destination o)) address))
           "Authoritative destination start preceded completed copy return")
    (check (null (metadata-ref (clamsara::%space-forwarding (copy-owner-source o))
                              source-address))
           "This source forwarding preceded completed copy return")
    (push (list :source source :destination destination :source-address source-address
                :destination-address address
                :earlier-forwarding (clamsara::%cycle-forwarding-published-p cycle)
                :movement-count (clamsara::%cycle-movement-count cycle)
                :allocator (allocator-state
                             (clamsara::%space-allocator (copy-owner-destination o))))
          (copy-owner-copy-events o))
    (when (= (copy-owner-copies o) (copy-owner-fault-at o))
      (setf (copy-owner-injected-p o) t)
      (error 'injected-copy-failure))))

(defun with-unique-method (generic qualifiers classes definition thunk)
  (assert (null (find-method generic qualifiers (mapcar #'find-class classes) nil)))
  (let ((method (eval definition)))
    ;; Removing our method is NOT cleanup of a failed configuration.
    (unwind-protect (funcall thunk) (remove-method generic method))))
(defun with-copy-observers (thunk)
  (labels ((install (specs)
             (if (null specs) (funcall thunk)
                 (destructuring-bind (name qualifiers classes definition) (car specs)
                   (with-unique-method (fdefinition name) qualifiers classes definition
                     (lambda () (install (cdr specs))))))))
    (install
     '((initialize-object (:before) (clamsara::host-bound-object-model t t t t)
        (defmethod initialize-object :before
            ((model clamsara::host-bound-object-model) address kind bytes descriptor)
          (declare (ignore kind bytes descriptor))
          (when (and *active-copy-owner* (owner-model-p *active-copy-owner* model))
            (incf (copy-owner-inits *active-copy-owner*))
            (setf (copy-owner-last-init-address *active-copy-owner*) address))))
       (copy-object-representation (:after) (clamsara::host-bound-object-model t t)
        (defmethod copy-object-representation :after
            ((model clamsara::host-bound-object-model) source destination)
          (when (and *active-copy-owner* (owner-model-p *active-copy-owner* model))
            (copy-completed-observer model source destination))))
       (allocate-raw (:before) (clamsara::runtime-allocator t t t)
        (defmethod allocate-raw :before
            ((allocator clamsara::runtime-allocator) bytes alignment kind)
          (declare (ignore bytes alignment kind))
          (when *active-copy-owner*
            (push allocator (copy-owner-raw-allocators *active-copy-owner*)))))
       (clamsara::%cancel-raw-allocation (:before) (clamsara::runtime-allocator)
        (defmethod clamsara::%cancel-raw-allocation :before
            ((allocator clamsara::runtime-allocator))
          (when *active-copy-owner*
            (push allocator (copy-owner-cancelled-allocators *active-copy-owner*)))))))))

(defun with-owned-world (name constructor action)
  (let ((o (make-copy-owner :name name)))
    (push o *copy-owners*)
    (handler-case
        (progn
          (setf (copy-owner-world o) (funcall constructor)
                (copy-owner-phase o) :ready)
          (funcall action o)
          o)
      (error (c)
        (setf (copy-owner-condition o) c (copy-owner-phase o) :unexpected-failure-retained)
        ;; No root erasure, collection, unbind or shutdown on this path.
        (error c)))))
(defun new-world (mode starts)
  (if (eq mode :semispace)
      (make-quality-world :algorithm :semispace :object-starts starts
                          :extent 256 :root-count 4 :trace-capacity 32)
      (clamsara.quality.generational::make-generation-world
        :object-starts starts :nursery-extent 256 :mature-extent 1024 :root-count 4)))
(defun record-count-is (record name expected)
  (multiple-value-bind (value known) (cycle-result-count record name)
    (check (and known (= value expected)) "~S expected ~D, got ~S/~S"
           name expected value known)))
(defun complete-cycle (o scope moved dead)
  (let ((r (collect-world (copy-owner-world o) :scope scope)))
    (setf (copy-owner-result o) r)
    (check (eq :complete (cycle-result-status r)) "Expected complete cycle, got ~S/~S"
           (cycle-result-status r) (cycle-result-reason r))
    (record-count-is r :objects-moved moved)
    (record-count-is r :bytes-moved (* 32 moved))
    (record-count-is r :objects-dead dead)
    r))
(defun check-graph (world expected)
  (check-equal expected (snapshot-world-graph world) "independent ID graph"))
(defun real-node-addresses (world)
  (multiple-value-bind (graph pairs) (snapshot-world-graph world)
    (declare (ignore graph))
    (loop for (id . reference) in pairs
          collect (cons id (reference-address (world-model world) reference)))))
(defun get-node (world id)
  (multiple-value-bind (graph pairs) (snapshot-world-graph world)
    (declare (ignore graph))
    (or (cdr (assoc id pairs)) (error "No real managed node ~D" id))))
(defun check-moved-addresses (before after)
  (check (= (length before) (length after)) "Address oracle length changed")
  (dolist (row before)
    (check (and (assoc (car row) after) (/= (cdr row) (cdr (assoc (car row) after))))
           "Node ~D did not really move" (car row))))

(defun build-shared-cycle (world)
  (let ((a (allocate-node world 1)))
    (set-world-root world 0 a)
    (set-world-root world 1 a)
    (let ((b (allocate-node world 2)))
      (set-world-root world 3 b)
      (let ((c (allocate-node world 3)))
        (set-world-root world 2 c)
        ;; Every object already has a registered real root before graph writes.
        (set-node-slot world a 1 b) (set-node-slot world a 2 c)
        (set-node-slot world b 1 a) (set-node-slot world b 2 c)
        (set-node-slot world c 1 c)
        (set-world-root world 3 nil))))
  (allocate-node world 99) ; genuine unreachable allocation, not a counter edit
  '((1 1 3 nil) ((1 2 3) (2 1 3) (3 3 nil))))

(defun run-semispace-graph (starts)
  (with-owned-world (list :semispace-shared-cycle starts)
    (lambda () (new-world :semispace starts))
    (lambda (o)
      (let* ((w (copy-owner-world o)) (expected (build-shared-cycle w)))
        (check-graph w expected)
        (dotimes (round 2)
          (let ((before (real-node-addresses w)))
            (complete-cycle o :all 3 (if (zerop round) 1 0))
            (check-graph w expected)
            (check-moved-addresses before (real-node-addresses w))
            (check (= 3 (loop for s in (clamsara::%plan-spaces (world-plan w))
                             sum (length (space-starts s))))
                   "Unexpected authoritative starts after successful copy")))
        (close-quality-world w) ; success only; all roots belong to this case
        (setf (copy-owner-phase o) :complete)))))

(defun run-generational-graph (starts)
  (with-owned-world (list :minor-major-shared-cycles starts)
    (lambda () (new-world :minor starts))
    (lambda (o)
      (let* ((w (copy-owner-world o)) (initial (build-shared-cycle w))
             (young-addresses (real-node-addresses w)))
        (complete-cycle o :minor 3 1)
        (check-graph w initial)
        (check-moved-addresses young-addresses (real-node-addresses w))
        (let ((mature-addresses (real-node-addresses w)))
          (dolist (id '(1 2 3))
            (check (clamsara.quality.generational::mature-p w (get-node w id))
                   "Minor did not promote ~D" id))
          ;; New young two-node cycle shares already-promoted objects.
          (let ((e (allocate-node w 5)))
            (set-world-root w 3 e)
            (let ((f (allocate-node w 6)))
              (set-node-slot w e 1 f) (set-node-slot w e 2 (get-node w 1))
              (set-node-slot w f 1 e) (set-node-slot w f 2 (get-node w 3))
              (set-node-slot w (get-node w 1) 2 e)))
          (allocate-node w 100)
          (let* ((expected '((1 1 3 5) ((1 2 5) (2 1 3) (3 3 nil) (5 6 1) (6 5 3))))
                 (before-major (real-node-addresses w)))
            (complete-cycle o :all 2 1)
            (check-graph w expected)
            (dolist (row mature-addresses)
              (check (= (cdr row) (cdr (assoc (car row) (real-node-addresses w))))
                     "Major moved a mature object"))
            (dolist (id '(5 6))
              (check (not (clamsara.quality.generational::mature-p w (get-node w id)))
                     "Major promoted young object instead of nursery copying")
              (check (/= (cdr (assoc id before-major))
                         (reference-address (world-model w) (get-node w id)))
                     "Major did not copy young object"))
            ;; No intervening payload/root store can repair forgotten state.
            (let ((before-minor (real-node-addresses w)))
              (complete-cycle o :minor 2 0)
              (check-graph w expected)
              (dolist (id '(5 6))
                (check (clamsara.quality.generational::mature-p w (get-node w id))
                       "Following minor did not promote young cycle")
                (check (/= (cdr (assoc id before-minor))
                           (reference-address (world-model w) (get-node w id)))
                       "Following minor did not really move young object")))
            (dolist (row mature-addresses)
              (check (= (cdr row) (cdr (assoc (car row) (real-node-addresses w))))
                     "Minor changed an established mature address"))))
        (close-quality-world w)
        (setf (copy-owner-phase o) :complete)))))

(defun select-copy-spaces (o mode)
  (let* ((w (copy-owner-world o)) (p (world-plan w))
         (source (find-if (lambda (space)
                           (and (typep space 'clamsara::semispace-space)
                                (eq :allocation (clamsara::%semispace-role space))))
                         (clamsara::%plan-spaces p)))
         (destination (if (eq mode :minor) (clamsara::%gen-mature p)
                          (clamsara::%semispace-partner source))))
    (check source "Missing actual allocation source")
    (setf (copy-owner-source o) source (copy-owner-destination o) destination)))
(defun build-fault-cycle (w)
  (let ((a (allocate-node w 1)))
    (set-world-root w 0 a)
    (let ((b (allocate-node w 2)))
      (set-world-root w 1 b)
      (set-node-slot w a 1 b) (set-node-slot w b 1 a)
      (set-world-root w 1 nil)))
  '((1 nil nil nil) ((1 2 nil) (2 1 nil))))

(defun check-first-failure (o mode)
  (let* ((w (copy-owner-world o)) (p (world-plan w)) (r (copy-owner-result o))
         (source (copy-owner-source o)) (destination (copy-owner-destination o))
         (event (first (copy-owner-copy-events o))))
    (check (and (eq :retained (cycle-result-status r))
                (eq :preflight-failed (cycle-result-reason r)))
           "Pre-forwarding copy fault outcome changed: ~S/~S"
           (cycle-result-status r) (cycle-result-reason r))
    (check (eq :open (clamsara::%plan-state p)) "Pre-forwarding fault did not reopen plan")
    (check (eq :released (clamsara::simulator-stop-state (world-coordinator w)))
           "Pre-forwarding fault did not release stop")
    (check (not (clamsara::%cycle-forwarding-published-p (cycle-of o)))
           "Failed first copy published forwarding")
    (check (null (forwarding-entries source)) "Forwarding escaped failed first copy")
    (check (= 2 (length (space-starts source))) "Source authoritative starts changed")
    (check (null (space-starts destination)) "Leaked authoritative destination start")
    (check (equal (copy-owner-before-starts o) (start-snapshot w))
           "First-copy fault changed authoritative starts in some space")
    (check (same-allocation-state-p (copy-owner-before-allocators o) (allocation-snapshot w))
           "Allocator ownership/frontier leaked across first-copy fault")
    (check-graph w (copy-owner-before-graph o))
    ;; Read-only host representation oracle. Retirement is a DEFUN, not a
    ;; generic seam: never replace it or pretend a method can observe it.
    (check (= 2 (clamsara::host-model-live-count (world-model w)))
           "Failed copy leaked a live representation")
    (check (not (clamsara::%host-descriptor-active-p
                  (world-model w)
                  (clamsara::host-reference-descriptor (getf event :destination))))
           "Failed copy destination descriptor remains active")
    (check (stale-reference-p w (getf event :destination))
           "Failed destination remains publicly valid")
    (if (eq mode :minor)
        (progn
          (check (null (copy-owner-raw-allocators o)) "Minor unexpectedly borrowed raw allocator")
          (check (null (copy-owner-cancelled-allocators o))
                 "Minor canceled allocator reservation it did not own"))
        (progn
          (check (= 1 (length (copy-owner-raw-allocators o))) "Missing real copy allocation")
          (check (= 1 (length (copy-owner-cancelled-allocators o))) "Copy allocation not canceled once")
          (check (eq (first (copy-owner-raw-allocators o)) (clamsara::%space-allocator destination))
                 "Wrong allocating owner")
          (check (eq (first (copy-owner-cancelled-allocators o)) (clamsara::%space-allocator destination))
                 "Canceled wrong allocator owner")))
    (record-count-is r :objects-moved 0) (record-count-is r :bytes-moved 0)
    (record-count-is r :objects-discovered 0) (record-count-is r :objects-dead 0)))

(defun check-second-failure (o mode)
  (let* ((w (copy-owner-world o)) (p (world-plan w)) (r (copy-owner-result o))
         (source (copy-owner-source o)) (destination (copy-owner-destination o))
         (events (reverse (copy-owner-copy-events o)))
         (first (first events)) (second (second events))
         (forward (forwarding-entries source)))
    (check (and (eq :retained (cycle-result-status r))
                (eq :post-publication-failure (cycle-result-reason r)))
           "Second copy fault after earlier publication was not retained")
    (check (and (eq :retained (clamsara::%plan-state p))
                (eq :covered (clamsara::simulator-stop-state (world-coordinator w))))
           "Published-copy failure resumed the heap")
    (check (and (not (getf first :earlier-forwarding)) (getf second :earlier-forwarding))
           "Failure did not occur after an earlier genuine publication")
    (check (= 1 (getf second :movement-count)) "Earlier copy was not recorded")
    (check (= 1 (length forward)) "Expected exactly the earlier forwarding edge")
    (check (and (= (caar forward) (getf first :source-address))
                (eq (cdar forward) (getf first :destination)))
           "Earlier forwarding identity changed")
    (check (null (assoc (getf second :source-address) forward))
           "Failed second copy published its own forwarding")
    (check (equal (space-starts destination) (list (getf first :destination-address)))
           "Destination authoritative starts disagree with publication")
    (check (= 2 (length (space-starts source))) "Retained sources were retired")
    (dolist (row (copy-owner-before-starts o))
      (unless (eq (first row) destination)
        (check (equal (second row) (space-starts (first row)))
               "Post-publication failure altered another space's starts")))
    ;; Retained scratch is not a rollback success. Do not cancel or reuse it.
    (check (null (copy-owner-cancelled-allocators o)) "Post-publication failure canceled ownership")
    (check (= 4 (clamsara::host-model-live-count (world-model w)))
           "Post-publication failure did not retain all four real representations")
    (dolist (event events)
      (dolist (key '(:source :destination))
        (check (clamsara::%host-descriptor-active-p
                 (world-model w) (clamsara::host-reference-descriptor (getf event key)))
               "Post-publication failure retired a retained representation")))
    (if (eq mode :minor)
        (check (null (copy-owner-raw-allocators o)) "Promotion borrowed raw allocation")
        (progn
          (check (= 2 (length (copy-owner-raw-allocators o))) "Expected two actual copy reservations")
          (check (every (lambda (a) (eq a (clamsara::%space-allocator destination)))
                        (copy-owner-raw-allocators o)) "Wrong destination reservation owner")
          (check (clamsara::%allocator-last-valid-p (clamsara::%space-allocator destination))
                 "Current retained copy reservation was silently released")))
    (record-count-is r :objects-moved 1) (record-count-is r :bytes-moved 32)
    (record-count-is r :objects-discovered 1) (record-count-is r :objects-dead 0)
    ;; Genuine ordinary operations reject; no fake trace claims or forwarding.
    (let ((fresh (make-cycle-result-record p)))
      (signals-runtime-reason
        (lambda () (collect (world-configuration w) :all :explicit fresh)) :collection-busy)
      (check (eq :uninitialized (cycle-result-status fresh)) "Rejected entry mutated report"))
    (signals-runtime-reason
      (lambda () (allocate-object (world-context w) :quality-node 32 16 (world-node-kind w)))
      :collection-busy)
    (check (eq :retry (unbind-mutator (world-configuration w) (world-context w)))
           "Retained state allowed mutator unbind")))

(defun run-copy-fault (mode starts ordinal)
  (with-owned-world (list :copy-fault mode starts ordinal)
    (lambda () (new-world mode starts))
    (lambda (o)
      (let ((w (copy-owner-world o)))
        (setf (copy-owner-fault-at o) ordinal
              (copy-owner-before-graph o) (build-fault-cycle w))
        (select-copy-spaces o mode)
        (check-graph w (copy-owner-before-graph o))
        (setf (copy-owner-before-allocators o) (allocation-snapshot w)
              (copy-owner-before-starts o) (start-snapshot w)
              (copy-owner-before-context-allocator o)
              (clamsara::%context-allocator (world-context w))
              (copy-owner-phase o) :collecting-injected-copy)
        (with-copy-observers
          (lambda ()
            (let ((*active-copy-owner* o))
              (setf (copy-owner-result o)
                    (collect-world w :scope (if (eq mode :minor) :minor :all))))))
        (check (and (copy-owner-injected-p o) (= ordinal (copy-owner-copies o)))
               "Required fault point was not reached")
        (ecase ordinal (1 (check-first-failure o mode)) (2 (check-second-failure o mode)))
        (check (eq (copy-owner-before-context-allocator o)
                   (clamsara::%context-allocator (world-context w)))
               "Copy failure changed the mutator's allocator owner")
        (check (eq :published (clamsara::%configuration-state (world-configuration w)))
               "Fault test destroyed its owner")
        (check (clamsara::simulator-provider-token-active-p (world-root-token w))
               "Fault test released its real root token")
        ;; Both recoverable and terminal failed cycles retain their real owners.
        ;; No close/collection/root erasure is used to manufacture a pass.
        (setf (copy-owner-phase o) :expected-copy-failure-owner-retained)))))

(defun run-focused-copy-tests ()
  ;; 16 small cases: 4 completed graph histories and 12 owned injected failures.
  ;; This is copy-action semantics, NOT full lifecycle/protocol composition.
  (let ((before (length *copy-owners*)))
    (dolist (starts '(:packed :scalar))
      (run-semispace-graph starts)
      (run-generational-graph starts)
      (dolist (mode '(:semispace :minor :major))
        (dolist (ordinal '(1 2)) (run-copy-fault mode starts ordinal))))
    (check (= 16 (- (length *copy-owners*) before)) "Focused matrix incomplete")
    (format t "~&COPY-ACTION-OBSERVED cases=16 completed=4 failed-cycle-owners-retained=12~%")
    t))

;;; Permanent entry checks each newly created group without erasing prior owners.
(defun run-copy-action-tests ()
  (let ((prior *copy-owners*))
    (run-focused-copy-tests)
    (let ((new (ldiff *copy-owners* prior)))
      (check (= 16 (length new) (count-if #'copy-owner-world new))
             "Copy-action group did not produce 16 real worlds")
      (check (= 4 (count :complete new :key #'copy-owner-phase))
             "Copy-action graph configurations did not complete")
      (check (= 12 (count :expected-copy-failure-owner-retained new
                          :key #'copy-owner-phase))
             "Copy-action group did not retain its twelve expected failed worlds")
      (check (zerop (count :unexpected-failure-retained new :key #'copy-owner-phase))
             "Copy-action group retained an unexpected failure")
      (format t "~&COPY-ACTION-PERMANENT-PASS new-worlds=16 complete-configurations=4 expected-failed-worlds-retained=12~%"))
    t))
