;;;; Adversarial callback histories. Native host callbacks are test controllers;
;;;; these tests do not claim managed callback representation/ABI admission.
(in-package #:clamsara.quality.finalizers)

(defun check-empty-registry (registry)
  (check (zerop (clamsara::%registry-pending-count registry)) "Pending work remained")
  (check (every (lambda (state) (eq state :free)) (clamsara::%registry-states registry))
         "Terminal records were not released")
  (check (every #'null (clamsara::%registry-referents registry)) "Terminal referent root remained")
  (check (every #'null (clamsara::%registry-callbacks registry)) "Terminal callback remained"))

(defun run-callback-exit (algorithm starts style)
  (let* ((world (make-quality-world :algorithm algorithm :object-starts starts
                                     :extent 512 :finalizer-capacity 2))
         (registry (world-registry world)) (context (world-context world))
         (calls 0) (last-reference nil) (reached-exit nil))
    (register-finalizer registry context (allocate-node world 71)
      (lambda (reference)
        (setf last-reference reference)
        (incf calls)
        (check-equal 71 (read-node-slot world reference 0) "callback referent")
        (setf reached-exit t)
        (ecase style
          (:normal :returned)
          (:error (error "Deliberate callback error"))
          (:throw (throw 'callback-exit :escaped)))))
    (complete-collection world)
    (let ((first (catch 'callback-exit (drain-pending-finalizers registry context)))
          (second (catch 'callback-exit (drain-pending-finalizers registry context))))
      (check (and (eql first (if (eq style :throw) :escaped 1))
                  (eql second 0) (= calls 1))
             "Callback ~S repeated or lost: returns=~S/~S calls=~D" style first second calls))
    ;; A contained assertion failure must not masquerade as the deliberately
    ;; raised ERROR merely because both increment the failure count once.
    (check reached-exit "Callback failed before its intended exit point")
    (check (= (if (eq style :normal) 0 1)
              (clamsara::%registry-callback-failure-count registry))
           "Callback completion/failure was not recorded")
    (check-empty-registry registry)
    (complete-collection world)
    (check (stale-reference-p world last-reference) "Terminal callback retained its referent")
    (close-quality-world world)))

(defun run-recursive-drain (algorithm starts)
  (let* ((world (make-quality-world :algorithm algorithm :object-starts starts
                                     :extent 512 :finalizer-capacity 2))
         (registry (world-registry world)) (context (world-context world))
         (calls nil) (recursed nil) (inner nil))
    (register-finalizer registry context (allocate-node world 1)
      (lambda (reference)
        (declare (ignore reference))
        (push :a calls)
        (unless recursed
          (setf recursed t inner (drain-pending-finalizers registry context)))))
    (register-finalizer registry context (allocate-node world 2)
      (lambda (reference) (declare (ignore reference)) (push :b calls)))
    (complete-collection world)
    (let ((outer (drain-pending-finalizers registry context)))
      (check (and (= outer 1) (eql inner 1) (equal (reverse calls) '(:a :b)))
             "Reentrant claims were not exclusive: outer=~S inner=~S calls=~S"
             outer inner (reverse calls)))
    (check (zerop (clamsara::%registry-callback-failure-count registry))
           "Unexpected recursive callback failure")
    (check-empty-registry registry)
    (close-quality-world world)))

(defun run-nested-publication (algorithm starts)
  (let* ((world (make-quality-world :algorithm algorithm :object-starts starts
                                     :extent 512 :finalizer-capacity 4))
         (registry (world-registry world)) (context (world-context world))
         (calls nil))
    ;; Advance a ring's head once so later publication must wrap with live work.
    (register-finalizer registry context (allocate-node world -1)
      (lambda (reference) (declare (ignore reference))))
    (complete-collection world)
    (check (= 1 (drain-pending-finalizers registry context)) "Prelude did not drain")
    (dotimes (iteration 10)
      (setf calls nil)
      (let ((a (allocate-node world 0)) (c (allocate-node world 1))
            (b (allocate-node world 2)) (d (allocate-node world 3)))
        (set-world-root world 0 b) (set-world-root world 1 d)
        (register-finalizer registry context a
          (lambda (reference)
            (declare (ignore reference))
            (push :a calls)
            (set-world-root world 0 nil) (set-world-root world 1 nil)
            (complete-collection world)))
        (register-finalizer registry context c
          (lambda (reference) (declare (ignore reference)) (push :c calls)))
        (register-finalizer registry context b
          (lambda (reference) (declare (ignore reference)) (push :b calls)))
        (register-finalizer registry context d
          (lambda (reference) (declare (ignore reference)) (push :d calls))))
      (complete-collection world)
      (let ((first (drain-pending-finalizers registry context)))
        (check (and (= first 2) (equal (reverse calls) '(:a :c))
                    (= 2 (clamsara::%registry-pending-count registry)))
               "Nested publication lost/order-mixed work: round=~D first=~S calls=~S pending=~D"
               iteration first (reverse calls) (clamsara::%registry-pending-count registry)))
      (check (= 2 (drain-pending-finalizers registry context)) "Newly pending batch lost")
      (check-equal '(:a :c :b :d) (reverse calls) "queue order across batches")
      (check (zerop (clamsara::%registry-callback-failure-count registry))
             "Nested collection callback failed")
      (check-empty-registry registry))
    (close-quality-world world)))

(defun run-callback-appends (algorithm starts)
  (let* ((world (make-quality-world :algorithm algorithm :object-starts starts
                                     :extent 512 :finalizer-capacity 2))
         (registry (world-registry world)) (context (world-context world))
         (calls 0))
    (labels ((callback (reference)
               (declare (ignore reference))
               (incf calls)
               (when (< calls 5)
                 (register-finalizer registry context (allocate-node world calls) #'callback)
                 (complete-collection world))))
      (register-finalizer registry context (allocate-node world 0) #'callback)
      (complete-collection world)
      (dotimes (index 5)
        (let ((drained (drain-pending-finalizers registry context)))
          (check (and (= drained 1) (= calls (1+ index)))
                 "Drain did not bound newly appended work: count=~D calls=~D round=~D"
                 drained calls index))))
    (check (zerop (clamsara::%registry-callback-failure-count registry)) "Append callback failed")
    (check-empty-registry registry)
    (close-quality-world world)))

(defun run-running-roots (algorithm starts)
  (let* ((world (make-quality-world :algorithm algorithm :object-starts starts
                                     :extent 512 :finalizer-capacity 2))
         (registry (world-registry world)) (context (world-context world))
         (parent (allocate-node world 10)) (child (allocate-node world 20))
         (token nil) (reached-end nil) (after nil))
    (set-node-slot world parent 1 child)
    (setf token
          (register-finalizer registry context parent
            (lambda (reference)
              (declare (ignore reference))
              (let ((index (clamsara::%registry-token-index registry token)))
                (check index "Running callback lost its current token identity")
                (complete-collection world)
                ;; Reload the actual corrected registry root. This does not
                ;; pretend an unregistered native Lisp local is a writable root.
                (setf after (aref (clamsara::%registry-referents registry) index))
                (check-equal 10 (read-node-slot world after 0))
                (check-equal 20 (read-node-slot world (read-node-slot world after 1) 0))
                (setf reached-end t)))))
    (complete-collection world)
    (check (= 1 (drain-pending-finalizers registry context)) "Running-root callback did not drain")
    (check (and reached-end (zerop (clamsara::%registry-callback-failure-count registry)))
           "Running referent/closure did not survive nested collection")
    (complete-collection world)
    (check (stale-reference-p world after) "Done callback retained closure")
    (close-quality-world world)))

(defun run-active-callback-context (algorithm starts)
  (let* ((world (make-quality-world :algorithm algorithm :object-starts starts
                                     :extent 512 :finalizer-capacity 2))
         (registry (world-registry world)) (context (world-context world))
         (unbind nil) (shutdown nil))
    (register-finalizer registry context (allocate-node world 1)
      (lambda (reference)
        (declare (ignore reference))
        (setf unbind (unbind-mutator (world-configuration world) context)
              shutdown (handler-case
                           (nth-value 0 (shutdown-configuration (world-configuration world)))
                         (clamsara::runtime-rejection (condition)
                           (clamsara::runtime-rejection-reason condition))))))
    (complete-collection world)
    (check (= 1 (drain-pending-finalizers registry context)) "Context callback did not drain")
    (check (and (eq unbind :retry) (eq shutdown :active-mutator-contexts)
                (eq :bound (clamsara::%context-state context)))
           "Callback lost its active context: unbind=~S shutdown=~S state=~S"
           unbind shutdown (clamsara::%context-state context))
    (check (zerop (clamsara::%registry-callback-failure-count registry)) "Context callback failed")
    (close-quality-world world)))

(defun run-throw-keeps-rest (algorithm starts)
  (let* ((world (make-quality-world :algorithm algorithm :object-starts starts
                                     :extent 512 :finalizer-capacity 3))
         (registry (world-registry world)) (context (world-context world))
         (a (allocate-node world 1)) (b (allocate-node world 2))
         (c (allocate-node world 3)) (calls nil) (old-token nil))
    (set-world-root world 0 c)
    (setf old-token
          (register-finalizer registry context a
            (lambda (reference)
              (declare (ignore reference))
              (push :a calls)
              (set-world-root world 0 nil)
              (complete-collection world)
              (throw 'nested-callback-exit :escaped))))
    (register-finalizer registry context b
      (lambda (reference)
        (declare (ignore reference))
        (push :b calls)
        (complete-collection world)))
    (register-finalizer registry context c
      (lambda (reference) (declare (ignore reference)) (push :c calls)))
    (complete-collection world)
    (check (eq :escaped (catch 'nested-callback-exit
                          (drain-pending-finalizers registry context)))
           "Callback nonlocal exit was hidden")
    (check (= 2 (clamsara::%registry-pending-count registry)) "Exit discarded other pending records")
    ;; Reuse A's freed physical slot while B/C remain queued. B's later
    ;; collection selects D; no old queue entry may invoke D as if it were A.
    (let ((new-token
            (register-finalizer registry context (allocate-node world 4)
              (lambda (reference) (declare (ignore reference)) (push :d calls)))))
      (cancel-finalizer registry context old-token)
      (check (find new-token (registrations registry) :key #'car) "Old A token canceled D")
      (check (= 2 (drain-pending-finalizers registry context)) "B/C did not drain")
      (check-equal '(:a :b :c) (reverse calls) "Old batch order after nonlocal exit")
      (check (= 1 (drain-pending-finalizers registry context)) "D was lost or invoked too early"))
    (check-equal '(:a :b :c :d) (reverse calls) "Callback identities across physical reuse")
    (check (= 1 (clamsara::%registry-callback-failure-count registry)) "Exit failure count")
    (check-empty-registry registry)
    (close-quality-world world)))

(defun run-recursive-throw (algorithm starts)
  (let* ((world (make-quality-world :algorithm algorithm :object-starts starts
                                     :extent 512 :finalizer-capacity 2))
         (registry (world-registry world)) (context (world-context world))
         (calls nil) (nested nil) (unbind nil) (entered nil))
    (register-finalizer registry context (allocate-node world 1)
      (lambda (reference)
        (declare (ignore reference))
        (push :a calls)
        (unless entered
          (setf entered t
                nested (catch 'recursive-exit (drain-pending-finalizers registry context))
                unbind (unbind-mutator (world-configuration world) context)))
        (push :a-return calls)))
    (register-finalizer registry context (allocate-node world 2)
      (lambda (reference)
        (declare (ignore reference))
        (push :b calls)
        (throw 'recursive-exit :escaped)))
    (complete-collection world)
    (check (= 1 (drain-pending-finalizers registry context)) "Outer invocation lost ownership")
    (check (and (eq nested :escaped) (eq unbind :retry)) "Nested exit lost outer context pin")
    (check-equal '(:a :b :a-return) (reverse calls) "Recursive nonlocal exit order")
    (check (= 1 (clamsara::%registry-callback-failure-count registry)) "Nested failure count")
    (check (zerop (clamsara::%context-finalizer-depth context)) "Context pin leaked after exit")
    (check-empty-registry registry)
    (close-quality-world world)))

(defun run-single-record-drain (algorithm starts)
  (let* ((world (make-quality-world :algorithm algorithm :object-starts starts
                                     :extent 512 :finalizer-capacity 1))
         (registry (world-registry world)) (context (world-context world))
         (calls 0))
    (dotimes (iteration 4)
      (register-finalizer registry context (allocate-node world iteration)
        (lambda (reference)
          (incf calls)
          (signals-runtime-reason
           (lambda () (register-finalizer registry context reference #'identity))
           :weak-storage-exhausted)))
      (complete-collection world)
      (check (= 1 (drain-pending-finalizers registry context)) "Capacity-one queue failed")
      (check (= (1+ iteration) calls) "Single record callback repeated")
      (check-empty-registry registry))
    (check (zerop (clamsara::%registry-callback-failure-count registry))
           "Running record was available for reuse")
    (check (= 4 (clamsara::%registry-next-token registry)) "Failed in-callback admission consumed history")
    (close-quality-world world)))

(defun run-callback-collection-failure (algorithm starts &optional (exit-style :return))
  (let* ((weak-kind nil)
         (world (make-quality-world
                 :algorithm algorithm :object-starts starts :extent 512
                 :finalizer-capacity 2 :conditional-capacity 0
                 :configure-model
                 (lambda (model)
                   (setf weak-kind
                         (make-object-kind-description
                          model :drain-weak :size-rule 16 :alignment-rule 16
                          :weak-descriptions
                          (list (make-weak-location-description
                                 model '(:identity :edge :offset 0) :leaf :cleared)))))))
         (registry (world-registry world)) (context (world-context world))
         (calls nil) (record nil) (token nil))
    (setf token
          (register-finalizer registry context (allocate-node world 1)
            (lambda (reference)
              (declare (ignore reference))
              (push :a calls)
              (multiple-value-bind (holder status reason)
                  (allocate-object context :drain-weak 16 16 weak-kind)
                (check (eq status :allocated) "Weak holder allocation failed: ~S" reason)
                (set-world-root world 0 holder))
              (setf record (collect-world world))
              (ecase exit-style
                (:return nil)
                (:throw (throw 'retained-callback-exit :escaped))
                (:error (error "Deliberate post-collection callback error"))))))
    (register-finalizer registry context (allocate-node world 2)
      (lambda (reference) (declare (ignore reference)) (push :b calls)))
    (complete-collection world)
    (let ((outcome
            (catch 'retained-callback-exit
              (handler-case (drain-pending-finalizers registry context)
                (clamsara::runtime-rejection (condition)
                  (clamsara::runtime-rejection-reason condition))))))
      (check (and record (eq :retained (cycle-result-status record))
                  (eq :weak-storage-exhausted (cycle-result-reason record)))
             "Nested failure setup did not reach conditional exhaustion")
      (if (eq algorithm :semispace)
          (progn
            (check (and (eq outcome (if (eq exit-style :throw) :escaped :collection-busy))
                        (equal (reverse calls) '(:a))
                        (= 1 (clamsara::%registry-pending-count registry))
                        (aref (clamsara::%registry-referents registry)
                              (clamsara::sequential-finalizer-token-index token)))
                   "Retained callback resumed/cleared roots: outcome=~S calls=~S pending=~D states=~S"
                   outcome (reverse calls) (clamsara::%registry-pending-count registry)
                   (clamsara::%registry-states registry))
            (check (eq :retained (clamsara::%plan-state (world-plan world))) "Retained plan reopened")
            (signals-runtime-reason (lambda () (drain-pending-finalizers registry context))
                                    :collection-busy)
            ;; Deliberately retain this irrecoverably closed fixture and its roots.
            (check (eq :retry (unbind-mutator (world-configuration world) context))
                   "Retained callback context escaped"))
          (progn
            (when (eq exit-style :throw)
              (check (and (eq outcome :escaped) (equal (reverse calls) '(:a))
                          (= 1 (clamsara::%registry-pending-count registry)))
                     "Recoverable exit lost the pending successor")
              (check (= 1 (drain-pending-finalizers registry context)) "Pending successor did not drain"))
            (check (and (or (eq exit-style :throw) (eql outcome 2))
                        (equal (reverse calls) '(:a :b))
                        (eq :open (clamsara::%plan-state (world-plan world))))
                   "Recoverable nonmoving failure was treated as a retained stop")
            (set-world-root world 0 nil)
            (check-empty-registry registry)
            (close-quality-world world)))
      (check (= (if (eq exit-style :return) 0 1)
                (clamsara::%registry-callback-failure-count registry))
             "Nested collection failure/exit count")
      (check (zerop (clamsara::%context-finalizer-depth context))
             "Callback pin remained after nested collection failure"))))

(defun run-finalizer-drain-tests ()
  (let ((failures 0) (cases 0))
    (flet ((run (name function algorithm starts)
             (incf cases)
             (handler-case
                 (progn (funcall function algorithm starts)
                        (format t "~&FINALIZER-DRAIN ~S ~S ~S PASS~%" name algorithm starts))
               (error (condition)
                 (incf failures)
                 (format t "~&FINALIZER-DRAIN ~S ~S ~S FAIL: ~A~%" name algorithm starts condition)))))
      (run-profile
       (lambda (algorithm starts)
         (dolist (style '(:normal :error :throw))
           (run style (lambda (algorithm starts) (run-callback-exit algorithm starts style))
                algorithm starts))
         (run :recursive #'run-recursive-drain algorithm starts)
         (run :nested-publication #'run-nested-publication algorithm starts)
         (run :appends #'run-callback-appends algorithm starts)
         (run :running-roots #'run-running-roots algorithm starts)
         (run :active-context #'run-active-callback-context algorithm starts)
         (run :throw-keeps-rest #'run-throw-keeps-rest algorithm starts)
         (run :recursive-throw #'run-recursive-throw algorithm starts)
         (run :single-record #'run-single-record-drain algorithm starts)
         (dolist (style '(:return :throw :error))
           (run (list :collection-failure style)
                (lambda (algorithm starts)
                  (run-callback-collection-failure algorithm starts style))
                algorithm starts)))))
    (check (zerop failures) "Finalizer drain histories: ~D/~D failed" failures cases)
    (format t "~&FINALIZER-DRAIN-HISTORIES-PASS cases=~D~%" cases)
    t))
