;;;; Regression histories found by the independent v14 review.
;;;; These exercise the hosted registry. They do not establish managed callback
;;;; support or complete finalizer/profile admission.
(defpackage #:clamsara.quality.finalizers
  (:use #:cl #:clamsara #:clamsara.quality.support)
  (:export #:run-finalizer-registration-tests))
(in-package #:clamsara.quality.finalizers)

(defun registrations (registry)
  (let ((entries nil))
    (map-finalizer-registrations registry
                                (lambda (token referent)
                                  (push (cons token referent) entries)))
    (nreverse entries)))

(defun complete-collection (world)
  (let ((record (collect-world world)))
    (check (eq :complete (cycle-result-status record))
           "Finalizer history collection failed: ~S/~S/~S"
           (cycle-result-status record) (cycle-result-phase record)
           (cycle-result-reason record))
    record))

(defun run-cancel-reuse (algorithm starts)
  (let* ((world (make-quality-world :algorithm algorithm :object-starts starts
                                     :extent 512 :finalizer-capacity 3))
         (registry (world-registry world)) (context (world-context world))
         (old-tokens nil) (calls 0))
    (dotimes (iteration 12)
      (let* ((node (allocate-node world iteration))
             (first (register-finalizer registry context node
                       (lambda (value) (declare (ignore value)) (incf calls)))))
        (check (eq :canceled (cancel-finalizer registry context first))
               "First cancellation failed")
        (let ((second (register-finalizer registry context node
                        (lambda (value) (declare (ignore value)) (incf calls)))))
          (check (and (not (eql first second))
                      (not (member second old-tokens))) "Finalizer token revived")
          (dolist (stale (cons first old-tokens))
            (check (eq :already-finalized (cancel-finalizer registry context stale))
                   "Stale token canceled a successor"))
          (check (eq :canceled (cancel-finalizer registry context second))
                 "Reused slot's current token cannot cancel its registration")
          (push first old-tokens) (push second old-tokens)))
      (check (null (registrations registry)) "Canceled record stayed active")
      (complete-collection world)
      (check (zerop (drain-pending-finalizers registry context))
             "Canceled callback became pending"))
    (check (zerop calls) "Canceled callback ran")
    (close-quality-world world)))

(defun run-drain-reuse (algorithm starts)
  (let* ((world (make-quality-world :algorithm algorithm :object-starts starts
                                     :extent 512 :finalizer-capacity 3))
         (registry (world-registry world)) (context (world-context world))
         (calls nil) (old-token nil))
    (dotimes (iteration 12)
      (let* ((id (+ 100 iteration)) (node (allocate-node world id))
             (token (register-finalizer
                     registry context node
                     (lambda (referent)
                       (check-equal id (read-node-slot world referent 0) "finalized payload")
                       (push id calls)))))
        (when old-token
          (check (eq :already-finalized (cancel-finalizer registry context old-token))
                 "Done token named a new active record"))
        (complete-collection world)
        (check (= 1 (drain-pending-finalizers registry context)) "Expected one callback")
        (check (zerop (drain-pending-finalizers registry context)) "Callback repeated")
        (check (null (registrations registry)) "Done record stayed active")
        (setf old-token token)))
    (check-equal (loop for id from 111 downto 100 collect id) calls "callback order/count")
    (close-quality-world world)))

(defun run-partial-hole-reuse (algorithm starts)
  (let* ((world (make-quality-world :algorithm algorithm :object-starts starts
                                     :extent 512 :finalizer-capacity 3))
         (registry (world-registry world)) (context (world-context world))
         (tokens (make-array 3)) (calls nil))
    (dotimes (index 3)
      (let ((id index) (node (allocate-node world index)))
        (set-world-root world index node)
        (setf (aref tokens index)
              (register-finalizer registry context node
                (lambda (referent)
                  (check-equal id (read-node-slot world referent 0))
                  (push id calls))))))
    (check (eq :canceled (cancel-finalizer registry context (aref tokens 1)))
           "Middle cancellation failed")
    (let ((replacement (register-finalizer registry context (read-world-root world 1)
                         (lambda (referent)
                           (check-equal 1 (read-node-slot world referent 0))
                           (push :replacement calls)))))
      (check (eq :already-finalized (cancel-finalizer registry context (aref tokens 1)))
             "Middle stale token canceled replacement")
      ;; Live registry referents must be corrected too, before later selection.
      (complete-collection world)
      (check (= 3 (length (registrations registry))) "Active registration lost")
      (check (find replacement (registrations registry) :key #'car)
             "Replacement token disappeared after movement")
      (dotimes (index 3) (set-world-root world index nil))
      (complete-collection world)
      (check (= 3 (drain-pending-finalizers registry context)) "Hole reuse lost callbacks")
      (check-equal '(0 :replacement 2) (reverse calls) "physical slot publication order")
      (check (eq :already-finalized (cancel-finalizer registry context replacement))
             "Completed replacement was cancelable"))
    (close-quality-world world)))

(defun run-registration-admission (algorithm starts)
  (let* ((world (make-quality-world :algorithm algorithm :object-starts starts
                                     :extent 512 :finalizer-capacity 3))
         (foreign (make-quality-world :algorithm algorithm :object-starts starts
                                       :extent 512 :finalizer-capacity 3))
         (registry (world-registry world)) (context (world-context world))
         (callback (lambda (referent) (declare (ignore referent))))
         (stale (allocate-node world 1)) (other (allocate-node foreign 2)))
    (set-world-root foreign 0 other)
    (complete-collection world)
    (check (stale-reference-p world stale) "Admission setup failed to retire source")
    (dolist (invalid (list nil 17 :foreign-immediate (cons 1 2) "host payload" stale other))
      (signals-runtime-reason
       (lambda () (register-finalizer registry context invalid callback))
       :invalid-finalizer-registration)
      (check (null (registrations registry)) "Rejected referent published a record"))
    (let ((valid (allocate-node world 3)))
      (set-world-root world 0 valid)
      (signals-runtime-reason
       (lambda () (register-finalizer registry (world-context foreign) valid callback))
       :invalid-finalizer-registration)
      (signals-runtime-reason
       (lambda () (register-finalizer registry context valid nil))
       :invalid-finalizer-registration)
      (let ((token (register-finalizer registry context valid callback)))
        (check (eq :canceled (cancel-finalizer registry context token))
               "Valid registration failed after rejected requests")))
    (close-quality-world foreign)
    (close-quality-world world)))

(defun run-cross-registry (algorithm starts)
  (let* ((a (make-quality-world :algorithm algorithm :object-starts starts))
         (b (make-quality-world :algorithm algorithm :object-starts starts))
         (ra (world-registry a)) (rb (world-registry b))
         (ca (world-context a)) (cb (world-context b))
         (callback (lambda (reference) (declare (ignore reference))))
         (ta (register-finalizer ra ca (allocate-node a 1) callback))
         (tb (register-finalizer rb cb (allocate-node b 2) callback)))
    ;; Use a VALID B context; this must test token identity, not context checks.
    (cancel-finalizer rb cb ta)
    (check (= 1 (length (registrations rb)))
           "Registry A's token canceled registry B's unrelated registration")
    (dolist (invalid (list nil 1 most-positive-fixnum :bogus (copy-structure tb)))
      (cancel-finalizer rb cb invalid)
      (check (= 1 (length (registrations rb)))
             "Invalid/forged token canceled a registration"))
    (check (eq :canceled (cancel-finalizer rb cb tb)) "B's own token failed")
    (let* ((reference (allocate-node b 3))
           (current (register-finalizer rb cb reference callback))
           (before (registrations rb))
           (coordinator (world-coordinator b)))
      ;; CORRECT is a collector entry: test it under real completed coverage,
      ;; not by pretending a running mutator is the collector.
      (multiple-value-bind (stop reason)
          (request-safepoint coordinator :all :finalizer-token-check)
        (check (and stop (null reason)) "Token test stop was rejected")
        (multiple-value-bind (completed coverage failure)
            (await-safepoint coordinator stop)
          (check (and (eql completed stop) coverage (null failure))
                 "Token test coverage failed")
          (unwind-protect
               (progn
                 (dolist (invalid (list ta tb (copy-structure current) nil 1))
                   (check (eq :stale (correct-finalizer-referent
                                     rb invalid reference reference))
                          "Foreign/stale/copied token corrected a live registration")
                   (check-equal before (registrations rb) "mismatched correction changed records"))
                 (check (eq :corrected (correct-finalizer-referent
                                       rb current reference reference))
                        "Valid token was not correctable"))
            (check (eq :released (release-safepoint coordinator stop))
                   "Token test coverage did not release"))))
      (check (eq :canceled (cancel-finalizer rb cb current)) "Current B token failed"))
    (check (eq :canceled (cancel-finalizer ra ca ta)) "A's own token failed")
    (close-quality-world b)
    (close-quality-world a)))

(defun check-token-storage-account (world)
  (let* ((registry (world-registry world))
         (configuration (world-configuration world))
         (construction (clamsara::configuration-construction-context configuration))
         (identity (clamsara::%registry-index-resource-id registry))
         (state (gethash identity (clamsara::%context-resources construction)))
         (resource (clamsara::%resource-state-release-capability state))
         (manifest (clamsara::%simulator-resource-manifest resource))
         (account (find identity (clamsara::%configuration-capacity-account configuration)
                        :key #'clamsara::%capacity-account-entry-identity :test #'eq))
         (objects (append (coerce (clamsara::%registry-token-reserve registry) 'list)
                          (list (clamsara::%registry-token-owner registry)
                                (clamsara::%registry-token-reserve registry)
                                (clamsara::%registry-tokens registry)
                                (clamsara::%registry-pending registry)))))
    (check (clamsara::%simulator-resource-closed-p resource) "Token manifest not closed")
    (dolist (object objects)
      (check (= 1 (count object manifest :test #'eq)) "Token storage not owned exactly once"))
    (check account "Token resource missing from immutable account")
    (check (= (clamsara::%capacity-account-entry-entry-capacity account)
              (+ (* 2 (clamsara::%registry-capacity registry))
                 (clamsara::%registry-registration-capacity registry)))
           "Historical token vector omitted from entry account")
    (check (= (clamsara::%capacity-account-entry-auxiliary-bytes account)
              (+ (clamsara::%host-object-storage resource)
                 (clamsara::%host-object-storage manifest)
                 (clamsara::%host-object-storage
                  (clamsara::%simulator-resource-auxiliary-reserve resource))
                 (loop for object across manifest
                       sum (clamsara::%host-object-storage object))))
           "Token auxiliary charge does not match retained primitives")
    (mapcar #'clamsara::%host-object-storage objects)))

(defun run-history-exhaustion (algorithm starts)
  (let* ((world (make-quality-world
                 :algorithm algorithm :object-starts starts
                 :finalizer-capacity 2 :finalizer-registration-capacity 3))
         (registry (world-registry world)) (context (world-context world))
         (reserve (clamsara::%registry-token-reserve registry))
         (reserved (coerce reserve 'list))
         (charges (check-token-storage-account world))
         (callback (lambda (reference) (declare (ignore reference))))
         (node (allocate-node world 1)))
    (set-world-root world 0 node)
    (signals-runtime-reason
     (lambda () (register-finalizer registry context nil callback))
     :invalid-finalizer-registration)
    (check (zerop (clamsara::%registry-next-token registry))
           "Rejected admission consumed history")
    (let ((a (register-finalizer registry context node callback))
          (b (register-finalizer registry context node callback)))
      (check (and (eq a (first reserved)) (eq b (second reserved)))
             "Registration did not use construction-provisioned tokens")
      (signals-runtime-reason
       (lambda () (register-finalizer registry context node callback))
       :weak-storage-exhausted)
      (check (= 2 (clamsara::%registry-next-token registry))
             "Full-record rejection consumed history")
      (check (eq :canceled (cancel-finalizer registry context a)) "Cancel A failed")
      (let ((c (register-finalizer registry context node callback)))
        (check (eq c (third reserved)) "Reused record did not use next reserved token")
        (check (= 2 (length (registrations registry))) "Active record accounting failed")
        (cancel-finalizer registry context b)
        (cancel-finalizer registry context c)))
    ;; All F slots are free, but H historical identities are exhausted.
    (signals-runtime-reason
     (lambda () (register-finalizer registry context node callback))
     :generation-exhausted)
    (check (null (registrations registry)) "History exhaustion published a record")
    (check (= 3 (clamsara::%registry-next-token registry)) "History index advanced on failure")
    (check (eq reserve (clamsara::%registry-token-reserve registry)) "Token vector grew")
    (dotimes (index 3)
      (check (eq (nth index reserved) (aref reserve index)) "Historical token replaced"))
    (complete-collection world)
    (check (live-reference-p world (read-world-root world 0))
           "History exhaustion damaged normal collection")
    (check-equal charges (check-token-storage-account world) "token storage changed after publication")
    (close-quality-world world)))

(defun run-registration-capacity-admission ()
  (dolist (invalid (list nil 0 -1 :bogus 1.5 (1+ most-positive-fixnum)))
    (signals-runtime-reason
     (lambda () (make-sequential-finalizer-registry :capacity invalid))
     :invalid-finalizer-capacity)
    (signals-runtime-reason
     (lambda () (make-sequential-finalizer-registry
                 :capacity 2 :registration-capacity invalid))
     :invalid-finalizer-capacity))
  (signals-runtime-reason
   (lambda () (make-sequential-finalizer-registry :capacity 2 :registration-capacity 1))
   :invalid-finalizer-capacity))

(defun run-finalizer-registration-tests ()
  (run-registration-capacity-admission)
  (run-profile
   (lambda (algorithm starts)
     (run-cancel-reuse algorithm starts)
     (run-drain-reuse algorithm starts)
     (run-partial-hole-reuse algorithm starts)
     (run-registration-admission algorithm starts)
     (run-cross-registry algorithm starts)
     (run-history-exhaustion algorithm starts)))
  (format t "~&FINALIZER-REGISTRATION-HISTORIES-PASS profiles=4~%")
  t)
