;;;; Independently authored composed callback histories from the fixed queue review.
;;;; Native callbacks are test controllers, not managed-callback ABI evidence.
(defpackage #:clamsara.quality.finalizer-history
  (:use #:cl #:clamsara #:clamsara.quality.support)
  (:export #:run-finalizer-history-tests))
(in-package #:clamsara.quality.finalizer-history)
(defvar *inside-failures* nil)
(defun demand (condition control &rest args)
  (unless condition
    (let ((message (apply #'format nil control args)))
      (push message *inside-failures*) (error "~A" message))))
(defun cycle (w)
  (let ((result (collect-world w)))
    (demand (eq :complete (cycle-result-status result)) "cycle failed ~S/~S"
            (cycle-result-phase result) (cycle-result-reason result)) result))
(defun pending (r) (clamsara::%registry-pending-count r))
(defun depth (c) (clamsara::%context-finalizer-depth c))
(defun reason (thunk)
  (handler-case (funcall thunk)
    (clamsara::runtime-rejection (e) (clamsara::runtime-rejection-reason e))))
(defun clean (r)
  (demand (and (zerop (pending r))
               (every (lambda (s) (eq s :free)) (clamsara::%registry-states r))
               (every #'null (clamsara::%registry-referents r)))
          "Registry did not become empty"))

(defun composed-wrap-history (algorithm starts)
  (let* ((w (make-quality-world :algorithm algorithm :object-starts starts
              :extent 512 :finalizer-capacity 5 :finalizer-registration-capacity 80
              :stop-capacity 256))
         (r (world-registry w)) (ca (world-context w))
         (cb (bind-mutator (world-configuration w) :independent-secondary :default))
         (events nil) (tokens nil) (inner-result nil) (cleanup-result nil))
    (labels ((event (name) (push name events))
             (live (name id)
               (let* ((token (cdr (assoc name tokens)))
                      (index (clamsara::%registry-token-index r token))
                      (ref (and index (aref (clamsara::%registry-referents r) index))))
                 (demand (and ref (= id (read-node-slot w ref 0)))
                         "Wrong running/pending root ~S" name)))
             (register (name node fn)
               (let ((token (register-finalizer r ca node fn)))
                 (push (cons name token) tokens) token)))
      (dotimes (round 10)
        (setf events nil tokens nil inner-result nil cleanup-result nil)
        (let ((a (allocate-node w 1)) (b (allocate-node w 2))
              (c (allocate-node w 3)) (d (allocate-node w 4)))
          (set-world-root w 0 d)
          (register :a a
            (lambda (ref)
              (declare (ignore ref)) (event :a)
              (setf inner-result
                    (catch 'inner-exit (drain-pending-finalizers r cb)))
              (demand (eq inner-result :inner-escaped) "inner escape lost")
              (demand (and (= 1 (depth ca)) (zerop (depth cb))) "depth after inner escape")
              ;; Reuse B's physical slot while A runs and C/D are pending.
              (register :e (allocate-node w 5)
                (lambda (ref) (declare (ignore ref)) (event :e)))
              (demand (eq :already-finalized (cancel-finalizer r ca (cdr (assoc :b tokens))))
                      "B token canceled E")
              (cycle w)
              (unwind-protect (throw 'outer-exit :outer-escaped)
                ;; Unwind cleanup itself recursively drains and collects.
                (setf cleanup-result (drain-pending-finalizers r cb))
                (demand (eq :retry (unbind-mutator (world-configuration w) ca))
                        "A context unbound inside cleanup"))))
          (register :b b
            (lambda (ref)
              (declare (ignore ref)) (event :b)
              (demand (and (= 1 (depth ca)) (= 1 (depth cb))) "cross-context depth")
              (set-world-root w 0 nil) (cycle w)
              (live :a 1) (live :b 2)
              (throw 'inner-exit :inner-escaped)))
          (register :c c
            (lambda (ref)
              (declare (ignore ref)) (event :c)
              (cycle w) (live :a 1) (live :c 3)
              (demand (= 2 (drain-pending-finalizers r ca)) "D/E recursive count")
              (event :c-return)))
          (register :d d
            (lambda (ref)
              (declare (ignore ref)) (event :d)
              (demand (and (= 2 (depth ca)) (= 1 (depth cb))) "deep context pins")
              (error "Expected D callback error"))))
        (cycle w)
        (demand (eq :outer-escaped (catch 'outer-exit (drain-pending-finalizers r ca)))
                "outer escape lost")
        (demand (= cleanup-result 1) "cleanup claimed count ~S" cleanup-result)
        (demand (equal (reverse events) '(:a :b :c :d :e :c-return))
                "Wrong recursive/unwind order ~S" (reverse events))
        (demand (= (* 3 (1+ round)) (clamsara::%registry-callback-failure-count r))
                "failure accounting differs after round ~D" round)
        (demand (and (zerop (depth ca)) (zerop (depth cb))) "depth leaked")
        (clean r) (cycle w))
      (demand (eq :unbound (unbind-mutator (world-configuration w) cb)) "secondary unbind failed")
      (close-quality-world w)
      (format t "~&COMPOSED-WRAP-PASS ~S ~S rounds=10 callbacks=50 failures=30~%" algorithm starts))))

(defun two-registry-escape (algorithm starts)
  (let* ((a (make-quality-world :algorithm algorithm :object-starts starts :extent 512))
         (b (make-quality-world :algorithm algorithm :object-starts starts :extent 512))
         (ra (world-registry a)) (rb (world-registry b))
         (ca (world-context a)) (cb (world-context b)) (events nil))
    (register-finalizer ra ca (allocate-node a 1)
      (lambda (ref) (declare (ignore ref)) (push :a1 events)
        (drain-pending-finalizers rb cb)))
    (register-finalizer ra ca (allocate-node a 2)
      (lambda (ref) (declare (ignore ref)) (push :a2 events)))
    (register-finalizer rb cb (allocate-node b 3)
      (lambda (ref) (declare (ignore ref)) (push :b1 events)
        (cycle a) (cycle b)
        (demand (and (= 1 (depth ca)) (= 1 (depth cb))) "two-world pins lost")
        (throw 'both-exit :both-escaped)))
    (register-finalizer rb cb (allocate-node b 4)
      (lambda (ref) (declare (ignore ref)) (push :b2 events)))
    (cycle a) (cycle b)
    (demand (eq :both-escaped (catch 'both-exit (drain-pending-finalizers ra ca)))
            "cross-registry escape lost")
    (demand (and (= 1 (pending ra)) (= 1 (pending rb))
                 (zerop (depth ca)) (zerop (depth cb))) "cross-registry state damaged")
    (demand (= 1 (drain-pending-finalizers rb cb)) "B tail lost")
    (demand (= 1 (drain-pending-finalizers ra ca)) "A tail lost")
    (demand (equal (reverse events) '(:a1 :b1 :b2 :a2)) "cross-registry order ~S" events)
    (demand (and (= 1 (clamsara::%registry-callback-failure-count ra))
                 (= 1 (clamsara::%registry-callback-failure-count rb))) "cross-registry failures")
    (clean ra) (clean rb) (close-quality-world a) (close-quality-world b)
    (format t "~&TWO-REGISTRY-ESCAPE-PASS ~S ~S~%" algorithm starts)))

(defun recursive-collection-failure (algorithm starts escape-p)
  (let* ((weak-kind nil)
         (w (make-quality-world :algorithm algorithm :object-starts starts
              :extent 512 :finalizer-capacity 3 :conditional-capacity 0
              :configure-model
              (lambda (m)
                (setf weak-kind (make-object-kind-description m :review-weak
                  :size-rule 16 :alignment-rule 16 :weak-descriptions
                  (list (make-weak-location-description m
                          '(:identity :edge :offset 0) :leaf :cleared)))))))
         (r (world-registry w)) (ca (world-context w))
         (cb (bind-mutator (world-configuration w) :nested-failure :default))
         (events nil) (nested-record nil) (inner nil))
    (register-finalizer r ca (allocate-node w 1)
      (lambda (ref) (declare (ignore ref)) (push :a events)
        (setf inner (reason (lambda () (drain-pending-finalizers r cb))))))
    (register-finalizer r ca (allocate-node w 2)
      (lambda (ref) (declare (ignore ref)) (push :b events)
        (multiple-value-bind (holder status why)
            (allocate-object cb :review-weak 16 16 weak-kind)
          (demand (eq status :allocated) "weak allocation ~S" why)
          (set-world-root w 0 holder))
        (setf nested-record (collect-world w))
        (when escape-p (throw 'failure-exit :escaped))))
    (register-finalizer r ca (allocate-node w 3)
      (lambda (ref) (declare (ignore ref)) (push :c events)))
    (cycle w)
    (let ((result (catch 'failure-exit
                    (reason (lambda () (drain-pending-finalizers r ca))))))
      (demand (and (eq :retained (cycle-result-status nested-record))
                   (eq :weak-storage-exhausted (cycle-result-reason nested-record)))
              "nested failure wrong")
      (demand (and (zerop (depth ca)) (zerop (depth cb))) "retained/escape depth leak")
      (if (eq algorithm :semispace)
          (progn
            (demand (eq result (if escape-p :escaped :collection-busy)) "closed outcome ~S" result)
            (demand (equal (reverse events) '(:a :b)) "callback ran under retained stop")
            (demand (equal (coerce (clamsara::%registry-states r) 'list)
                           '(:running :running :pending)) "claimed roots recycled")
            (demand (and (= 1 (pending r))
                         (= 3 (count-if #'identity (clamsara::%registry-referents r))))
                    "retained roots/queue lost")
            (demand (eq :collection-busy (reason (lambda () (drain-pending-finalizers r cb))))
                    "closed drain resumed")
            (demand (eq :retry (unbind-mutator (world-configuration w) cb)) "closed unbind resumed"))
          (progn
            (when escape-p
              (demand (and (eq result :escaped) (= 1 (pending r))) "recoverable escape state")
              (demand (= 1 (drain-pending-finalizers r ca)) "remaining C lost"))
            (unless escape-p
              (demand (and (= result 1) (= inner 2)) "recursive recoverable drain counts"))
            (demand (equal (reverse events) '(:a :b :c)) "recoverable order")
            (clean r) (set-world-root w 0 nil)
            (unbind-mutator (world-configuration w) cb)
            (close-quality-world w)))
      (demand (= (if escape-p 2 0) (clamsara::%registry-callback-failure-count r))
              "nested failure count")
      (format t "~&RECURSIVE-FAILURE-PASS ~S ~S escape=~S actual=~S inner=~S~%"
              algorithm starts escape-p result inner))))

(defun run-finalizer-history-tests ()
  (let ((*inside-failures* nil))
    (dolist (algorithm '(:semispace :marksweep))
      (dolist (starts '(:packed :scalar))
        (composed-wrap-history algorithm starts)
        (two-registry-escape algorithm starts)
        (recursive-collection-failure algorithm starts nil)
        (recursive-collection-failure algorithm starts t)))
    (demand (null *inside-failures*) "Callback swallowed assertions: ~S" *inside-failures*)
    (format t "~&INDEPENDENT-QUEUE-PASS cases=16~%")
    t))
