;;;; Independent seeded graph histories from the fresh v14 review.
;;;; Managed payload/roots are compared with a separate host reachability oracle.
(in-package #:clamsara.quality.generational)

(defun oracle-graph (roots edges)
  (let ((todo (remove nil (coerce roots 'list))) (seen nil) (rows nil))
    (loop while todo for id = (pop todo)
          unless (member id seen)
            do (push id seen)
               (let ((pair (gethash id edges)))
                 (push (list id (first pair) (second pair)) rows)
                 (dolist (target pair) (when target (push target todo)))))
    (list (coerce roots 'list) (sort rows #'< :key #'first))))

(defun run-generational-history (starts seed)
  (let* ((w (make-generation-world :object-starts starts :nursery-extent 256
                                   :mature-extent 4096))
         (root-ids (make-array 8 :initial-element nil))
         (edges (make-hash-table)) (next-id 0) (state seed)
         (minors 0) (majors 0))
    (labels ((random-integer (bound)
               (setf state (mod (+ (* state 1664525) 1013904223) (expt 2 32)))
               (mod (ash state -8) bound))
             (verify ()
               (check (equal (oracle-graph root-ids edges) (snapshot-world-graph w))
                      "Oracle mismatch in ~S seed ~D id ~D" starts seed next-id))
             (cycle (scope)
               (let ((record (collect-world w :scope scope)))
                 (check (eq :complete (cycle-result-status record))
                        "Unexpected cycle failure ~S ~S/~S" scope
                        (cycle-result-phase record) (cycle-result-reason record)))
               (ecase scope (:minor (incf minors)) (:all (incf majors)))
               (verify)))
      (dotimes (iteration 72)
        ;; Bound allocation between explicit cycles: 2 nodes in a 256-byte nursery.
        (dotimes (unused 2)
          (declare (ignorable unused))
          (let* ((id (incf next-id)) (new (allocate-node w id))
                 (slot (random-integer 8)) (left (random-integer 8))
                 (right (random-integer 8)))
            (set-node-slot w new 1 (read-world-root w left))
            (set-node-slot w new 2 (read-world-root w right))
            (setf (gethash id edges) (list (aref root-ids left) (aref root-ids right)))
            (set-world-root w slot new) (setf (aref root-ids slot) id)))
        ;; Rewrite existing old sources and delete old edges. No raw bypass.
        (dotimes (unused 4)
          (declare (ignorable unused))
          (let* ((slot (random-integer 8)) (target-slot (random-integer 8))
                 (edge (random-integer 2)) (id (aref root-ids slot)))
            (when id
              (set-node-slot w (read-world-root w slot) (1+ edge)
                             (read-world-root w target-slot))
              (setf (nth edge (gethash id edges)) (aref root-ids target-slot)))))
        (when (zerop (mod iteration 3))
          (let ((slot (random-integer 8)))
            (set-world-root w slot nil) (setf (aref root-ids slot) nil)))
        (when (zerop (mod iteration 12))
          ;; Avoid retaining an unbounded root graph; keep address reuse frequent.
          (dotimes (slot 8) (set-world-root w slot nil) (setf (aref root-ids slot) nil)))
        (verify)
        (cycle (if (zerop (mod iteration 4)) :all :minor)))
      (check (and (= minors 54) (= majors 18)) "Incomplete generational history")
      (close-quality-world w)
      (format t "~&GEN-HISTORY-PASS starts=~S seed=~D minors=~D majors=~D~%"
              starts seed minors majors))))

(defun run-generational-history-tests ()
  (dolist (starts '(:packed :scalar))
    (dolist (seed '(731 15799)) (run-generational-history starts seed)))
  (format t "~&GENERATIONAL-HISTORIES-PASS cycles=288 minors=216 majors=72~%")
  t)
