;;;; Independent geometry histories, integrated from the fixed-snapshot review.
;;;; See docs/geometry-snapshot-review.md and docs/geometry-unwind-review.md.
(defpackage #:clamsara.quality.kind-history
  (:use #:cl #:clamsara #:clamsara.quality.support)
  (:export #:run-kind-history-tests))
(in-package #:clamsara.quality.kind-history)
(defvar *case-count* 0)
(defun event (label &rest fields) (format t "~&CHECK ~S ~S~%" label fields) (finish-output))
(defun allocated (world kind bytes &optional (alignment 16))
  (multiple-value-bind (object status reason)
      (allocate-object (world-context world) kind bytes alignment
                       (object-kind-descriptor (world-model world) kind))
    (check (and object (eq status :allocated) (null reason))
           "Allocation ~S/~S failed: ~S/~S" kind bytes status reason)
    object))
(defun reject-allocation (world kind bytes alignment token reason)
  (multiple-value-bind (object status actual)
      (allocate-object (world-context world) kind bytes alignment token)
    (check (and (null object) (eq status :failed) (eq actual reason))
           "Expected ~S, got ~S/~S" reason status actual)))
(defun signals-p (function)
  (handler-case (progn (funcall function) nil) (error () t)))
(defun complete (world count)
  (let ((record (collect-world world)))
    (check (and (eq :complete (cycle-result-status record))
                (= count (cycle-result-count record :objects-discovered)))
           "Cycle: ~S/~S discoveries ~S, expected ~D"
           (cycle-result-status record) (cycle-result-reason record)
           (cycle-result-count record :objects-discovered) count)
    (event :cycle (world-algorithm world) (world-object-starts world)
           :discovered count :moved (cycle-result-count record :objects-moved))))
(defun strong-ids (model source &optional stage)
  (let ((ids nil))
    (funcall (if stage #'map-staged-reference-locations #'map-reference-locations)
             model source (lambda (id location) (declare (ignore location)) (push id ids)))
    (nreverse ids)))
(defun location-value (model source wanted &optional stage)
  (let ((value nil) (found nil))
    (funcall (if stage #'map-staged-reference-locations #'map-reference-locations)
             model source (lambda (id location)
                            (when (eql id wanted)
                              (setf found t value (load-reference model location)))))
    (check found "No location ~S" wanted) value))

;; Independent complete fixture permits the same offered model to be handed to
;; two configurations. It does not replace any model or collector operation.
(defun world-from-offer (offer algorithm starts)
  (let* ((q 16) (base 4096) (extent 512)
         (roots (make-simulator-root-client :provider-capacity 8))
         (provider (make-simulator-root-provider 4))
         (token (register-root-provider roots :independent-roots 4 provider))
         (coordinator (make-simulator-coordinator roots :stop-capacity 16 :await-bound 16))
         (arena (make-simulator-address-space :base base
                  :byte-extent (* extent (if (eq algorithm :semispace) 2 1))
                  :alignment q :page-size 256 :coordinator coordinator))
         (clients (make-simulator-clients :model offer :roots roots :coordinator coordinator
                    :address-space arena :atomics (make-host-atomics)
                    :diagnostics (make-simulator-diagnostics)))
         (registry (make-sequential-finalizer-registry :capacity 4 :root-client roots))
         (domain0 (make-metadata-domain :base base :limit (+ base extent) :granularity q))
         (map0 (ecase starts (:packed (make-object-start-marks :domain domain0))
                                   (:scalar (make-scalar-object-start-marks :domain domain0))))
         (first-space
           (if (eq algorithm :semispace)
               (make-semispace-space :name :first :object-start-map map0
                 :forwarding (make-side-forwarding :domain domain0)
                 :extent extent :packing-quantum q :role :allocation)
               (make-marksweep-space :name :first :object-start-map map0
                 :marks (make-side-marks :domain domain0) :extent extent
                 :packing-quantum q :descriptor-capacity 128)))
         (second-space
           (when (eq algorithm :semispace)
             (let* ((domain1 (make-metadata-domain :base (+ base extent)
                              :limit (+ base (* 2 extent)) :granularity q))
                    (map1 (ecase starts (:packed (make-object-start-marks :domain domain1))
                                              (:scalar (make-scalar-object-start-marks :domain domain1)))))
               (make-semispace-space :name :second :object-start-map map1
                 :forwarding (make-side-forwarding :domain domain1)
                 :extent extent :packing-quantum q :role :reserve))))
         (plan (if second-space
                   (make-semispace-plan :from-space first-space :to-space second-space
                     :root-client roots :coordinator coordinator
                     :diagnostics (clamsara::construction-diagnostics-client clients)
                     :registry registry :trace-capacity 64 :conditional-capacity 32
                     :finalizer-capacity 4 :packing-quantum q)
                   (make-marksweep-plan :space first-space :root-client roots
                     :coordinator coordinator :diagnostics (clamsara::construction-diagnostics-client clients)
                     :registry registry :trace-capacity 64 :conditional-capacity 32
                     :finalizer-capacity 4 :packing-quantum q)))
         (configuration (construct-plan plan clients))
         (context (bind-mutator configuration :independent-mutator :default)))
    (clamsara.quality.support::%make-quality-world
      :algorithm algorithm :object-starts starts :packing-quantum q
      :configuration configuration :context context :model (configuration-object-model configuration)
      :roots roots :root-token token :root-provider provider :coordinator coordinator
      :plan plan :registry registry :space first-space :root-count 4
      :node-kind (object-kind-descriptor (configuration-object-model configuration) :quality-node))))

(defun account-index (world)
  (let ((owners (make-hash-table :test #'eq))
        (construction (clamsara::configuration-construction-context (world-configuration world))))
    (maphash
      (lambda (id state)
        (let* ((resource (clamsara::%resource-state-release-capability state))
               (manifest (clamsara::%simulator-resource-manifest resource))
               (handle (clamsara::%simulator-resource-handle resource))
               (padding (clamsara::%simulator-resource-physical-padding resource))
               (reserve (clamsara::%simulator-resource-auxiliary-reserve resource))
               (aux (+ (clamsara::%host-object-storage resource)
                       (clamsara::%host-object-storage manifest)
                       (clamsara::%host-object-storage reserve)))
               (entry (find id (clamsara::%configuration-capacity-account (world-configuration world))
                        :test #'eql :key #'clamsara::%capacity-account-entry-identity)))
          (check (and (clamsara::%simulator-resource-closed-p resource)
                      (null (clamsara::%simulator-resource-manifest-seen resource)))
                 "Unclosed resource")
          (loop for object across manifest do
            (check (not (gethash object owners)) "Duplicate manifest object")
            (setf (gethash object owners) id)
            (incf aux (clamsara::%host-object-storage object)))
          (check (= aux (clamsara::%resource-state-auxiliary-bytes state)
                        (clamsara::%capacity-account-entry-auxiliary-bytes entry))
                 "Auxiliary charge mismatch")
          (check (= (+ (clamsara::%host-object-storage handle)
                       (if padding (clamsara::%host-object-storage padding) 0))
                    (clamsara::%resource-state-physical-bytes state)
                    (clamsara::%capacity-account-entry-physical-bytes entry))
                 "Physical charge mismatch")))
      (clamsara::%context-resources construction))
    owners))
(defun check-catalogue-account (world)
  ;; Independent membership walk, not the patch's storage visitor.
  (let* ((model (world-model world)) (owners (account-index world))
         (table (clamsara::host-model-description-snapshots model))
         (required (list model table (clamsara::host-model-kinds model)
                         (clamsara::host-model-kind-snapshots model))))
    (dolist (catalogue (list (clamsara::host-model-kinds model)
                            (clamsara::host-model-kind-snapshots model)))
      (dotimes (i (clamsara::host-model-kind-count model))
        (let* ((kind (aref catalogue i))
               (size (clamsara::host-object-kind-description-size-rule kind))
               (alignment (clamsara::host-object-kind-description-alignment-rule kind))
               (strong (clamsara::host-object-kind-description-strong-layout kind))
               (weak (clamsara::host-object-kind-description-weak-descriptions kind))
               (eph (clamsara::host-object-kind-description-ephemeron-descriptions kind)))
          (push kind required)
          (when (or (functionp size) (typep size 'clamsara::host-variable-size-rule)) (push size required))
          (when (functionp alignment) (push alignment required))
          (push strong required) (push weak required) (push eph required)
          (if (vectorp strong) (loop for slot across strong do (push slot required))
              (push (clamsara::host-indexed-layout-identity-function strong) required))
          (loop for slot across weak do (push slot required))
          (loop for slot across eph do (push slot required)))))
    (maphash (lambda (key value) (push key required) (push value required)) table)
    (dolist (object required) (check (gethash object owners) "Unowned kind-storage ~S" (type-of object)))
    (event :account :unique-required (length (remove-duplicates required :test #'eq))
           :alias-count (hash-table-count table))
    (hash-table-count table)))

(defun shared-binding-case (algorithm starts)
  (let* ((size 32) (alignment 8) (size-calls 0) (alignment-calls 0)
         (size-rule (lambda (kind) (declare (ignore kind)) (incf size-calls) size))
         (alignment-rule (lambda (kind) (declare (ignore kind)) (incf alignment-calls) alignment))
         (offer (make-host-object-model :capacity 128 :max-object-bytes 128
                  :kind-capacity 8 :slot-capacity 8 :variant-capacity 16
                  :location-capacity 8 :handle-capacity 16 :stage-capacity 2))
         (node (make-object-kind-description offer :quality-node :size-rule 32
                 :alignment-rule 16 :strong-layout '(:id :left :right)))
         (token-a (make-object-kind-description offer :shared-a :size-rule size-rule
                    :alignment-rule alignment-rule :strong-layout '(:edge)))
         (token-b (make-object-kind-description offer :shared-b :size-rule size-rule
                    :alignment-rule alignment-rule :strong-layout '(:edge))))
    (declare (ignore node))
    (check (and (= 0 size-calls) (= 0 alignment-calls)) "Creation evaluated rules")
    (let* ((first (world-from-offer offer algorithm starts))
           (first-model (world-model first)))
      (check (and (= 2 size-calls) (= 2 alignment-calls)) "First binding capture count")
      ;; No allocation has happened yet. A second configuration gets new values.
      (setf size 48 alignment 16)
      (let* ((second (world-from-offer offer algorithm starts))
             (second-model (world-model second)))
        (check (and (= 4 size-calls) (= 4 alignment-calls)) "Second binding capture count")
        (setf size 0 alignment 0)
        (check (not (eq (clamsara::host-model-kind-snapshots first-model)
                       (clamsara::host-model-kind-snapshots second-model))) "Shared snapshot vector")
        (dolist (world (list first second))
          (let ((bytes (if (eq world first) 32 48))
                (align (if (eq world first) 8 16)))
            (check (and (eq token-a (object-kind-descriptor (world-model world) :shared-a))
                        (eq token-b (object-kind-descriptor (world-model world) :shared-b)))
                   "Opaque token identity changed")
            (set-world-root world 0 (allocated world :shared-a bytes align))
            (set-world-root world 1 (allocated world :shared-b bytes align))
            (set-node-slot world (read-world-root world 0) 0 (allocate-node world 101))
            (set-node-slot world (read-world-root world 1) 0 (allocate-node world 102))
            (reject-allocation world :shared-a (if (= bytes 32) 48 32) align token-a :invalid-size)
            (check-catalogue-account world)
            (complete world 4)))
        (check (and (= 4 size-calls) (= 4 alignment-calls)) "Runtime reevaluated rule")
        (close-quality-world first)
        ;; Releasing one configuration must not alter shared offered tokens or
        ;; the other configuration's executable snapshot or children.
        (complete second 4)
        (check (and (= 101 (read-node-slot second (read-node-slot second (read-world-root second 0) 0) 0))
                    (= 102 (read-node-slot second (read-node-slot second (read-world-root second 1) 0) 0))
                    (= 48 (object-size second-model (read-world-root second 0)))
                    (= 16 (object-alignment second-model (read-world-root second 0)))
                    (= 4 size-calls) (= 4 alignment-calls)) "Second binding changed after first shutdown")
        (check-catalogue-account second)
        (close-quality-world second)
        (incf *case-count*)
        (event :shared-bindings-pass algorithm starts :function-calls (list size-calls alignment-calls))))))

(defun alias-rejection-case ()
  (let* ((token nil) (weak nil)
         (world (make-quality-world :configure-model
                  (lambda (offer)
                    (setf weak (make-weak-location-description offer :weak :quality-node nil)
                          token (make-object-kind-description offer :alias :size-rule 32 :alignment-rule 16
                                  :weak-descriptions (list weak)))
                    (make-object-kind-description offer :other :size-rule 32 :alignment-rule 16))))
         (model (world-model world))
         (reserve (find :reserve (clamsara::%plan-spaces (world-plan world))
                       :key #'clamsara::%semispace-role))
         (address (clamsara::%space-base reserve))
         (snapshot (gethash token (clamsara::host-model-description-snapshots model)))
         (foreign (make-object-kind-description (make-host-object-model) :alias :size-rule 32 :alignment-rule 16))
         (bad (list :alias :other nil (copy-structure token) foreign weak
                    (object-kind-descriptor model :other))))
    (set-world-root world 0 (allocate-node world 201))
    (dolist (descriptor bad)
      (let ((before (copy-seq (clamsara::host-model-sizes model)))
            (generations (copy-seq (clamsara::host-model-descriptor-generations model)))
            (live (clamsara::host-model-live-count model)))
        (reject-allocation world :alias 32 16 descriptor :invalid-kind)
        (check (signals-p (lambda () (initialize-object model address :alias 32 descriptor)))
               "Initialize accepted descriptor by name or shape")
        (check (and (equalp before (clamsara::host-model-sizes model))
                    (equalp generations (clamsara::host-model-descriptor-generations model))
                    (= live (clamsara::host-model-live-count model)))
               "Rejected descriptor changed representation state")))
    ;; Original is public token; private snapshot is an explicit internal alias.
    (dolist (descriptor (list token snapshot))
      (let ((start (initialize-object model address :alias 32 descriptor)))
        (check (= address (reference-address model start)) "Valid alias initialized wrong address")
        (clamsara::runtime-retire-object-representation model start)))
    (check (eq token (object-kind model (allocated world :alias 32))) "Object kind is not original token")
    (complete world 1)
    (close-quality-world world)
    (incf *case-count*) (event :exact-alias-pass :rejected (length bad) :accepted 2)))

(defun conditional-info (model object staged-p)
  (let ((weak nil) (eph nil))
    (funcall (if staged-p #'map-staged-weak-descriptors #'map-weak-descriptors)
             model object (lambda (id location cleared)
                            (push (list id cleared (load-reference model location)) weak)))
    (funcall (if staged-p #'map-staged-ephemeron-descriptors #'map-ephemeron-descriptors)
             model object (lambda (id key value clear-p ck cv)
                            (push (list id clear-p ck cv (load-reference model key)
                                        (load-reference model value)) eph)))
    (list weak eph)))
(defun staged-case (starts)
  (let* ((size 32) (alignment 8) (size-calls 0) (alignment-calls 0)
         (variable (clamsara::make-host-variable-size-rule :header-bytes 16 :element-bytes 8 :maximum-elements 4))
         (fixed-token nil) (array-token nil)
         (world (make-quality-world :object-starts starts :extent 512
           :configure-model
           (lambda (offer)
             (setf fixed-token
               (make-object-kind-description offer :fixed-stage
                 :size-rule (lambda (kind) (declare (ignore kind)) (incf size-calls) size)
                 :alignment-rule (lambda (kind) (declare (ignore kind)) (incf alignment-calls) alignment)
                 :strong-layout '(:edge)
                 :weak-descriptions (list (make-weak-location-description offer '(:identity :weak :offset 8) :quality-node :wc))
                 :ephemeron-descriptions
                 (list (make-ephemeron-description offer
                         (clamsara::make-host-ephemeron-location-description :identity :pair :key-offset 16 :value-offset 24)
                         t :kc :vc))))
             (setf array-token
               (make-object-kind-description offer :array-stage :size-rule variable
                 :alignment-rule 16 :strong-layout '(:indexed :base-offset 16))))))
         (model (world-model world))
         (reserve (find :reserve (clamsara::%plan-spaces (world-plan world)) :key #'clamsara::%semispace-role))
         (map (space-object-start-map reserve))
         (address (clamsara::%space-base reserve))
         (alias-count (check-catalogue-account world)))
    (check (and (= 1 size-calls) (= 1 alignment-calls)) "Staging kind not captured at binding")
    ;; Caller input changes before the first object allocation.
    (setf size 48 alignment 32
          (clamsara::host-variable-size-rule-element-bytes variable) 16)
    (let ((fixed (allocated world :fixed-stage 32 8))
          (array (allocated world :array-stage 48 16)))
      (set-world-root world 0 fixed) (set-world-root world 1 array)
      (set-node-slot world fixed 0 (allocate-node world 301))
      (set-node-slot world array 3 (allocate-node world 302))
      (dolist (spec (list (list fixed fixed-token 32 '(:edge))
                         (list array array-token 48 '(0 1 2 3))))
        (destructuring-bind (source token bytes ids) spec
          (let ((source-values (loop for id in ids collect (location-value model source id)))
                (conditional (conditional-info model source nil)))
            (multiple-value-bind (stage used) (copy-object-to-staging model source 0 bytes)
              (check (= used bytes) "Stage size changed")
              (check-equal ids (strong-ids model stage t))
              (check-equal conditional (conditional-info model stage t))
              (check (every #'eq source-values
                            (loop for id in ids collect (location-value model stage id t)))
                     "Staged edges differ")
              (let ((destination (initialize-object model address token bytes token))
                    (handles nil))
                (when (eq source fixed)
                  (dolist (key '((:strong :edge) (:weak :weak) (:ephemeron-key :pair) (:ephemeron-value :pair)))
                    (multiple-value-bind (handle status reason)
                        (make-staged-reference-location-handle model stage (first key) (second key) destination)
                      (check (and handle (eq status :complete) (null reason)) "Stage handle rejected ~S" key)
                      (check (eq :stale (call-with-reference-location model handle
                                             (lambda (location) (declare (ignore location)) (error "Early resolution"))))
                             "Handle resolved before publication")
                      (push handle handles))))
                (install-staged-object model stage destination)
                (metadata-set map address 1)
                (check (and (eq token (object-kind model destination))
                            (= bytes (object-size model destination))) "Installed kind identity/size changed")
                (check-equal ids (strong-ids model destination))
                (check-equal conditional (conditional-info model destination nil))
                (check (every #'eq source-values (loop for id in ids collect (location-value model destination id)))
                       "Installed staged edges differ")
                (dolist (handle handles)
                  (check (eq :present (call-with-reference-location model handle
                                           (lambda (location) (load-reference model location))))
                         "Installed handle missing"))
                ;; Only temporary model-test destination is unpublished/retired.
                ;; Real root/source objects are unchanged and collected below.
                (metadata-reset map address)
                (clamsara::runtime-retire-object-representation model destination)
                (dolist (handle handles)
                  (check (eq :stale (call-with-reference-location model handle
                                           (lambda (location) (declare (ignore location)) (error "Retired handle resolved"))))
                         "Handle survived retirement")))))))
      (complete world 4)
      (check (and (= 301 (read-node-slot world (read-node-slot world (read-world-root world 0) 0) 0))
                  (= 302 (read-node-slot world (read-node-slot world (read-world-root world 1) 3) 0))
                  (= 1 size-calls) (= 1 alignment-calls)
                  (= alias-count (check-catalogue-account world))) "Stage/collection changed snapshot")
      (close-quality-world world)
      (incf *case-count*) (event :staging-pass starts :fixed-calls (list size-calls alignment-calls)))))

(defun prebinding-mutation-case (algorithm starts field value)
  (let ((made nil) (rejection nil))
    (handler-case
        (setf made
          (make-quality-world :algorithm algorithm :object-starts starts :extent 512
            :configure-model
            (lambda (offer)
              (let ((rule (clamsara::make-host-variable-size-rule :header-bytes 16 :element-bytes 8
                            :minimum-elements 1 :maximum-elements 4)))
                (make-object-kind-description offer :invalidated :size-rule rule :alignment-rule 16
                  :strong-layout '(:indexed :base-offset 16))
                ;; This is the caller's input record, not an opaque output.
                (ecase field
                  (:header (setf (clamsara::host-variable-size-rule-header-bytes rule) value))
                  (:element (setf (clamsara::host-variable-size-rule-element-bytes rule) value))
                  (:minimum (setf (clamsara::host-variable-size-rule-minimum-elements rule) value))
                  (:maximum (setf (clamsara::host-variable-size-rule-maximum-elements rule) value))
                  (:kind (setf (clamsara::host-variable-size-rule-element-kind rule) value)))))))
      (clamsara::construction-rejected (condition)
        (setf rejection (clamsara::construction-rejection-reason condition))))
    (when made (close-quality-world made))
    (check (eq rejection :bind-object-model-signaled)
           "Prebinding invalidation ~S/~S did not reject at binding: ~S" field value rejection)
    (incf *case-count*) (event :prebinding-invalid-pass algorithm starts field value rejection)))

(defun run-kind-history-tests ()
  (let ((*case-count* 0))
    (dolist (algorithm '(:semispace :marksweep))
      (dolist (starts '(:packed :scalar))
        (shared-binding-case algorithm starts)
        (dolist (change '((:header -1) (:header 24) (:element 0) (:element 16)
                          (:minimum -1) (:maximum 0) (:kind :numeric)))
          (prebinding-mutation-case algorithm starts (first change) (second change)))))
    (alias-rejection-case)
    (staged-case :packed)
    (staged-case :scalar)
    (event :independent-geometry-finished :cases *case-count*)
    (check (= 35 *case-count*) "Independent geometry case count changed")
    t))
