;;;; Parent-owned implementation checks, separate from the independent matrix.
(in-package #:clamsara.quality.reference-variants)

(defun directory-state (model)
  (list (copy-seq (clamsara::host-model-variant-code-keys model))
        (copy-seq (clamsara::host-model-variant-code-rows model))
        (clamsara::host-model-variant-count model)
        (clamsara::host-model-variant-publishing-p model)
        (map 'list #'reference-fields (clamsara::host-model-variants model))))

(defun directory-history (algorithm starts)
  (let* ((cells (expected-cells algorithm 16))
         (codes (append (loop for tag from 1 to 4 collect (+ #x20000000 tag))
                        (loop for offset from 1 to 8 collect (+ #x10000000 offset))
                        (loop for tag from 1 to 4 append
                          (loop for offset in '(1 8)
                                collect (+ #x30000000 (ash tag 20) offset)))))
         (world (make-row-world :algorithm algorithm :starts starts
                               :variant-capacity (+ (* (length codes) cells) 3)))
         (model (world-model world)))
    (multiple-value-bind (parent child first) (graph world (first codes))
      (declare (ignore child first))
      (loop for code in codes for count from 1 do
        (assert-reference model (rebuild-reference model parent code) parent code)
        (check (= (* count cells) (clamsara::host-model-variant-count model))
               "New canonical code did not reserve exactly C records"))
      ;; The chosen tags/interiors share initial hash buckets. This exercises
      ;; collisions, not merely distinct successful inserts into empty buckets.
      (let* ((keys (clamsara::host-model-variant-code-keys model))
             (mask (1- (length keys)))
             (buckets (loop for key across keys unless (= key -1)
                            collect (logand (logxor key (ash key -18)) mask))))
        (check (< (length (remove-duplicates buckets)) (length buckets))
               "Directory history failed to exercise collisions"))
      (let ((before (directory-state model)))
        (require-rebuild-rejection model parent #x1000001f)
        (check (equalp before (directory-state model))
               "Rejected code changed directory, guard or immutable records")
        (check (eq (rebuild-reference model parent #x20000001)
                   (rebuild-reference model parent #x20010001))
               "Alias did not reuse directory code")
        (complete-cycles world (first codes))
        (multiple-value-bind (now ignored)
            (normalize-reference model (read-world-root world 0))
          (declare (ignore ignored))
          (dolist (code codes)
            (assert-reference model (rebuild-reference model now code) now code)))
        (check (equalp before (directory-state model))
               "Alias/correction changed directory or immutable row records")))
    (close-successful-world world)))

(defun run-row-directory-tests ()
  (setf *passed* 0 *failed* 0 *results* nil *preserved-failures* nil)
  (dolist (algorithm '(:semispace :marksweep))
    (dolist (starts '(:packed :scalar))
      (run-case (list :directory algorithm starts)
                (lambda () (directory-history algorithm starts)))))
  (event :directory-finished :passed *passed* :failed *failed*)
  (when (plusp *failed*)
    (error "Variant directory checks failed: ~D failures" *failed*))
  t)
