;;;; Independent fixed-snapshot edge/account regressions.
;;;; Original MAPCAR-on-vector harness failure is preserved in review evidence.
(in-package #:clamsara.quality.reference-variants)
(defun account-index (world)
  (let ((owners (make-hash-table :test #'eq))
        (construction (clamsara::configuration-construction-context (world-configuration world))))
    (maphash
      (lambda (id state)
        (let* ((resource (clamsara::%resource-state-release-capability state))
               (manifest (clamsara::%simulator-resource-manifest resource))
               (handle (clamsara::%simulator-resource-handle resource))
               (padding (clamsara::%simulator-resource-physical-padding resource))
               (reserve (clamsara::%simulator-resource-auxiliary-reserve resource))
               (aux (+ (clamsara::%host-object-storage resource)
                       (clamsara::%host-object-storage manifest)
                       (clamsara::%host-object-storage reserve)))
               (entry (find id (clamsara::%configuration-capacity-account (world-configuration world))
                        :test #'eql :key #'clamsara::%capacity-account-entry-identity)))
          (check (and (clamsara::%simulator-resource-closed-p resource)
                      (null (clamsara::%simulator-resource-manifest-seen resource)))
                 "Unclosed resource")
          (loop for object across manifest do
            (check (not (gethash object owners)) "Duplicate manifest object")
            (setf (gethash object owners) id)
            (incf aux (clamsara::%host-object-storage object)))
          (check (= aux (clamsara::%resource-state-auxiliary-bytes state)
                        (clamsara::%capacity-account-entry-auxiliary-bytes entry))
                 "Auxiliary charge mismatch")
          (check (= (+ (clamsara::%host-object-storage handle)
                       (if padding (clamsara::%host-object-storage padding) 0))
                    (clamsara::%resource-state-physical-bytes state)
                    (clamsara::%capacity-account-entry-physical-bytes entry))
                 "Physical charge mismatch")))
      (clamsara::%context-resources construction))
    owners))

(defun row-directory-state (model)
  (list (copy-seq (clamsara::host-model-variant-code-keys model))
        (copy-seq (clamsara::host-model-variant-code-rows model))
        (clamsara::host-model-variant-count model)
        (clamsara::host-model-variant-publishing-p model)
        (map 'list #'reference-fields (clamsara::host-model-variants model))))
(defun account-value (world)
  (map 'list (lambda (entry)
            (list (clamsara::%capacity-account-entry-identity entry)
                  (clamsara::%capacity-account-entry-physical-bytes entry)
                  (clamsara::%capacity-account-entry-auxiliary-bytes entry)))
          (clamsara::%configuration-capacity-account (world-configuration world))))
(defun assert-row-account (world)
  (let* ((model (world-model world)) (owners (account-index world))
         (required (list model (clamsara::host-model-variants model)
                         (clamsara::host-model-variant-code-keys model)
                         (clamsara::host-model-variant-code-rows model))))
    (loop for reference across (clamsara::host-model-variants model) do (push reference required))
    (dolist (object required) (check (gethash object owners) "Uncharged row/directory backing"))
    (event :exact-row-account :required (length required)
           :h (length (clamsara::host-model-variants model))
           :reserved (clamsara::host-model-variant-count model))
    (account-value world)))
(defun reject-with-directory-check (model base code)
  (let ((before (row-directory-state model)))
    (require-rebuild-rejection model base code)
    (check (equalp before (row-directory-state model)) "Rejection changed directory or publication guard")))

(defun holes-case (algorithm starts g)
  (let* ((c (expected-cells algorithm g))
         (world (make-row-world :algorithm algorithm :starts starts :granularity g :variant-capacity c))
         (model (world-model world))
         (kind (object-kind-descriptor model :row-large))
         (small-kind (object-kind-descriptor model :row-small))
         (account (assert-row-account world)))
    (multiple-value-bind (source status reason) (allocate-object (world-context world) :row-large 64 16 kind)
      (check (and source (eq status :allocated) (null reason)) "Large real allocation failed")
      (clamsara::host-object-payload-write model source 63 #xD5)
      ;; Invalid forms must not consume the only row, even before first admission.
      (dolist (bad '(#x10000000 #x20000000 #x30000000 #x40000000 -1 :bad))
        (reject-with-directory-check model source bad))
      (let* ((code #x1000001f) (reference (rebuild-reference model source code))
             (row (row-directory-state model)))
        (set-world-root world 0 reference)
        (check (= c (clamsara::host-model-variant-count model)) "First code did not reserve C")
        (loop for base in (row-bases world) do
          (let* ((address (+ base 512 -16))
                 ;; A valid unexposed base, but displacement31 cannot fit here.
                 (small (initialize-object model address small-kind 16 small-kind)))
            (reject-with-directory-check model small code)
            (check (equalp row (row-directory-state model)) "Invalid endpoint lookup rewrote row holes")
            (clamsara::runtime-retire-object-representation model small)))
        (reject-with-directory-check model source #x20000001)
        (dotimes (round 3)
          (let ((record (collect-world world)))
            (check (and (eq :complete (cycle-result-status record))
                        (= 1 (cycle-result-count record :objects-discovered)))
                   "Hole-history real collection failed")
            (multiple-value-bind (base actual) (normalize-reference model (read-world-root world 0))
              (check (and (= code actual) (= 64 (object-size model base))
                          (= #xD5 (clamsara::host-object-payload-read model base 63)))
                     "Hole-history reference/payload changed"))))
        (check (equalp row (row-directory-state model)) "Existing-code movement changed row storage")
        (check (equal account (assert-row-account world)) "Materialization changed fixed account")))
    (close-successful-world world)))

(defun make-wide-world (algorithm starts)
  ;; The 1MiB leaf tests maximum tagged-interior descriptor fields without
  ;; allocating a huge dense small-quantum record domain. It has four cells.
  ;; This is an explicit independent geometry, not a changed benchmark offer.
  (let* ((q (ash 1 20)) (base q) (extent (* 2 q))
         (space-count (if (eq algorithm :semispace) 2 1))
         (cells (* 2 space-count))
         (roots (make-simulator-root-client :provider-capacity 4))
         (provider (make-simulator-root-provider 3))
         (token (register-root-provider roots :wide-roots 3 provider))
         (coordinator (make-simulator-coordinator roots :stop-capacity 16 :await-bound 8))
         (arena (make-simulator-address-space :base base :byte-extent (* space-count extent)
                  :alignment q :page-size q :coordinator coordinator))
         (offer (make-host-object-model :capacity cells :variant-capacity (* 3 cells)
                   :kind-capacity 2 :slot-capacity 1 :location-capacity 2
                   :handle-capacity 2 :stage-capacity 1 :max-object-bytes q
                   :max-interior-displacement (1- q) :tag-capacity 65535))
         (kind (make-object-kind-description offer :wide-leaf :size-rule q :alignment-rule q))
         (diagnostics (make-simulator-diagnostics))
         (clients (make-simulator-clients :model offer :roots roots :coordinator coordinator
                    :address-space arena :atomics (make-host-atomics) :diagnostics diagnostics))
         (registry (make-sequential-finalizer-registry :capacity 2 :root-client roots))
         (domain0 (make-metadata-domain :base base :limit (+ base extent) :granularity q))
         (map0 (ecase starts (:packed (make-object-start-marks :domain domain0))
                            (:scalar (make-scalar-object-start-marks :domain domain0))))
         (from (if (eq algorithm :semispace)
                   (make-semispace-space :name :wide-from :object-start-map map0
                     :forwarding (make-side-forwarding :domain domain0) :extent extent
                     :packing-quantum q :role :allocation)
                   (make-marksweep-space :name :wide-only :object-start-map map0
                     :marks (make-side-marks :domain domain0) :extent extent
                     :packing-quantum q :descriptor-capacity cells)))
         (to (when (eq algorithm :semispace)
               (let* ((domain1 (make-metadata-domain :base (+ base extent)
                                :limit (+ base (* 2 extent)) :granularity q))
                      (map1 (ecase starts (:packed (make-object-start-marks :domain domain1))
                                          (:scalar (make-scalar-object-start-marks :domain domain1)))))
                 (make-semispace-space :name :wide-to :object-start-map map1
                   :forwarding (make-side-forwarding :domain domain1) :extent extent
                   :packing-quantum q :role :reserve))))
         (plan (if to
                   (make-semispace-plan :from-space from :to-space to :root-client roots
                     :coordinator coordinator :diagnostics diagnostics :registry registry
                     :trace-capacity 8 :conditional-capacity 4 :finalizer-capacity 2 :packing-quantum q)
                   (make-marksweep-plan :space from :root-client roots :coordinator coordinator
                     :diagnostics diagnostics :registry registry :trace-capacity 8
                     :conditional-capacity 4 :finalizer-capacity 2 :packing-quantum q)))
         (configuration (construct-plan plan clients))
         (context (bind-mutator configuration :wide :default))
         (world (clamsara.quality.support::%make-quality-world
                  :algorithm algorithm :object-starts starts :packing-quantum q
                  :configuration configuration :context context :model (configuration-object-model configuration)
                  :roots roots :root-token token :root-provider provider :root-count 3
                  :coordinator coordinator :plan plan :registry registry :space from :node-kind kind)))
    (push world *case-worlds*)
    (check (= cells (length (clamsara::host-model-sizes (world-model world)))) "Wide C mismatch")
    world))
(defun maximum-code-case (algorithm starts)
  (let* ((world (make-wide-world algorithm starts)) (model (world-model world))
         (q (world-packing-quantum world))
         (account (assert-row-account world))
         (codes '(#x2000ffff #x100fffff #x3fffffff)))
    (multiple-value-bind (source status reason)
        (allocate-object (world-context world) :wide-leaf q q (world-node-kind world))
      (check (and source (eq status :allocated) (null reason)) "Wide leaf allocation failed")
      (clamsara::host-object-payload-write model source 0 #xA9)
      (clamsara::host-object-payload-write model source (1- q) #xE7)
      (dolist (bad '(#x30000001 #x3ff00000 #x10100000 #x40000000))
        (reject-with-directory-check model source bad))
      (loop for code in codes for root from 0 do
        (let ((reference (rebuild-reference model source code)))
          (assert-reference model reference source code)
          (set-world-root world root reference)))
      (check (eq (read-world-root world 0) (rebuild-reference model source #x2fffffff))
             "Maximum tagged-base alias created another code")
      (let ((row (row-directory-state model)) (old-address (reference-address model source)))
        (reject-with-directory-check model source #x20000001)
        (dotimes (round 3)
          (let ((record (collect-world world)))
            (check (and (eq :complete (cycle-result-status record))
                        (= 1 (cycle-result-count record :objects-discovered))
                        (= (if (eq algorithm :semispace) 1 0)
                           (cycle-result-count record :objects-moved)))
                   "Maximum-form real cycle failed")
            (loop for code in codes for root from 0 do
              (multiple-value-bind (base actual) (normalize-reference model (read-world-root world root))
                (assert-reference model (read-world-root world root) base code)
                (check (and (= code actual) (= q (object-size model base))
                            (= #xA9 (clamsara::host-object-payload-read model base 0))
                            (= #xE7 (clamsara::host-object-payload-read model base (1- q))))
                       "Maximum form lost bytes/tag/displacement")))
            (let ((new-address (reference-address model (normalize-reference model (read-world-root world 0)))))
              (check (if (eq algorithm :semispace) (/= old-address new-address) (= old-address new-address))
                     "Maximum form wrong address history")
              (setf old-address new-address))))
        (check (equalp row (row-directory-state model)) "Maximum-form collection changed ready rows"))
      (check (equal account (assert-row-account world)) "Maximum-form row changed accounted storage"))
    (close-successful-world world)))
(defun run-additional-row-checks ()
  (setf *passed* 0 *failed* 0 *results* nil *preserved-failures* nil)
  (dolist (algorithm '(:semispace :marksweep))
    (dolist (starts '(:packed :scalar))
      (dolist (g '(8 16))
        (run-case (list :endpoint-holes algorithm starts g)
                  (lambda () (holes-case algorithm starts g))))
      (run-case (list :maximum-canonical-fields algorithm starts)
                (lambda () (maximum-code-case algorithm starts)))))
  (event :additional-finished :passed *passed* :failed *failed*)
  (when (plusp *failed*) (error "Additional row checks failed: ~D failures" *failed*))
  t)
