(in-package #:clamsara.list-next.draft.v2)
(defvar *baseline-results* nil)
(defvar *baseline-active-case* nil)
(defvar *baseline-pre-unwind* nil)
(defun baseline-owner-scalar (o)
  (let* ((rt (owner-runtime o)) (p (owner-provider o))
         (config (and rt (clamsara::workload-runtime-configuration rt)))
         (token (and rt (clamsara::workload-runtime-root-token rt)))
         (v (and p (clamsara::workload-provider-vm p))))
    (list :name (owner-name o) :phase (owner-phase o) :runtime (not (null rt))
          :configuration (and config (clamsara::%configuration-state config))
          :token-active (and token (clamsara::simulator-provider-token-active-p token))
          :condition (and (owner-condition o) (type-of (owner-condition o)))
          :expected-condition (and (owner-expected-condition o)
                                   (type-of (owner-expected-condition o)))
          :frame-count (and p (clamsara::workload-provider-frame-count p))
          :native-count (and p (clamsara::workload-provider-native-cell-count p))
          :frames (and p (length (clamsara::workload-provider-functions p)))
          :saved (and p (length (clamsara::workload-provider-saved-values p)))
          :cells (and p (length (clamsara::workload-provider-native-cells p)))
          :vm-stack-top (and v (maclina.vm-cross::vm-stack-top v))
          :vm-frame-pointer (and v (maclina.vm-cross::vm-frame-pointer v))
          :vm-pc (and v (maclina.vm-cross::vm-pc v))
          :vm-args (and v (maclina.vm-cross::vm-args v))
          :vm-arg-count (and v (maclina.vm-cross::vm-arg-count v))
          :allocations-observed (owner-allocations o) :stores-observed (owner-stores o)
          :case-rooted (owner-rooted-p o) :spec (owner-construction-spec o))))
(defun baseline-attempt (name thunk &optional diagnostic)
  (let ((*baseline-active-case* name) (before *owners*))
    (format t "~&LIST-BASELINE-BEGIN ~S~%" name)
    (handler-case
        (handler-bind
            ((error
               (lambda (c)
                 ;; Scalars only; never read guest payload or collect here.
                 (let* ((o (and (not (eq before *owners*)) (first *owners*)))
                        (row (list :case name :type (type-of c)
                                   :context (and o (baseline-owner-scalar o)))))
                   (push row *baseline-pre-unwind*)
                   (let ((*print-level* 8) (*print-length* 60))
                     (format t "~&LIST-BASELINE-PRE-UNWIND ~S~%" row))
                   (sb-debug:print-backtrace :count 12 :stream *standard-output*)))))
          (let ((o (funcall thunk)))
            (if diagnostic
                (progn
                  (assert (eq :payload-rejected-retained (owner-phase o)))
                  (assert (owner-condition o))
                  (assert (retained-p o)))
                (progn
                  (assert (eq :complete (owner-phase o)))
                  (assert (null (owner-condition o)))
                  (assert (null (clamsara::workload-runtime-configuration
                                  (owner-runtime o))))))
            (push (list :case name :status (if diagnostic :diagnostic-only :pass)
                        :owner (baseline-owner-scalar o)) *baseline-results*)
            (format t "~&LIST-BASELINE-RESULT ~S~%" (first *baseline-results*))))
      (error (c)
        (let ((*print-level* 8) (*print-length* 60)
              (o (and (not (eq before *owners*)) (first *owners*))))
          (push (list :case name :status :fail :type (type-of c)
                      :condition (princ-to-string c)
                      :owner (and o (baseline-owner-scalar o))) *baseline-results*)
          (format t "~&LIST-BASELINE-RESULT ~S~%" (first *baseline-results*)))))))

;; Required order: seven separately attempted behavior cases first.
(dolist (kind '(:empty :one :many :order :identity :moving :mapc-nested))
  (baseline-attempt (list :behavior kind) (lambda () (run-behavior kind))))
;; Private N+2 proposal, not normative CL minimum capacities.
(baseline-attempt '(:capacity 0 :arena :exact nil)
  (lambda () (run-capacity 0 :arena :exact)))
(dolist (resource '(:arena :functions :saved))
  (dolist (boundary '(:exact :one-short))
    (dolist (nested '(nil t))
      (baseline-attempt (list :capacity 17 resource boundary nested)
        (lambda () (run-capacity 17 resource boundary :nested nested))))))
(baseline-attempt '(:host-payload-diagnostic)
  #'run-host-payload-rejection t)

(format t "~&LIST-BASELINE-SUMMARY attempted=~D passes=~D failures=~D diagnostics=~D owners=~D~%"
        (length *baseline-results*)
        (count :pass *baseline-results* :key (lambda (r) (getf r :status)))
        (count :fail *baseline-results* :key (lambda (r) (getf r :status)))
        (count :diagnostic-only *baseline-results* :key (lambda (r) (getf r :status)))
        (length *owners*))
(dolist (o (reverse *owners*))
  (let ((*print-level* 8) (*print-length* 60))
    (format t "~&LIST-BASELINE-OWNER ~S~%" (baseline-owner-scalar o))))
(with-open-file (s #p"/tmp/clamsara-mapc-draft-wd3ba0th/independent-review/list-rest-next/list-native-v2-baseline-95p03oqo/results.sexp" :direction :output :if-exists :error)
  (let ((*print-readably* t) (*print-pretty* nil))
    (write (reverse *baseline-results*) :stream s) (terpri s)))
(with-open-file (s #p"/tmp/clamsara-mapc-draft-wd3ba0th/independent-review/list-rest-next/list-native-v2-baseline-95p03oqo/owners.sexp" :direction :output :if-exists :error)
  (let ((*print-readably* t) (*print-pretty* nil))
    (write (mapcar #'baseline-owner-scalar (reverse *owners*)) :stream s) (terpri s)))
;; Strict baseline: expected-red behavior/capacity is still a FAILURE exit.
(assert (= 21 (length *baseline-results*)))
(assert (notany (lambda (r) (eq :fail (getf r :status))) *baseline-results*))
(assert (= 20 (count :pass *baseline-results* :key (lambda (r) (getf r :status)))))
(assert (= 1 (count :diagnostic-only *baseline-results* :key (lambda (r) (getf r :status)))))
(format t "~&LIST-BASELINE-ACCEPTED positive=20 diagnostic-only=1~%")
