(require :asdf)
(push #p"/tmp/clamsara-variant-row-review-bnum_11t/" asdf:*central-registry*)
(asdf:initialize-output-translations '(:output-translations (t #p"/tmp/clamsara-variant-row-review-bnum_11t/independent-review/row-source-review/fasl/") :ignore-inherited-configuration))
(assert (equal (truename #p"/tmp/clamsara-variant-row-review-bnum_11t/") (truename (asdf:system-source-directory :clamsara))))
(format t "~&SOURCE ~A~%" (asdf:system-source-directory :clamsara))
(asdf:load-system :clamsara/quality/support)
(asdf:load-system :clamsara/generational)
(load #p"/tmp/clamsara-variant-row-review-bnum_11t/independent-review/row-source-review/independent-fixture.lisp")
(load #p"/tmp/clamsara-variant-row-review-bnum_11t/independent-review/row-source-review/independent-generational.lisp")
(load #p"/tmp/clamsara-variant-row-review-bnum_11t/independent-review/row-source-review/independent-cases.lisp")
(load #p"/tmp/clamsara-variant-row-review-bnum_11t/independent-review/row-source-review/additional-checks-02.lisp")
(whole-code-row-acceptance:run-row-acceptance)
(whole-code-row-acceptance::run-additional-row-checks)
(format t "~&INDEPENDENT-ROW-FINISHED cases=120~%")
