(in-package #:whole-code-row-acceptance)
(defun rejected-binding (algorithm starts granularity h &optional model-capacity)
  (let ((*observation* (make-observation)) (caught nil))
    (handler-case
        (make-row-world :algorithm algorithm :starts starts :granularity granularity
                        :variant-capacity h :model-capacity model-capacity)
      (clamsara::construction-rejected (condition) (setf caught condition)))
    (check caught "Positive H<C was not rejected at binding")
    (check (eq :bind-object-model-signaled (clamsara::construction-rejection-reason caught))
           "Wrong construction rejection boundary/reason: ~S" caught)
    (assert-builder-released *observation*)))
(defun boundary-case (algorithm starts granularity h)
  (let ((c (expected-cells algorithm granularity)))
    (cond
      ((< 0 h c) (rejected-binding algorithm starts granularity h))
      (t
       (let* ((world (make-row-world :algorithm algorithm :starts starts
                        :granularity granularity :variant-capacity h))
              (model (world-model world)))
         (multiple-value-bind (parent child first) (graph world (if (zerop h) 0 #x20000001))
           (declare (ignore child))
           (cond
             ((zerop h)
              (require-rebuild-rejection model parent #x20000001)
              (complete-cycles world 0))
             (t
              (let ((before (model-state model)))
                (check (eq first (rebuild-reference model parent #x20010001))
                       "Tagged-base descriptor alias spent a distinct code or changed encoding")
                (check (equalp before (model-state model)) "Alias changed model state"))
              (if (< h (* 2 c))
                  (require-rebuild-rejection model parent #x10000008)
                  (let ((second (rebuild-reference model parent #x10000008)))
                    (assert-reference model second parent #x10000008)
                    (set-world-root world 1 second)
                    ;; A tail of 3<C is not a third complete row.
                    (require-rebuild-rejection model parent #x20000002)))
              (complete-cycles world #x20000001)
              (when (>= h (* 2 c)) (verify-graph world #x10000008 1)))))
         (close-successful-world world))))))
(defun history-case (algorithm starts granularity code &optional reserve-granularity)
  (let* ((rg (or reserve-granularity granularity))
         (c (expected-cells algorithm granularity rg))
         (world (make-row-world :algorithm algorithm :starts starts :granularity granularity
                   :reserve-granularity rg :variant-capacity c)))
    (graph world code)
    (complete-cycles world code)
    (close-successful-world world)))

;; Direct public model initialization/publication visits EVERY descriptor cell,
;; including fine-granularity cells not selected by the ordinary 16-byte allocator.
;; These are model-domain tests, not invented collector allocation histories.
(defun every-cell-case (algorithm starts granularity &optional reserve-granularity)
  (let* ((rg (or reserve-granularity granularity))
         (c (expected-cells algorithm granularity rg))
         (world (make-row-world :algorithm algorithm :starts starts :granularity granularity
                   :reserve-granularity rg :variant-capacity (* 2 c)))
         (model (world-model world)) (saved (make-hash-table :test #'eql))
         (visited 0))
    (dotimes (round 2)
      (setf visited 0)
      (loop for map in (row-maps world) for base in (row-bases world)
            for g in (row-granularities world) do
        (loop for address from base below (+ base 512) by g do
          (let* ((kind (object-kind-descriptor model (if (= g 8) :row-cell8 :row-cell16)))
                 (start (initialize-object model address kind g kind)))
            (metadata-set map address 1)
            (let* ((tag (rebuild-reference model start #x20000001))
                   (interior (rebuild-reference model start #x10000001)))
              (assert-reference model tag start #x20000001)
              (assert-reference model interior start #x10000001)
              (check (eq tag (rebuild-reference model start #x20010001)) "Alias changed per-cell encoding")
              (if (zerop round)
                  (setf (gethash address saved)
                        (list tag interior (reference-fields tag) (reference-fields interior)))
                  (let ((old (gethash address saved)))
                    (check (and (eq tag (first old)) (eq interior (second old))
                                (equal (third old) (reference-fields tag))
                                (equal (fourth old) (reference-fields interior)))
                           "Address reuse changed an immutable encoding"))))
            (incf visited)
            (metadata-reset map address)
            (clamsara::runtime-retire-object-representation model start))))
      (check (= c visited) "Did not visit every actual descriptor cell")
      (maphash (lambda (address old)
                 (declare (ignore address))
                 (check (and (equal (third old) (reference-fields (first old)))
                             (equal (fourth old) (reference-fields (second old))))
                        "Later cell reconstruction retargeted an older reference")) saved))
    (event :all-descriptor-cells :cells c :passes 2 :granularities (row-granularities world))
    (close-successful-world world)))

(defun future-large-case (algorithm starts granularity)
  (let* ((c (expected-cells algorithm granularity))
         (world (make-row-world :algorithm algorithm :starts starts :granularity granularity :variant-capacity c))
         (model (world-model world)) (map0 (first (row-maps world)))
         (base0 (first (row-bases world)))
         (small-kind (object-kind-descriptor model :row-small))
         (large-kind (object-kind-descriptor model :row-large))
         ;; This live cell is too small when the first code is created.
         (small (initialize-object model (+ base0 128) small-kind 16 small-kind))
         (source (allocate-node world 777)))
    (metadata-set map0 (+ base0 128) 1)
    (let* ((code #x10000018) (first (rebuild-reference model source code))
           (first-fields (reference-fields first)))
      (assert-reference model first source code)
      (set-world-root world 0 first)
      (metadata-reset map0 (+ base0 128))
      (clamsara::runtime-retire-object-representation model small)
      (loop for map in (row-maps world) for base in (row-bases world) do
        (let* ((address (+ base 128))
               (large (initialize-object model address large-kind 64 large-kind))
               (value (rebuild-reference model large code)))
          ;; Includes an initially inactive reserve cell for SemiSpace.
          (check (valid-reference-p model value) "Unexposed future reference not admitted")
          (check (= (+ address 24) (clamsara::simulator-reference-address value))
                 "Future larger destination lost displacement")
          (metadata-set map address 1)
          (assert-reference model value large code)
          (check (equal first-fields (reference-fields first)) "New destination retargeted source encoding")
          (metadata-reset map address)
          (clamsara::runtime-retire-object-representation model large)))
      ;; Cells near the fixed range end cannot fit this interior form. They
      ;; remain charged: unused holes do not buy even one new canonical code.
      (require-rebuild-rejection model source #x20000001))
    (close-successful-world world)))

(defun staged-case (algorithm starts granularity)
  (let* ((c (expected-cells algorithm granularity))
         (world (make-row-world :algorithm algorithm :starts starts :granularity granularity :variant-capacity c))
         (model (world-model world)) (code #x10000008))
    (multiple-value-bind (source child original) (graph world code)
      (declare (ignore original))
      (let* ((map (car (last (row-maps world))))
             (address (+ (car (last (row-bases world))) 128))
             (kind (object-kind-descriptor model :quality-node))
             (destination (initialize-object model address kind 32 kind))
             (moved (rebuild-reference model destination code)))
        (check (valid-reference-p model moved) "Unpublished encoding is not admitted")
        (let ((caught nil))
          (handler-case (normalize-reference model moved) (error (condition) (setf caught condition)))
          (check caught "Unexposed destination incorrectly normalized as published"))
        (multiple-value-bind (stage used) (copy-object-to-staging model source 0 32)
          (check (= used 32) "Stage lost source size")
          (map-staged-reference-locations model stage
            (lambda (identity location)
              (when (eq identity :left)
                (store-reference-raw model location (rebuild-reference model child code)))))
          (install-staged-object model stage destination))
        (metadata-set map address 1)
        (assert-reference model moved destination code)
        (set-world-root world 1 moved)
        (verify-graph world code 1 code)
        (verify-graph world code 0 0)
        ;; Successful model staging fixture cleanup only. A failure above never
        ;; reaches these operations and its real roots/world remain unchanged.
        (set-world-root world 1 nil)
        (metadata-reset map address)
        (clamsara::runtime-retire-object-representation model destination))
      (complete-cycles world code)
      (close-successful-world world))))

(defun run-case (name function)
  (let ((*case-name* name) (*case-worlds* nil))
    (event :begin name)
    (handler-case
        (progn (funcall function) (incf *passed*)
               (push (list name :pass) *results*) (event :pass name))
      (error (condition)
        (incf *failed*)
        (push (list name :fail (princ-to-string condition)) *results*)
        (push (list :case name :condition condition :worlds *case-worlds*) *preserved-failures*)
        ;; No blanket unwind cleanup: failed worlds are diagnostic evidence.
        (event :fail name :condition (princ-to-string condition)
               :preserved-worlds (length *case-worlds*))))))
(defun run-row-acceptance ()
  (setf *passed* 0 *failed* 0 *results* nil *preserved-failures* nil)
  (dolist (algorithm '(:semispace :marksweep))
    (dolist (starts '(:packed :scalar))
      (dolist (g '(16 8))
        (let ((c (expected-cells algorithm g)))
          (dolist (h (list 0 1 (1- c) c (1- (* 2 c)) (* 2 c) (+ (* 2 c) 3)))
            (run-case (list :boundary algorithm starts :granularity g :c c :h h)
                      (lambda () (boundary-case algorithm starts g h)))))
        (dolist (code '(#x20000001 #x10000008))
          (run-case (list :history algorithm starts g code)
                    (lambda () (history-case algorithm starts g code))))
        (run-case (list :all-cells algorithm starts g)
                  (lambda () (every-cell-case algorithm starts g)))
        (run-case (list :future-large algorithm starts g)
                  (lambda () (future-large-case algorithm starts g)))
        (run-case (list :staged algorithm starts g)
                  (lambda () (staged-case algorithm starts g))))
      ;; Independent known rejected-bind control proves the observation path
      ;; really sees native acquisition/release even on the frozen RED baseline.
      (run-case (list :observer-control algorithm starts)
        (lambda () (let ((c (expected-cells algorithm 8)))
                     (rejected-binding algorithm starts 8 c (1- c)))))))
  (dolist (starts '(:packed :scalar))
    (run-case (list :mixed-granularity-history starts)
              (lambda () (history-case :semispace starts 8 #x10000008 16)))
    (run-case (list :mixed-granularity-all-cells starts)
              (lambda () (every-cell-case :semispace starts 8 16)))
    (dolist (code '(#x20000001 #x10000008))
      (run-case (list :generation-promotion starts code)
                (lambda () (generation-case starts code)))))
  (event :finished :passed *passed* :failed *failed*
         :preserved-worlds (loop for entry in *preserved-failures*
                                sum (length (getf entry :worlds))))
  (when *failed* (error "Whole-code-row acceptance failed: ~D requirement failures (~D passes)"
                       *failed* *passed*))
  t)
