(require :asdf)
(push #p"/tmp/clamsara-description-review-7p14doks/" asdf:*central-registry*)
(asdf:initialize-output-translations '(:output-translations (t #p"/tmp/clamsara-description-review-7p14doks/independent-review/variant-capacity/row-acceptance/fasl/") :ignore-inherited-configuration))
(assert (equal (truename #p"/tmp/clamsara-description-review-7p14doks/") (truename (asdf:system-source-directory :clamsara))))
(format t "~&SOURCE ~A~%" (asdf:system-source-directory :clamsara))
(asdf:load-system :clamsara/quality/support)
(asdf:load-system :clamsara/generational)
(load #p"/tmp/clamsara-description-review-7p14doks/independent-review/variant-capacity/row-acceptance/fixture.lisp")
(load #p"/tmp/clamsara-description-review-7p14doks/independent-review/variant-capacity/row-acceptance/generational-02.lisp")
(load #p"/tmp/clamsara-description-review-7p14doks/independent-review/variant-capacity/row-acceptance/cases.lisp")
(whole-code-row-acceptance:run-row-acceptance)
