(require :asdf)
(push #p"/home/iskam/src/vibe/Clamsara/" asdf:*central-registry*)
(assert (equal (truename #p"/home/iskam/src/vibe/Clamsara/")
               (truename (asdf:system-source-directory :clamsara))))
(asdf:load-system :clamsara/quality/support)
(asdf:load-system :clamsara/generational)
(load #p"/tmp/clamsara-description-review-7p14doks/independent-review/variant-capacity/row-acceptance/fixture.lisp")
(load #p"/tmp/clamsara-description-review-7p14doks/independent-review/variant-capacity/row-acceptance/generational-02.lisp")
(load #p"/tmp/clamsara-description-review-7p14doks/independent-review/variant-capacity/row-acceptance/cases.lisp")
(whole-code-row-acceptance:run-row-acceptance)
(format t "~&VARIANT-ROW-INDEPENDENT-GREEN-PASS~%")
