(require :asdf)
(asdf:test-system :clamsara)
(asdf:test-system :clamsara/tools/test)
(asdf:test-system :clamsara/workload/test)
(asdf:test-system :clamsara/generational/test)
(asdf:test-system :clamsara/quality/generational/test)
(asdf:load-system :clamsara/quality)
(clamsara.structure:assert-project-structure :include-optional-loaded t)
(format t "~&GENERATIONAL-CHECKPOINT-COMPONENTS-PASS~%")
