;;;; Independent native result oracle for all original FRPOLY parameter sets.
;;;; The default dependency fails; the explicit compiler candidate agrees.
;;;; This is computation only: returning NIL is not benchmark acceptance.
;;;; Run from the repository root; fixture globals are never erased for close.
(require :asdf)
(asdf:load-system :clamsara/workload)
(defpackage #:clamsara-frpoly-oracle (:use #:cl))
(let ((*package* (find-package :clamsara-frpoly-oracle)))
  (load "bench/gabriel/reference/frpoly.cl"))
(in-package :clamsara)
(defun frpoly-host-shape (value)
  (cond ((consp value) (cons (frpoly-host-shape (car value))
                             (frpoly-host-shape (cdr value))))
        ((and value (symbolp value)) (symbol-name value))
        (t value)))
(defun frpoly-guest-shape (env value)
  (cond ((%guest-cons-p env value)
         (cons (frpoly-guest-shape env (%guest-car env value))
               (frpoly-guest-shape env (%guest-cdr env value))))
        ((%guest-bignum-p env value) (%guest-bignum->host env value))
        ((and value (symbolp value)) (symbol-name value))
        (t value)))
(let* ((rt (make-workload-runtime :extent 1048576 :max-object-bytes 524288
                                  :root-capacity 1024))
       (env (workload-runtime-environment rt))
       (oracle (find-package :clamsara-frpoly-oracle))
       (cases 0) (total-moved 0))
  (workload-load env "bench/gabriel/reference/frpoly.cl")
  (dolist (degree '(2 5 10 15))
    (dolist (name '(r r2 r3))
      (let* ((native (funcall (symbol-function (find-symbol "PEXPTSQ" oracle))
                              (symbol-value (find-symbol (symbol-name name) oracle))
                              degree))
             (record (make-cycle-result-record (workload-runtime-plan rt))))
        (workload-eval env `(pexptsq ,name ,degree))
        (collect (workload-runtime-configuration rt) :all :explicit record)
        (assert (eq :complete (cycle-result-status record)))
        (format t "~&FRPOLY-ORACLE checking ~S degree=~D moved=~D~%"
                name degree (cycle-result-count record :objects-moved))
        (incf total-moved (cycle-result-count record :objects-moved))
        (let* ((vm (workload-provider-vm (workload-runtime-root-provider rt)))
               (corrected (car (maclina.vm-cross::vm-values vm))))
          (assert (equal (frpoly-host-shape native) (frpoly-guest-shape env corrected))))
        (incf cases))))
  (format t "~&FRPOLY-ORACLE cases=~D moved=~D~%" cases total-moved)
  (assert (= cases 12))
  (assert (plusp total-moved))
  ;; Run the original entry in this same environment after the independent
  ;; value comparisons. Its NIL return is not the correctness oracle.
  (format t "~&FRPOLY-ORIGINAL-ENTRY starting~%")
  (assert (equal '(nil) (multiple-value-list (workload-eval env '(testfrpoly)))))
  (format t "~&FRPOLY-ORIGINAL-ENTRY returned; polynomial oracles already checked~%")
  ;; No forced teardown: the fixture's globals are genuinely still live.
  (workload-eval env nil)
  (assert (handler-case (progn (close-workload-runtime rt) nil)
            (workload-error (condition)
              (eq :reachable-objects-not-discharged (workload-error-reason condition)))))
  (format t "FRPOLY-COMPUTATION-ONLY; live fixture globals preserved~%"))
