;;;; Clean paper-v14 API. No dependency on the legacy simulator.
(defpackage #:clamsara
  (:use #:cl)
  (:export
   #:make-metadata-domain
   #:metadata-domain
   #:scalar-side-marks
   #:make-scalar-side-marks
   #:side-forwarding
   #:make-side-forwarding
   #:object-start-marks
   #:make-object-start-marks
   #:scalar-object-start-marks
   #:make-scalar-object-start-marks
   #:make-side-marks
   #:make-epoch-marks
   #:marks-retire
   #:marks-active-p
   #:make-inline-marks
   #:make-scalar-inline-marks
   #:make-simulator-root-client
   #:make-simulator-root-provider
   #:simulator-root-location
   #:make-simulator-coordinator
   #:make-simulator-address-space
   #:make-simulator-clients
   #:make-simulator-diagnostics
   #:make-host-object-model
   #:make-host-atomics
   #:make-semispace-space
   #:make-semispace-plan
   #:make-marksweep-space
   #:make-marksweep-plan
   #:make-sequential-finalizer-registry
   #:activate-component
   #:allocate-object
   #:allocate-raw
   #:atomic-bit-clear
   #:atomic-bit-set
   #:atomic-cas
   #:atomic-fetch-add
   #:atomic-load
   #:atomic-metadata
   #:atomic-store
   #:automatic-collect
   #:await-safepoint
   #:barrier-compare-exchange
   #:barrier-contribution-admit
   #:barrier-contribution-after-exposure
   #:barrier-contribution-before-exposure
   #:barrier-contribution-cancel
   #:barrier-contribution-reserve
   #:barrier-contribution-transform
   #:barrier-read
   #:barrier-store
   #:begin-collector-checkpoint
   #:begin-trace-context
   #:bind-mutator
   #:bind-object-model
   #:bit-metadata
   #:call-with-allocation-heap
   #:call-with-reference-location
   #:cancel-finalizer
   #:cancel-movement-participant
   #:cancel-reclaim-space
   #:cas-reference-raw
   #:close-environment-heap
   #:collect
   #:collect-heaps
   #:component
   #:component-barrier-contributions
   #:component-cohort
   #:component-constraints
   #:component-dependencies
   #:component-placement-requests
   #:component-resources
   #:component-result-contributions
   #:configuration-barrier
   #:configuration-object-model
   #:construct-plan
   #:construction-placement
   #:construction-resource
   #:coordinator
   #:copy-checkpoint-actor
   #:copy-object-representation
   #:copy-object-to-staging
   #:correct-finalizer-referent
   #:cycle-cause-description
   #:cycle-cause-known-p
   #:cycle-counter-description
   #:cycle-counter-known-p
   #:cycle-reason-description
   #:cycle-reason-known-p
   #:cycle-result-algorithm
   #:cycle-result-cause
   #:cycle-result-count
   #:cycle-result-owner
   #:cycle-result-phase
   #:cycle-result-reason
   #:cycle-result-scope
   #:cycle-result-status
   #:deactivate-component
   #:describe-barrier-contribution
   #:describe-barrier-reservation-claim
   #:describe-construction-constraint
   #:describe-ephemeron
   #:describe-managed-arena-offer
   #:describe-metadata-field-offer
   #:describe-object-kind
   #:describe-object-start-binding
   #:describe-placement-request
   #:describe-resource-contribution
   #:describe-result-contribution
   #:describe-weak-location
   #:drain-pending-finalizers
   #:end-collector-checkpoint
   #:environment-default-heap
   #:evha-manager
   #:fatal-diagnostic
   #:fence
   #:field-cas
   #:field-read
   #:field-write
   #:finish-movement-participant
   #:finish-space
   #:finish-trace-context
   #:flush-address-translations
   #:freeze-finalizer-candidate
   #:heap-of
   #:initialize-component
   #:initialize-object
   #:inline-marks
   #:install-managed-layout
   #:install-staged-object
   #:load-reference
   #:load-root
   #:make-barrier-contribution
   #:make-barrier-reservation-claim
   #:make-construction-constraint
   #:make-cycle-result-record
   #:make-environment-heap
   #:make-ephemeron-description
   #:make-metadata-field-offer
   #:make-object-kind-description
   #:make-object-start-binding
   #:make-placement-request
   #:make-reference-location-handle
   #:make-resource-contribution
   #:make-result-contribution
   #:make-staged-reference-location-handle
   #:make-weak-location-description
   #:managed-arena-offer
   #:map-checkpoint-ranges
   #:map-cycle-deaths
   #:map-cycle-movements
   #:map-ephemeron-descriptors
   #:map-finalizer-registrations
   #:map-logical-pages
   #:map-provider-roots
   #:map-reference-locations
   #:map-root-locations
   #:map-staged-ephemeron-descriptors
   #:map-staged-reference-locations
   #:map-staged-weak-descriptors
   #:map-trace-discoveries
   #:map-weak-descriptors
   #:mark-consumer
   #:mark-demo-plan
   #:mark-map
   #:marked-space
   #:metadata
   #:metadata-bounds
   #:metadata-cas
   #:metadata-clear-bit
   #:metadata-default-value
   #:metadata-fold
   #:metadata-map-present
   #:metadata-project
   #:metadata-ref
   #:metadata-reset
   #:metadata-reset-range
   #:metadata-set
   #:metadata-set-bit
   #:metadata-transfer
   #:metadata-value-equal-p
   #:metadata-value-valid-p
   #:monotonic-clock
   #:movement-participant
   #:normalize-reference
   #:object-alignment
   #:object-kind
   #:object-kind-descriptor
   #:object-live-p
   #:object-size
   #:offered-metadata-fields
   #:prepare-checkpoint-actor
   #:prepare-movement-participant
   #:prepare-space
   #:prepare-space-ownership-update
   #:protect-logical-pages
   #:publish-pending-finalizers
   #:range-metadata
   #:rebuild-reference
   #:reclaim-space
   #:reference-address
   #:reference-encoding-equal-p
   #:reference-equal
   #:refill-mutator
   #:register-finalizer
   #:register-root-provider
   #:release-construction-resource
   #:release-managed-layout
   #:release-safepoint
   #:remap-logical-pages
   #:request-safepoint
   #:reserve-virtual-range
   #:restore-collector-checkpoint
   #:root-location-kind
   #:root-provider-load
   #:root-provider-read
   #:root-provider-store
   #:scalar-inline-marks
   #:shutdown-configuration
   #:side-marks
   #:space-object-start-map
   #:space-of-reference
   #:stopped-root-pass
   #:store-reference-raw
   #:store-root
   #:trace-abandon-object
   #:trace-await-claim
   #:trace-claim-object
   #:trace-commit-object
   #:trace-context-cycle
   #:trace-context-scope
   #:trace-discovery-count
   #:trace-fail
   #:trace-finish-work
   #:trace-object
   #:trace-reference
   #:trace-scope-contains-p
   #:trace-take-work
   #:transferable-metadata
   #:unbind-mutator
   #:unmap-logical-pages
   #:unregister-root-provider
   #:update-space-ownership
   #:valid-reference-p
   #:validate-component
   #:validate-managed-layout
   #:with-root-snapshot
))
